apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-keycloak-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zta-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres-keycloak
type: Opaque
data:
  postgres-password: {{ .Values.postgresKeycloak.password | b64enc | quote }}
