{{- $component := "operator" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "casa-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "casa-control-plane.selectorLabels" (dict "Release" .Release "Chart" .Chart "component" $component) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "casa-control-plane.selectorLabels" (dict "Release" .Release "Chart" .Chart "component" $component) | nindent 8 }}
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ .Release.Name }}-operator
      {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          env:
            - name: AUTH_SERVICE_URL
              value: {{ default (include "casa-control-plane.authServiceUrl" .) .Values.operator.authServiceUrl | quote }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
