# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.api.multi_agent_systems_api import MultiAgentSystemsApi


class TestMultiAgentSystemsApi(unittest.TestCase):
    """MultiAgentSystemsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MultiAgentSystemsApi()

    def tearDown(self) -> None:
        pass

    def test_bind_apps_mas_mas_id_bind_apps_post(self) -> None:
        """Test case for bind_apps_mas_mas_id_bind_apps_post

        Bind Apps
        """
        pass

    def test_create_mas_mas_put(self) -> None:
        """Test case for create_mas_mas_put

        Create Mas
        """
        pass

    def test_delete_mas_mas_mas_id_delete(self) -> None:
        """Test case for delete_mas_mas_mas_id_delete

        Delete Mas
        """
        pass

    def test_get_all_mas_mas_get(self) -> None:
        """Test case for get_all_mas_mas_get

        Get All Mas
        """
        pass

    def test_get_mas_apps_mas_mas_id_apps_get(self) -> None:
        """Test case for get_mas_apps_mas_mas_id_apps_get

        Get Mas Apps
        """
        pass

    def test_get_mas_by_id_mas_mas_id_get(self) -> None:
        """Test case for get_mas_by_id_mas_mas_id_get

        Get Mas By Id
        """
        pass

    def test_update_mas_mas_mas_id_post(self) -> None:
        """Test case for update_mas_mas_mas_id_post

        Update Mas
        """
        pass


if __name__ == '__main__':
    unittest.main()
