# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.models.k8s_llm_call_mapping import K8sLlmCallMapping

class TestK8sLlmCallMapping(unittest.TestCase):
    """K8sLlmCallMapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> K8sLlmCallMapping:
        """Test K8sLlmCallMapping
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `K8sLlmCallMapping`
        """
        model = K8sLlmCallMapping()
        if include_optional:
            return K8sLlmCallMapping(
                id = '',
                namespace = '',
                trace_id = '',
                mas_id = '',
                app_id = '',
                user_input_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return K8sLlmCallMapping(
                namespace = '',
                trace_id = '',
                mas_id = '',
                app_id = '',
                user_input_id = '',
        )
        """

    def testK8sLlmCallMapping(self):
        """Test K8sLlmCallMapping"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
