# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.api.user_inputs_api import UserInputsApi


class TestUserInputsApi(unittest.TestCase):
    """UserInputsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserInputsApi()

    def tearDown(self) -> None:
        pass

    def test_create_user_input(self) -> None:
        """Test case for create_user_input

        Create User Input
        """
        pass

    def test_get_user_input_by_tag(self) -> None:
        """Test case for get_user_input_by_tag

        Get User Input By Tag
        """
        pass


if __name__ == '__main__':
    unittest.main()
