# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.models.mas_list_response import MASListResponse

class TestMASListResponse(unittest.TestCase):
    """MASListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MASListResponse:
        """Test MASListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MASListResponse`
        """
        model = MASListResponse()
        if include_optional:
            return MASListResponse(
                api_version = 'zta.io/v1alpha1',
                kind = 'MultiAgentSystemList',
                items = [
                    identity_auth_sdk.models.multi_agent_system_crd.MultiAgentSystemCRD(
                        api_version = 'zta.io/v1alpha1', 
                        kind = 'MultiAgentSystem', 
                        metadata = identity_auth_sdk.models.multi_agent_system_metadata.MultiAgentSystemMetadata(
                            name = '', 
                            namespace = '', 
                            uid = '', 
                            resource_version = '', 
                            generation = 56, 
                            labels = { }, 
                            annotations = { }, ), 
                        spec = identity_auth_sdk.models.multi_agent_system_spec.MultiAgentSystemSpec(
                            name = '', 
                            enabled_tool_checks = [
                                'DETERMINISTIC_TOOL_SELECTED'
                                ], 
                            apps = [
                                identity_auth_sdk.models.app_spec.AppSpec(
                                    name = '', 
                                    type = null, 
                                    base_url = '', )
                                ], ), 
                        status = null, )
                    ]
            )
        else:
            return MASListResponse(
                items = [
                    identity_auth_sdk.models.multi_agent_system_crd.MultiAgentSystemCRD(
                        api_version = 'zta.io/v1alpha1', 
                        kind = 'MultiAgentSystem', 
                        metadata = identity_auth_sdk.models.multi_agent_system_metadata.MultiAgentSystemMetadata(
                            name = '', 
                            namespace = '', 
                            uid = '', 
                            resource_version = '', 
                            generation = 56, 
                            labels = { }, 
                            annotations = { }, ), 
                        spec = identity_auth_sdk.models.multi_agent_system_spec.MultiAgentSystemSpec(
                            name = '', 
                            enabled_tool_checks = [
                                'DETERMINISTIC_TOOL_SELECTED'
                                ], 
                            apps = [
                                identity_auth_sdk.models.app_spec.AppSpec(
                                    name = '', 
                                    type = null, 
                                    base_url = '', )
                                ], ), 
                        status = null, )
                    ],
        )
        """

    def testMASListResponse(self):
        """Test MASListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
