# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.api.authorization_server_api import AuthorizationServerApi


class TestAuthorizationServerApi(unittest.TestCase):
    """AuthorizationServerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthorizationServerApi()

    def tearDown(self) -> None:
        pass

    def test_app_metadata(self) -> None:
        """Test case for app_metadata

        App Metadata
        """
        pass

    def test_health_check_health_get(self) -> None:
        """Test case for health_check_health_get

        Health Check
        """
        pass

    def test_introspect(self) -> None:
        """Test case for introspect

        Introspect
        """
        pass

    def test_token(self) -> None:
        """Test case for token

        Token
        """
        pass

    def test_token_exchange(self) -> None:
        """Test case for token_exchange

        Token Exchange
        """
        pass


if __name__ == '__main__':
    unittest.main()
