# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.api.kubernetes_resources_api import KubernetesResourcesApi


class TestKubernetesResourcesApi(unittest.TestCase):
    """KubernetesResourcesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KubernetesResourcesApi()

    def tearDown(self) -> None:
        pass

    def test_cache_load_token(self) -> None:
        """Test case for cache_load_token

        Load Token
        """
        pass

    def test_cache_store_token(self) -> None:
        """Test case for cache_store_token

        Store Token
        """
        pass

    def test_get_k8s_mas_by_app_host(self) -> None:
        """Test case for get_k8s_mas_by_app_host

        Get K8S Mas By App Host
        """
        pass


if __name__ == '__main__':
    unittest.main()
