# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.models.tool_check_type import ToolCheckType

class TestToolCheckType(unittest.TestCase):
    """ToolCheckType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testToolCheckType(self):
        """Test ToolCheckType"""
        # inst = ToolCheckType()

if __name__ == '__main__':
    unittest.main()
