# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.api.scopes_api import ScopesApi


class TestScopesApi(unittest.TestCase):
    """ScopesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScopesApi()

    def tearDown(self) -> None:
        pass

    def test_create_scope_scopes_post(self) -> None:
        """Test case for create_scope_scopes_post

        Create Scope
        """
        pass

    def test_delete_scope_scopes_scope_id_delete(self) -> None:
        """Test case for delete_scope_scopes_scope_id_delete

        Delete Scope
        """
        pass

    def test_get_scope_scopes_scope_id_get(self) -> None:
        """Test case for get_scope_scopes_scope_id_get

        Get Scope
        """
        pass

    def test_get_scopes_scopes_get(self) -> None:
        """Test case for get_scopes_scopes_get

        Get Scopes
        """
        pass

    def test_update_scope_scopes_scope_id_put(self) -> None:
        """Test case for update_scope_scopes_scope_id_put

        Update Scope
        """
        pass


if __name__ == '__main__':
    unittest.main()
