# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.api.kubernetes_crds_api import KubernetesCRDsApi


class TestKubernetesCRDsApi(unittest.TestCase):
    """KubernetesCRDsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KubernetesCRDsApi()

    def tearDown(self) -> None:
        pass

    def test_create_mas_crd_k8s_namespaces_namespace_mas_post(self) -> None:
        """Test case for create_mas_crd_k8s_namespaces_namespace_mas_post

        Create Mas Crd
        """
        pass

    def test_delete_mas_crd_k8s_namespaces_namespace_mas_name_delete(self) -> None:
        """Test case for delete_mas_crd_k8s_namespaces_namespace_mas_name_delete

        Delete Mas Crd
        """
        pass

    def test_get_mas_crd_k8s_namespaces_namespace_mas_mas_id_get(self) -> None:
        """Test case for get_mas_crd_k8s_namespaces_namespace_mas_mas_id_get

        Get Mas Crd
        """
        pass

    def test_list_all_mas_crds_k8s_mas_get(self) -> None:
        """Test case for list_all_mas_crds_k8s_mas_get

        List All Mas Crds
        """
        pass

    def test_list_mas_crds_in_namespace_k8s_namespaces_namespace_mas_get(self) -> None:
        """Test case for list_mas_crds_in_namespace_k8s_namespaces_namespace_mas_get

        List Mas Crds In Namespace
        """
        pass

    def test_liveness_probe_k8s_healthz_get(self) -> None:
        """Test case for liveness_probe_k8s_healthz_get

        Liveness Probe
        """
        pass

    def test_readiness_probe_k8s_readyz_get(self) -> None:
        """Test case for readiness_probe_k8s_readyz_get

        Readiness Probe
        """
        pass

    def test_update_mas_crd_k8s_namespaces_namespace_mas_name_put(self) -> None:
        """Test case for update_mas_crd_k8s_namespaces_namespace_mas_name_put

        Update Mas Crd
        """
        pass

    def test_update_mas_status_k8s_namespaces_namespace_mas_name_status_patch(self) -> None:
        """Test case for update_mas_status_k8s_namespaces_namespace_mas_name_status_patch

        Update Mas Status
        """
        pass

    def test_watch_all_mas_k8s_watch_multiagentsystems_get(self) -> None:
        """Test case for watch_all_mas_k8s_watch_multiagentsystems_get

        Watch All Mas
        """
        pass

    def test_watch_mas_in_namespace_k8s_watch_namespaces_namespace_multiagentsystems_get(self) -> None:
        """Test case for watch_mas_in_namespace_k8s_watch_namespaces_namespace_multiagentsystems_get

        Watch Mas In Namespace
        """
        pass

    def test_watch_policies_in_namespace_k8s_watch_namespaces_namespace_ztapolicies_get(self) -> None:
        """Test case for watch_policies_in_namespace_k8s_watch_namespaces_namespace_ztapolicies_get

        Watch Policies In Namespace
        """
        pass


if __name__ == '__main__':
    unittest.main()
