# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.models.multi_agent_system_spec_output import MultiAgentSystemSpecOutput

class TestMultiAgentSystemSpecOutput(unittest.TestCase):
    """MultiAgentSystemSpecOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MultiAgentSystemSpecOutput:
        """Test MultiAgentSystemSpecOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MultiAgentSystemSpecOutput`
        """
        model = MultiAgentSystemSpecOutput()
        if include_optional:
            return MultiAgentSystemSpecOutput(
                name = '',
                enabled_tool_checks = [
                    'DETERMINISTIC_TOOL_SELECTED'
                    ],
                apps = [
                    identity_auth_sdk.models.app_spec.AppSpec(
                        name = '', 
                        type = null, 
                        base_url = '', )
                    ]
            )
        else:
            return MultiAgentSystemSpecOutput(
                name = '',
        )
        """

    def testMultiAgentSystemSpecOutput(self):
        """Test MultiAgentSystemSpecOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
