# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.api.traces_api import TracesApi


class TestTracesApi(unittest.TestCase):
    """TracesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TracesApi()

    def tearDown(self) -> None:
        pass

    def test_get_traces_trace_get(self) -> None:
        """Test case for get_traces_trace_get

        Get Traces
        """
        pass

    def test_trace_llm_call_end(self) -> None:
        """Test case for trace_llm_call_end

        Trace Llm Call End
        """
        pass

    def test_trace_llm_call_start(self) -> None:
        """Test case for trace_llm_call_start

        Trace Llm Call Start
        """
        pass


if __name__ == '__main__':
    unittest.main()
