# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.models.k8s_app_spec_view_model import K8sAppSpecViewModel

class TestK8sAppSpecViewModel(unittest.TestCase):
    """K8sAppSpecViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> K8sAppSpecViewModel:
        """Test K8sAppSpecViewModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `K8sAppSpecViewModel`
        """
        model = K8sAppSpecViewModel()
        if include_optional:
            return K8sAppSpecViewModel(
                id = '',
                name = '',
                type = 'agent',
                url_host = '',
                url_scheme = '',
                prompt_field_json_path = '',
                kubernetes_workload_name = '',
                mas_crd_id = '',
                app_id = ''
            )
        else:
            return K8sAppSpecViewModel(
                name = '',
                type = 'agent',
                url_host = '',
                url_scheme = '',
        )
        """

    def testK8sAppSpecViewModel(self):
        """Test K8sAppSpecViewModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
