default_stages: [pre-commit, pre-push]
exclude: "^demo/"
repos:
    - repo: https://github.com/google/addlicense
      rev: v1.2.0
      hooks:
          - id: addlicense # Add license header to files
            args:
                - -ignore
                - "**/node_modules/**"
                - -ignore
                - "**/vendor/**"
                - -c
                - "Cisco Systems, Inc. and its affiliates"
                - -l
                - Apache-2.0
                - -s=only
            files: \.(go|ts|tsx|js|jsx|py|sh|yaml|yml|css|scss)$
            exclude: |
                (?x)^(
                |docs/ui/generatedSidebarsProtodocs.js           # generated doc JS file
                )

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-added-large-files # Prevent giant files from being committed
            args: ["--maxkb=2500"] # Increase limit to 2.5MB
            exclude: "^casa-explorer-ui/\\.yarn/releases/" # Yarn binaries are meant to be committed
          - id: detect-private-key # Checks for the existence of private keys
            exclude: "^sdk/"
          - id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem
            exclude: "^sdk/"
          - id: check-merge-conflict # Check for files that contain merge conflict strings
            exclude: "^sdk/"
          - id: check-symlinks # Checks for symlinks which do not point to anything
            exclude: "^sdk/"
          - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
            exclude: "^sdk/"
          - id: mixed-line-ending # Replaces or checks mixed line ending
            exclude: "^sdk/"
          - id: trailing-whitespace # Trims trailing whitespace
            args: [--markdown-linebreak-ext=md]
            exclude: "^sdk/"

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.12.7
      hooks:
          - id: ruff
            args: [--fix]
            types_or: [python, pyi, jupyter]
            exclude: |
                (?x)^(
                  sdk/    # generated python sdk
                )
          - id: ruff-format
            types_or: [python, pyi, jupyter]
            exclude: |
                (?x)^(
                  sdk/    # generated python sdk
                )

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.17.1
      hooks:
          - id: mypy
            additional_dependencies: [types-PyYAML, types-requests]
            exclude: |
                (?x)^(
                  sdk/    # generated python sdk
                )

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
          - id: shellcheck
            exclude: |
                (?x)^(
                  sdk/    # generated python sdk
                )
