{{- $component := "postgres-auth" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zta-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  type: ClusterIP
  selector:
    {{- include "zta-control-plane.selectorLabels" (dict "Release" .Release "Chart" .Chart "component" $component) | nindent 4 }}
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: postgres
