# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_auth_sdk.models.token_introspect_response import TokenIntrospectResponse

class TestTokenIntrospectResponse(unittest.TestCase):
    """TokenIntrospectResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenIntrospectResponse:
        """Test TokenIntrospectResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenIntrospectResponse`
        """
        model = TokenIntrospectResponse()
        if include_optional:
            return TokenIntrospectResponse(
                client_id = '',
                scope = '',
                sub = '',
                act = identity_auth_sdk.models.actor_claim.ActorClaim(
                    sub = '', 
                    act = null, ),
                other = { },
                exp = 56,
                user_input_id = '',
                app_id = '',
                tools = [
                    ''
                    ],
                active = True
            )
        else:
            return TokenIntrospectResponse(
                active = True,
        )
        """

    def testTokenIntrospectResponse(self):
        """Test TokenIntrospectResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
