# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_metadata_response import AppMetadataResponse

class TestAppMetadataResponse(unittest.TestCase):
    """AppMetadataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppMetadataResponse:
        """Test AppMetadataResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppMetadataResponse`
        """
        model = AppMetadataResponse()
        if include_optional:
            return AppMetadataResponse(
                client_id = '',
                client_name = '',
                grant_types = [
                    ''
                    ],
                response_types = [
                    ''
                    ],
                token_endpoint_auth_method = '',
                jwks_uri = ''
            )
        else:
            return AppMetadataResponse(
                client_id = '',
                client_name = '',
                grant_types = [
                    ''
                    ],
                response_types = [
                    ''
                    ],
                token_endpoint_auth_method = '',
                jwks_uri = '',
        )
        """

    def testAppMetadataResponse(self):
        """Test AppMetadataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
