# coding: utf-8

"""FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from identity_auth_sdk.models.actor_claim import ActorClaim


class TestActorClaim(unittest.TestCase):
    """ActorClaim unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActorClaim:
        """Test ActorClaim
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `ActorClaim`
        """
        model = ActorClaim()
        if include_optional:
            return ActorClaim(
                sub = '',
                act = identity_auth_sdk.models.actor_claim.ActorClaim(
                    sub = '',
                    act = null, )
            )
        else:
            return ActorClaim(
                sub = '',
        )
        """

    def testActorClaim(self):
        """Test ActorClaim"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
