/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// MultiAgentSystemsAPIService MultiAgentSystemsAPI service
type MultiAgentSystemsAPIService service

type ApiBindAppsMasMasIdBindAppsPostRequest struct {
	ctx context.Context
	ApiService *MultiAgentSystemsAPIService
	masId string
	multiAgentSystemAppsBindingRequest *MultiAgentSystemAppsBindingRequest
}

func (r ApiBindAppsMasMasIdBindAppsPostRequest) MultiAgentSystemAppsBindingRequest(multiAgentSystemAppsBindingRequest MultiAgentSystemAppsBindingRequest) ApiBindAppsMasMasIdBindAppsPostRequest {
	r.multiAgentSystemAppsBindingRequest = &multiAgentSystemAppsBindingRequest
	return r
}

func (r ApiBindAppsMasMasIdBindAppsPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.BindAppsMasMasIdBindAppsPostExecute(r)
}

/*
BindAppsMasMasIdBindAppsPost Bind Apps

Bind a list of apps with an existing multi agent system.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param masId
 @return ApiBindAppsMasMasIdBindAppsPostRequest
*/
func (a *MultiAgentSystemsAPIService) BindAppsMasMasIdBindAppsPost(ctx context.Context, masId string) ApiBindAppsMasMasIdBindAppsPostRequest {
	return ApiBindAppsMasMasIdBindAppsPostRequest{
		ApiService: a,
		ctx: ctx,
		masId: masId,
	}
}

// Execute executes the request
func (a *MultiAgentSystemsAPIService) BindAppsMasMasIdBindAppsPostExecute(r ApiBindAppsMasMasIdBindAppsPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MultiAgentSystemsAPIService.BindAppsMasMasIdBindAppsPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/mas/{mas_id}/bind_apps"
	localVarPath = strings.Replace(localVarPath, "{"+"mas_id"+"}", url.PathEscape(parameterValueToString(r.masId, "masId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.multiAgentSystemAppsBindingRequest == nil {
		return nil, reportError("multiAgentSystemAppsBindingRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.multiAgentSystemAppsBindingRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiCreateMasMasPutRequest struct {
	ctx context.Context
	ApiService *MultiAgentSystemsAPIService
	multiAgentSystemCreateRequest *MultiAgentSystemCreateRequest
}

func (r ApiCreateMasMasPutRequest) MultiAgentSystemCreateRequest(multiAgentSystemCreateRequest MultiAgentSystemCreateRequest) ApiCreateMasMasPutRequest {
	r.multiAgentSystemCreateRequest = &multiAgentSystemCreateRequest
	return r
}

func (r ApiCreateMasMasPutRequest) Execute() (*MultiAgentSystem, *http.Response, error) {
	return r.ApiService.CreateMasMasPutExecute(r)
}

/*
CreateMasMasPut Create Mas

Create a new multi agent system.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateMasMasPutRequest
*/
func (a *MultiAgentSystemsAPIService) CreateMasMasPut(ctx context.Context) ApiCreateMasMasPutRequest {
	return ApiCreateMasMasPutRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return MultiAgentSystem
func (a *MultiAgentSystemsAPIService) CreateMasMasPutExecute(r ApiCreateMasMasPutRequest) (*MultiAgentSystem, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MultiAgentSystem
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MultiAgentSystemsAPIService.CreateMasMasPut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/mas"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.multiAgentSystemCreateRequest == nil {
		return localVarReturnValue, nil, reportError("multiAgentSystemCreateRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.multiAgentSystemCreateRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteMasMasMasIdDeleteRequest struct {
	ctx context.Context
	ApiService *MultiAgentSystemsAPIService
	masId string
}

func (r ApiDeleteMasMasMasIdDeleteRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.DeleteMasMasMasIdDeleteExecute(r)
}

/*
DeleteMasMasMasIdDelete Delete Mas

Delete an existing multi agent system.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param masId
 @return ApiDeleteMasMasMasIdDeleteRequest
*/
func (a *MultiAgentSystemsAPIService) DeleteMasMasMasIdDelete(ctx context.Context, masId string) ApiDeleteMasMasMasIdDeleteRequest {
	return ApiDeleteMasMasMasIdDeleteRequest{
		ApiService: a,
		ctx: ctx,
		masId: masId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *MultiAgentSystemsAPIService) DeleteMasMasMasIdDeleteExecute(r ApiDeleteMasMasMasIdDeleteRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MultiAgentSystemsAPIService.DeleteMasMasMasIdDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/mas/{mas_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"mas_id"+"}", url.PathEscape(parameterValueToString(r.masId, "masId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetAllMasMasGetRequest struct {
	ctx context.Context
	ApiService *MultiAgentSystemsAPIService
	page *int32
	pageSize *int32
	q *string
	includeMetrics *bool
}

func (r ApiGetAllMasMasGetRequest) Page(page int32) ApiGetAllMasMasGetRequest {
	r.page = &page
	return r
}

func (r ApiGetAllMasMasGetRequest) PageSize(pageSize int32) ApiGetAllMasMasGetRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiGetAllMasMasGetRequest) Q(q string) ApiGetAllMasMasGetRequest {
	r.q = &q
	return r
}

func (r ApiGetAllMasMasGetRequest) IncludeMetrics(includeMetrics bool) ApiGetAllMasMasGetRequest {
	r.includeMetrics = &includeMetrics
	return r
}

func (r ApiGetAllMasMasGetRequest) Execute() (*MASListResponse, *http.Response, error) {
	return r.ApiService.GetAllMasMasGetExecute(r)
}

/*
GetAllMasMasGet Get All Mas

Get a paginated list of multi agent systems, with inline app summaries and optional trace counts.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetAllMasMasGetRequest
*/
func (a *MultiAgentSystemsAPIService) GetAllMasMasGet(ctx context.Context) ApiGetAllMasMasGetRequest {
	return ApiGetAllMasMasGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return MASListResponse
func (a *MultiAgentSystemsAPIService) GetAllMasMasGetExecute(r ApiGetAllMasMasGetRequest) (*MASListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MASListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MultiAgentSystemsAPIService.GetAllMasMasGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/mas"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	} else {
		var defaultValue int32 = 1
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", defaultValue, "form", "")
		r.page = &defaultValue
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "form", "")
	} else {
		var defaultValue int32 = 20
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	if r.q != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "q", r.q, "form", "")
	}
	if r.includeMetrics != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "include_metrics", r.includeMetrics, "form", "")
	} else {
		var defaultValue bool = false
		parameterAddToHeaderOrQuery(localVarQueryParams, "include_metrics", defaultValue, "form", "")
		r.includeMetrics = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetMasAppsMasMasIdAppsGetRequest struct {
	ctx context.Context
	ApiService *MultiAgentSystemsAPIService
	masId string
}

func (r ApiGetMasAppsMasMasIdAppsGetRequest) Execute() ([]AppViewModel, *http.Response, error) {
	return r.ApiService.GetMasAppsMasMasIdAppsGetExecute(r)
}

/*
GetMasAppsMasMasIdAppsGet Get Mas Apps

Get all the apps related to a MAS.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param masId
 @return ApiGetMasAppsMasMasIdAppsGetRequest
*/
func (a *MultiAgentSystemsAPIService) GetMasAppsMasMasIdAppsGet(ctx context.Context, masId string) ApiGetMasAppsMasMasIdAppsGetRequest {
	return ApiGetMasAppsMasMasIdAppsGetRequest{
		ApiService: a,
		ctx: ctx,
		masId: masId,
	}
}

// Execute executes the request
//  @return []AppViewModel
func (a *MultiAgentSystemsAPIService) GetMasAppsMasMasIdAppsGetExecute(r ApiGetMasAppsMasMasIdAppsGetRequest) ([]AppViewModel, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []AppViewModel
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MultiAgentSystemsAPIService.GetMasAppsMasMasIdAppsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/mas/{mas_id}/apps"
	localVarPath = strings.Replace(localVarPath, "{"+"mas_id"+"}", url.PathEscape(parameterValueToString(r.masId, "masId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetMasByIdMasMasIdGetRequest struct {
	ctx context.Context
	ApiService *MultiAgentSystemsAPIService
	masId string
	includeMetrics *bool
}

func (r ApiGetMasByIdMasMasIdGetRequest) IncludeMetrics(includeMetrics bool) ApiGetMasByIdMasMasIdGetRequest {
	r.includeMetrics = &includeMetrics
	return r
}

func (r ApiGetMasByIdMasMasIdGetRequest) Execute() (*MASViewModel, *http.Response, error) {
	return r.ApiService.GetMasByIdMasMasIdGetExecute(r)
}

/*
GetMasByIdMasMasIdGet Get Mas By Id

Get a multi agent system by id.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param masId
 @return ApiGetMasByIdMasMasIdGetRequest
*/
func (a *MultiAgentSystemsAPIService) GetMasByIdMasMasIdGet(ctx context.Context, masId string) ApiGetMasByIdMasMasIdGetRequest {
	return ApiGetMasByIdMasMasIdGetRequest{
		ApiService: a,
		ctx: ctx,
		masId: masId,
	}
}

// Execute executes the request
//  @return MASViewModel
func (a *MultiAgentSystemsAPIService) GetMasByIdMasMasIdGetExecute(r ApiGetMasByIdMasMasIdGetRequest) (*MASViewModel, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MASViewModel
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MultiAgentSystemsAPIService.GetMasByIdMasMasIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/mas/{mas_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"mas_id"+"}", url.PathEscape(parameterValueToString(r.masId, "masId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.includeMetrics != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "include_metrics", r.includeMetrics, "form", "")
	} else {
		var defaultValue bool = false
		parameterAddToHeaderOrQuery(localVarQueryParams, "include_metrics", defaultValue, "form", "")
		r.includeMetrics = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetMasFlowRequest struct {
	ctx context.Context
	ApiService *MultiAgentSystemsAPIService
	masId string
}

func (r ApiGetMasFlowRequest) Execute() ([]MASFlowEdge, *http.Response, error) {
	return r.ApiService.GetMasFlowExecute(r)
}

/*
GetMasFlow Get Mas Flow

Get observed caller→callee MCP call flow edges for a MAS, aggregated from trace events.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param masId
 @return ApiGetMasFlowRequest
*/
func (a *MultiAgentSystemsAPIService) GetMasFlow(ctx context.Context, masId string) ApiGetMasFlowRequest {
	return ApiGetMasFlowRequest{
		ApiService: a,
		ctx: ctx,
		masId: masId,
	}
}

// Execute executes the request
//  @return []MASFlowEdge
func (a *MultiAgentSystemsAPIService) GetMasFlowExecute(r ApiGetMasFlowRequest) ([]MASFlowEdge, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []MASFlowEdge
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MultiAgentSystemsAPIService.GetMasFlow")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/mas/{mas_id}/flow"
	localVarPath = strings.Replace(localVarPath, "{"+"mas_id"+"}", url.PathEscape(parameterValueToString(r.masId, "masId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateMasMasMasIdPostRequest struct {
	ctx context.Context
	ApiService *MultiAgentSystemsAPIService
	masId string
	multiAgentSystemUpdateRequest *MultiAgentSystemUpdateRequest
}

func (r ApiUpdateMasMasMasIdPostRequest) MultiAgentSystemUpdateRequest(multiAgentSystemUpdateRequest MultiAgentSystemUpdateRequest) ApiUpdateMasMasMasIdPostRequest {
	r.multiAgentSystemUpdateRequest = &multiAgentSystemUpdateRequest
	return r
}

func (r ApiUpdateMasMasMasIdPostRequest) Execute() (*MultiAgentSystem, *http.Response, error) {
	return r.ApiService.UpdateMasMasMasIdPostExecute(r)
}

/*
UpdateMasMasMasIdPost Update Mas

Update an existing multi agent system instance.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param masId
 @return ApiUpdateMasMasMasIdPostRequest
*/
func (a *MultiAgentSystemsAPIService) UpdateMasMasMasIdPost(ctx context.Context, masId string) ApiUpdateMasMasMasIdPostRequest {
	return ApiUpdateMasMasMasIdPostRequest{
		ApiService: a,
		ctx: ctx,
		masId: masId,
	}
}

// Execute executes the request
//  @return MultiAgentSystem
func (a *MultiAgentSystemsAPIService) UpdateMasMasMasIdPostExecute(r ApiUpdateMasMasMasIdPostRequest) (*MultiAgentSystem, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MultiAgentSystem
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MultiAgentSystemsAPIService.UpdateMasMasMasIdPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/mas/{mas_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"mas_id"+"}", url.PathEscape(parameterValueToString(r.masId, "masId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.multiAgentSystemUpdateRequest == nil {
		return localVarReturnValue, nil, reportError("multiAgentSystemUpdateRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.multiAgentSystemUpdateRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
