/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MASUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MASUpdateRequest{}

// MASUpdateRequest Request model for updating a MultiAgentSystem via API.
type MASUpdateRequest struct {
	Spec MultiAgentSystemSpecInput `json:"spec"`
}

type _MASUpdateRequest MASUpdateRequest

// NewMASUpdateRequest instantiates a new MASUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMASUpdateRequest(spec MultiAgentSystemSpecInput) *MASUpdateRequest {
	this := MASUpdateRequest{}
	this.Spec = spec
	return &this
}

// NewMASUpdateRequestWithDefaults instantiates a new MASUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMASUpdateRequestWithDefaults() *MASUpdateRequest {
	this := MASUpdateRequest{}
	return &this
}

// GetSpec returns the Spec field value
func (o *MASUpdateRequest) GetSpec() MultiAgentSystemSpecInput {
	if o == nil {
		var ret MultiAgentSystemSpecInput
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *MASUpdateRequest) GetSpecOk() (*MultiAgentSystemSpecInput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *MASUpdateRequest) SetSpec(v MultiAgentSystemSpecInput) {
	o.Spec = v
}

func (o MASUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MASUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["spec"] = o.Spec
	return toSerialize, nil
}

func (o *MASUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spec",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMASUpdateRequest := _MASUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMASUpdateRequest)

	if err != nil {
		return err
	}

	*o = MASUpdateRequest(varMASUpdateRequest)

	return err
}

type NullableMASUpdateRequest struct {
	value *MASUpdateRequest
	isSet bool
}

func (v NullableMASUpdateRequest) Get() *MASUpdateRequest {
	return v.value
}

func (v *NullableMASUpdateRequest) Set(val *MASUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMASUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMASUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMASUpdateRequest(val *MASUpdateRequest) *NullableMASUpdateRequest {
	return &NullableMASUpdateRequest{value: val, isSet: true}
}

func (v NullableMASUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMASUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


