/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CASAPolicyCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CASAPolicyCreateRequest{}

// CASAPolicyCreateRequest Request model for creating a CASAPolicy via API.
type CASAPolicyCreateRequest struct {
	Metadata MultiAgentSystemMetadata `json:"metadata"`
	Spec CASAPolicySpec `json:"spec"`
}

type _CASAPolicyCreateRequest CASAPolicyCreateRequest

// NewCASAPolicyCreateRequest instantiates a new CASAPolicyCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCASAPolicyCreateRequest(metadata MultiAgentSystemMetadata, spec CASAPolicySpec) *CASAPolicyCreateRequest {
	this := CASAPolicyCreateRequest{}
	this.Metadata = metadata
	this.Spec = spec
	return &this
}

// NewCASAPolicyCreateRequestWithDefaults instantiates a new CASAPolicyCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCASAPolicyCreateRequestWithDefaults() *CASAPolicyCreateRequest {
	this := CASAPolicyCreateRequest{}
	return &this
}

// GetMetadata returns the Metadata field value
func (o *CASAPolicyCreateRequest) GetMetadata() MultiAgentSystemMetadata {
	if o == nil {
		var ret MultiAgentSystemMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *CASAPolicyCreateRequest) GetMetadataOk() (*MultiAgentSystemMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *CASAPolicyCreateRequest) SetMetadata(v MultiAgentSystemMetadata) {
	o.Metadata = v
}

// GetSpec returns the Spec field value
func (o *CASAPolicyCreateRequest) GetSpec() CASAPolicySpec {
	if o == nil {
		var ret CASAPolicySpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *CASAPolicyCreateRequest) GetSpecOk() (*CASAPolicySpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *CASAPolicyCreateRequest) SetSpec(v CASAPolicySpec) {
	o.Spec = v
}

func (o CASAPolicyCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CASAPolicyCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["metadata"] = o.Metadata
	toSerialize["spec"] = o.Spec
	return toSerialize, nil
}

func (o *CASAPolicyCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metadata",
		"spec",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCASAPolicyCreateRequest := _CASAPolicyCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCASAPolicyCreateRequest)

	if err != nil {
		return err
	}

	*o = CASAPolicyCreateRequest(varCASAPolicyCreateRequest)

	return err
}

type NullableCASAPolicyCreateRequest struct {
	value *CASAPolicyCreateRequest
	isSet bool
}

func (v NullableCASAPolicyCreateRequest) Get() *CASAPolicyCreateRequest {
	return v.value
}

func (v *NullableCASAPolicyCreateRequest) Set(val *CASAPolicyCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCASAPolicyCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCASAPolicyCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCASAPolicyCreateRequest(val *CASAPolicyCreateRequest) *NullableCASAPolicyCreateRequest {
	return &NullableCASAPolicyCreateRequest{value: val, isSet: true}
}

func (v NullableCASAPolicyCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCASAPolicyCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


