/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MultiAgentSystemCRD type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultiAgentSystemCRD{}

// MultiAgentSystemCRD Complete MultiAgentSystem Custom Resource Definition.
type MultiAgentSystemCRD struct {
	// API version
	ApiVersion *string `json:"apiVersion,omitempty"`
	// Resource kind
	Kind *string `json:"kind,omitempty"`
	Metadata MultiAgentSystemMetadata `json:"metadata"`
	Spec MultiAgentSystemSpecOutput `json:"spec"`
	Status NullableMultiAgentSystemStatus `json:"status,omitempty"`
}

type _MultiAgentSystemCRD MultiAgentSystemCRD

// NewMultiAgentSystemCRD instantiates a new MultiAgentSystemCRD object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultiAgentSystemCRD(metadata MultiAgentSystemMetadata, spec MultiAgentSystemSpecOutput) *MultiAgentSystemCRD {
	this := MultiAgentSystemCRD{}
	var apiVersion string = "zta.io/v1alpha1"
	this.ApiVersion = &apiVersion
	var kind string = "MultiAgentSystem"
	this.Kind = &kind
	this.Metadata = metadata
	this.Spec = spec
	return &this
}

// NewMultiAgentSystemCRDWithDefaults instantiates a new MultiAgentSystemCRD object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultiAgentSystemCRDWithDefaults() *MultiAgentSystemCRD {
	this := MultiAgentSystemCRD{}
	var apiVersion string = "zta.io/v1alpha1"
	this.ApiVersion = &apiVersion
	var kind string = "MultiAgentSystem"
	this.Kind = &kind
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *MultiAgentSystemCRD) GetApiVersion() string {
	if o == nil || IsNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiAgentSystemCRD) GetApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *MultiAgentSystemCRD) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *MultiAgentSystemCRD) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *MultiAgentSystemCRD) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiAgentSystemCRD) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *MultiAgentSystemCRD) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *MultiAgentSystemCRD) SetKind(v string) {
	o.Kind = &v
}

// GetMetadata returns the Metadata field value
func (o *MultiAgentSystemCRD) GetMetadata() MultiAgentSystemMetadata {
	if o == nil {
		var ret MultiAgentSystemMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *MultiAgentSystemCRD) GetMetadataOk() (*MultiAgentSystemMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *MultiAgentSystemCRD) SetMetadata(v MultiAgentSystemMetadata) {
	o.Metadata = v
}

// GetSpec returns the Spec field value
func (o *MultiAgentSystemCRD) GetSpec() MultiAgentSystemSpecOutput {
	if o == nil {
		var ret MultiAgentSystemSpecOutput
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *MultiAgentSystemCRD) GetSpecOk() (*MultiAgentSystemSpecOutput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *MultiAgentSystemCRD) SetSpec(v MultiAgentSystemSpecOutput) {
	o.Spec = v
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultiAgentSystemCRD) GetStatus() MultiAgentSystemStatus {
	if o == nil || IsNil(o.Status.Get()) {
		var ret MultiAgentSystemStatus
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultiAgentSystemCRD) GetStatusOk() (*MultiAgentSystemStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *MultiAgentSystemCRD) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableMultiAgentSystemStatus and assigns it to the Status field.
func (o *MultiAgentSystemCRD) SetStatus(v MultiAgentSystemStatus) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *MultiAgentSystemCRD) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *MultiAgentSystemCRD) UnsetStatus() {
	o.Status.Unset()
}

func (o MultiAgentSystemCRD) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultiAgentSystemCRD) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiVersion) {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	toSerialize["metadata"] = o.Metadata
	toSerialize["spec"] = o.Spec
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	return toSerialize, nil
}

func (o *MultiAgentSystemCRD) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metadata",
		"spec",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMultiAgentSystemCRD := _MultiAgentSystemCRD{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMultiAgentSystemCRD)

	if err != nil {
		return err
	}

	*o = MultiAgentSystemCRD(varMultiAgentSystemCRD)

	return err
}

type NullableMultiAgentSystemCRD struct {
	value *MultiAgentSystemCRD
	isSet bool
}

func (v NullableMultiAgentSystemCRD) Get() *MultiAgentSystemCRD {
	return v.value
}

func (v *NullableMultiAgentSystemCRD) Set(val *MultiAgentSystemCRD) {
	v.value = val
	v.isSet = true
}

func (v NullableMultiAgentSystemCRD) IsSet() bool {
	return v.isSet
}

func (v *NullableMultiAgentSystemCRD) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultiAgentSystemCRD(val *MultiAgentSystemCRD) *NullableMultiAgentSystemCRD {
	return &NullableMultiAgentSystemCRD{value: val, isSet: true}
}

func (v NullableMultiAgentSystemCRD) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultiAgentSystemCRD) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


