/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenIntrospectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenIntrospectResponse{}

// TokenIntrospectResponse Pydantic model for the token introspection response.
type TokenIntrospectResponse struct {
	ClientId NullableString `json:"client_id,omitempty"`
	Scope NullableString `json:"scope,omitempty"`
	Sub NullableString `json:"sub,omitempty"`
	Act NullableActorClaim `json:"act,omitempty"`
	// Resource annotations
	Other map[string]interface{} `json:"other,omitempty"`
	Exp NullableInt32 `json:"exp,omitempty"`
	UserInputId NullableString `json:"user_input_id,omitempty"`
	AppId NullableString `json:"app_id,omitempty"`
	MasId NullableString `json:"mas_id,omitempty"`
	Tools []string `json:"tools,omitempty"`
	Active bool `json:"active"`
}

type _TokenIntrospectResponse TokenIntrospectResponse

// NewTokenIntrospectResponse instantiates a new TokenIntrospectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenIntrospectResponse(active bool) *TokenIntrospectResponse {
	this := TokenIntrospectResponse{}
	this.Active = active
	return &this
}

// NewTokenIntrospectResponseWithDefaults instantiates a new TokenIntrospectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenIntrospectResponseWithDefaults() *TokenIntrospectResponse {
	this := TokenIntrospectResponse{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenIntrospectResponse) GetClientId() string {
	if o == nil || IsNil(o.ClientId.Get()) {
		var ret string
		return ret
	}
	return *o.ClientId.Get()
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenIntrospectResponse) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClientId.Get(), o.ClientId.IsSet()
}

// HasClientId returns a boolean if a field has been set.
func (o *TokenIntrospectResponse) HasClientId() bool {
	if o != nil && o.ClientId.IsSet() {
		return true
	}

	return false
}

// SetClientId gets a reference to the given NullableString and assigns it to the ClientId field.
func (o *TokenIntrospectResponse) SetClientId(v string) {
	o.ClientId.Set(&v)
}
// SetClientIdNil sets the value for ClientId to be an explicit nil
func (o *TokenIntrospectResponse) SetClientIdNil() {
	o.ClientId.Set(nil)
}

// UnsetClientId ensures that no value is present for ClientId, not even an explicit nil
func (o *TokenIntrospectResponse) UnsetClientId() {
	o.ClientId.Unset()
}

// GetScope returns the Scope field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenIntrospectResponse) GetScope() string {
	if o == nil || IsNil(o.Scope.Get()) {
		var ret string
		return ret
	}
	return *o.Scope.Get()
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenIntrospectResponse) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scope.Get(), o.Scope.IsSet()
}

// HasScope returns a boolean if a field has been set.
func (o *TokenIntrospectResponse) HasScope() bool {
	if o != nil && o.Scope.IsSet() {
		return true
	}

	return false
}

// SetScope gets a reference to the given NullableString and assigns it to the Scope field.
func (o *TokenIntrospectResponse) SetScope(v string) {
	o.Scope.Set(&v)
}
// SetScopeNil sets the value for Scope to be an explicit nil
func (o *TokenIntrospectResponse) SetScopeNil() {
	o.Scope.Set(nil)
}

// UnsetScope ensures that no value is present for Scope, not even an explicit nil
func (o *TokenIntrospectResponse) UnsetScope() {
	o.Scope.Unset()
}

// GetSub returns the Sub field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenIntrospectResponse) GetSub() string {
	if o == nil || IsNil(o.Sub.Get()) {
		var ret string
		return ret
	}
	return *o.Sub.Get()
}

// GetSubOk returns a tuple with the Sub field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenIntrospectResponse) GetSubOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sub.Get(), o.Sub.IsSet()
}

// HasSub returns a boolean if a field has been set.
func (o *TokenIntrospectResponse) HasSub() bool {
	if o != nil && o.Sub.IsSet() {
		return true
	}

	return false
}

// SetSub gets a reference to the given NullableString and assigns it to the Sub field.
func (o *TokenIntrospectResponse) SetSub(v string) {
	o.Sub.Set(&v)
}
// SetSubNil sets the value for Sub to be an explicit nil
func (o *TokenIntrospectResponse) SetSubNil() {
	o.Sub.Set(nil)
}

// UnsetSub ensures that no value is present for Sub, not even an explicit nil
func (o *TokenIntrospectResponse) UnsetSub() {
	o.Sub.Unset()
}

// GetAct returns the Act field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenIntrospectResponse) GetAct() ActorClaim {
	if o == nil || IsNil(o.Act.Get()) {
		var ret ActorClaim
		return ret
	}
	return *o.Act.Get()
}

// GetActOk returns a tuple with the Act field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenIntrospectResponse) GetActOk() (*ActorClaim, bool) {
	if o == nil {
		return nil, false
	}
	return o.Act.Get(), o.Act.IsSet()
}

// HasAct returns a boolean if a field has been set.
func (o *TokenIntrospectResponse) HasAct() bool {
	if o != nil && o.Act.IsSet() {
		return true
	}

	return false
}

// SetAct gets a reference to the given NullableActorClaim and assigns it to the Act field.
func (o *TokenIntrospectResponse) SetAct(v ActorClaim) {
	o.Act.Set(&v)
}
// SetActNil sets the value for Act to be an explicit nil
func (o *TokenIntrospectResponse) SetActNil() {
	o.Act.Set(nil)
}

// UnsetAct ensures that no value is present for Act, not even an explicit nil
func (o *TokenIntrospectResponse) UnsetAct() {
	o.Act.Unset()
}

// GetOther returns the Other field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenIntrospectResponse) GetOther() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Other
}

// GetOtherOk returns a tuple with the Other field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenIntrospectResponse) GetOtherOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Other) {
		return map[string]interface{}{}, false
	}
	return o.Other, true
}

// HasOther returns a boolean if a field has been set.
func (o *TokenIntrospectResponse) HasOther() bool {
	if o != nil && !IsNil(o.Other) {
		return true
	}

	return false
}

// SetOther gets a reference to the given map[string]interface{} and assigns it to the Other field.
func (o *TokenIntrospectResponse) SetOther(v map[string]interface{}) {
	o.Other = v
}

// GetExp returns the Exp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenIntrospectResponse) GetExp() int32 {
	if o == nil || IsNil(o.Exp.Get()) {
		var ret int32
		return ret
	}
	return *o.Exp.Get()
}

// GetExpOk returns a tuple with the Exp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenIntrospectResponse) GetExpOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Exp.Get(), o.Exp.IsSet()
}

// HasExp returns a boolean if a field has been set.
func (o *TokenIntrospectResponse) HasExp() bool {
	if o != nil && o.Exp.IsSet() {
		return true
	}

	return false
}

// SetExp gets a reference to the given NullableInt32 and assigns it to the Exp field.
func (o *TokenIntrospectResponse) SetExp(v int32) {
	o.Exp.Set(&v)
}
// SetExpNil sets the value for Exp to be an explicit nil
func (o *TokenIntrospectResponse) SetExpNil() {
	o.Exp.Set(nil)
}

// UnsetExp ensures that no value is present for Exp, not even an explicit nil
func (o *TokenIntrospectResponse) UnsetExp() {
	o.Exp.Unset()
}

// GetUserInputId returns the UserInputId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenIntrospectResponse) GetUserInputId() string {
	if o == nil || IsNil(o.UserInputId.Get()) {
		var ret string
		return ret
	}
	return *o.UserInputId.Get()
}

// GetUserInputIdOk returns a tuple with the UserInputId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenIntrospectResponse) GetUserInputIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserInputId.Get(), o.UserInputId.IsSet()
}

// HasUserInputId returns a boolean if a field has been set.
func (o *TokenIntrospectResponse) HasUserInputId() bool {
	if o != nil && o.UserInputId.IsSet() {
		return true
	}

	return false
}

// SetUserInputId gets a reference to the given NullableString and assigns it to the UserInputId field.
func (o *TokenIntrospectResponse) SetUserInputId(v string) {
	o.UserInputId.Set(&v)
}
// SetUserInputIdNil sets the value for UserInputId to be an explicit nil
func (o *TokenIntrospectResponse) SetUserInputIdNil() {
	o.UserInputId.Set(nil)
}

// UnsetUserInputId ensures that no value is present for UserInputId, not even an explicit nil
func (o *TokenIntrospectResponse) UnsetUserInputId() {
	o.UserInputId.Unset()
}

// GetAppId returns the AppId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenIntrospectResponse) GetAppId() string {
	if o == nil || IsNil(o.AppId.Get()) {
		var ret string
		return ret
	}
	return *o.AppId.Get()
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenIntrospectResponse) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppId.Get(), o.AppId.IsSet()
}

// HasAppId returns a boolean if a field has been set.
func (o *TokenIntrospectResponse) HasAppId() bool {
	if o != nil && o.AppId.IsSet() {
		return true
	}

	return false
}

// SetAppId gets a reference to the given NullableString and assigns it to the AppId field.
func (o *TokenIntrospectResponse) SetAppId(v string) {
	o.AppId.Set(&v)
}
// SetAppIdNil sets the value for AppId to be an explicit nil
func (o *TokenIntrospectResponse) SetAppIdNil() {
	o.AppId.Set(nil)
}

// UnsetAppId ensures that no value is present for AppId, not even an explicit nil
func (o *TokenIntrospectResponse) UnsetAppId() {
	o.AppId.Unset()
}

// GetMasId returns the MasId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenIntrospectResponse) GetMasId() string {
	if o == nil || IsNil(o.MasId.Get()) {
		var ret string
		return ret
	}
	return *o.MasId.Get()
}

// GetMasIdOk returns a tuple with the MasId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenIntrospectResponse) GetMasIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MasId.Get(), o.MasId.IsSet()
}

// HasMasId returns a boolean if a field has been set.
func (o *TokenIntrospectResponse) HasMasId() bool {
	if o != nil && o.MasId.IsSet() {
		return true
	}

	return false
}

// SetMasId gets a reference to the given NullableString and assigns it to the MasId field.
func (o *TokenIntrospectResponse) SetMasId(v string) {
	o.MasId.Set(&v)
}
// SetMasIdNil sets the value for MasId to be an explicit nil
func (o *TokenIntrospectResponse) SetMasIdNil() {
	o.MasId.Set(nil)
}

// UnsetMasId ensures that no value is present for MasId, not even an explicit nil
func (o *TokenIntrospectResponse) UnsetMasId() {
	o.MasId.Unset()
}

// GetTools returns the Tools field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenIntrospectResponse) GetTools() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenIntrospectResponse) GetToolsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tools) {
		return nil, false
	}
	return o.Tools, true
}

// HasTools returns a boolean if a field has been set.
func (o *TokenIntrospectResponse) HasTools() bool {
	if o != nil && !IsNil(o.Tools) {
		return true
	}

	return false
}

// SetTools gets a reference to the given []string and assigns it to the Tools field.
func (o *TokenIntrospectResponse) SetTools(v []string) {
	o.Tools = v
}

// GetActive returns the Active field value
func (o *TokenIntrospectResponse) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *TokenIntrospectResponse) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *TokenIntrospectResponse) SetActive(v bool) {
	o.Active = v
}

func (o TokenIntrospectResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenIntrospectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ClientId.IsSet() {
		toSerialize["client_id"] = o.ClientId.Get()
	}
	if o.Scope.IsSet() {
		toSerialize["scope"] = o.Scope.Get()
	}
	if o.Sub.IsSet() {
		toSerialize["sub"] = o.Sub.Get()
	}
	if o.Act.IsSet() {
		toSerialize["act"] = o.Act.Get()
	}
	if o.Other != nil {
		toSerialize["other"] = o.Other
	}
	if o.Exp.IsSet() {
		toSerialize["exp"] = o.Exp.Get()
	}
	if o.UserInputId.IsSet() {
		toSerialize["user_input_id"] = o.UserInputId.Get()
	}
	if o.AppId.IsSet() {
		toSerialize["app_id"] = o.AppId.Get()
	}
	if o.MasId.IsSet() {
		toSerialize["mas_id"] = o.MasId.Get()
	}
	if o.Tools != nil {
		toSerialize["tools"] = o.Tools
	}
	toSerialize["active"] = o.Active
	return toSerialize, nil
}

func (o *TokenIntrospectResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenIntrospectResponse := _TokenIntrospectResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenIntrospectResponse)

	if err != nil {
		return err
	}

	*o = TokenIntrospectResponse(varTokenIntrospectResponse)

	return err
}

type NullableTokenIntrospectResponse struct {
	value *TokenIntrospectResponse
	isSet bool
}

func (v NullableTokenIntrospectResponse) Get() *TokenIntrospectResponse {
	return v.value
}

func (v *NullableTokenIntrospectResponse) Set(val *TokenIntrospectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenIntrospectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenIntrospectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenIntrospectResponse(val *TokenIntrospectResponse) *NullableTokenIntrospectResponse {
	return &NullableTokenIntrospectResponse{value: val, isSet: true}
}

func (v NullableTokenIntrospectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenIntrospectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


