/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CASAPolicyTargetRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CASAPolicyTargetRef{}

// CASAPolicyTargetRef Reference to the workload this policy applies to.
type CASAPolicyTargetRef struct {
	// Workload kind: Deployment, StatefulSet, or Pod
	Kind string `json:"kind"`
	// Name of the target workload
	Name string `json:"name"`
}

type _CASAPolicyTargetRef CASAPolicyTargetRef

// NewCASAPolicyTargetRef instantiates a new CASAPolicyTargetRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCASAPolicyTargetRef(kind string, name string) *CASAPolicyTargetRef {
	this := CASAPolicyTargetRef{}
	this.Kind = kind
	this.Name = name
	return &this
}

// NewCASAPolicyTargetRefWithDefaults instantiates a new CASAPolicyTargetRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCASAPolicyTargetRefWithDefaults() *CASAPolicyTargetRef {
	this := CASAPolicyTargetRef{}
	return &this
}

// GetKind returns the Kind field value
func (o *CASAPolicyTargetRef) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *CASAPolicyTargetRef) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *CASAPolicyTargetRef) SetKind(v string) {
	o.Kind = v
}

// GetName returns the Name field value
func (o *CASAPolicyTargetRef) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CASAPolicyTargetRef) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CASAPolicyTargetRef) SetName(v string) {
	o.Name = v
}

func (o CASAPolicyTargetRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CASAPolicyTargetRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CASAPolicyTargetRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCASAPolicyTargetRef := _CASAPolicyTargetRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCASAPolicyTargetRef)

	if err != nil {
		return err
	}

	*o = CASAPolicyTargetRef(varCASAPolicyTargetRef)

	return err
}

type NullableCASAPolicyTargetRef struct {
	value *CASAPolicyTargetRef
	isSet bool
}

func (v NullableCASAPolicyTargetRef) Get() *CASAPolicyTargetRef {
	return v.value
}

func (v *NullableCASAPolicyTargetRef) Set(val *CASAPolicyTargetRef) {
	v.value = val
	v.isSet = true
}

func (v NullableCASAPolicyTargetRef) IsSet() bool {
	return v.isSet
}

func (v *NullableCASAPolicyTargetRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCASAPolicyTargetRef(val *CASAPolicyTargetRef) *NullableCASAPolicyTargetRef {
	return &NullableCASAPolicyTargetRef{value: val, isSet: true}
}

func (v NullableCASAPolicyTargetRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCASAPolicyTargetRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


