/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// ToolCheckFlags the model 'ToolCheckFlags'
type ToolCheckFlags int32

// List of ToolCheckFlags
const (
	_0 ToolCheckFlags = 0
	_1 ToolCheckFlags = 1
	_2 ToolCheckFlags = 2
	_4 ToolCheckFlags = 4
)

// All allowed values of ToolCheckFlags enum
var AllowedToolCheckFlagsEnumValues = []ToolCheckFlags{
	0,
	1,
	2,
	4,
}

func (v *ToolCheckFlags) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ToolCheckFlags(value)
	for _, existing := range AllowedToolCheckFlagsEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ToolCheckFlags", value)
}

// NewToolCheckFlagsFromValue returns a pointer to a valid ToolCheckFlags
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewToolCheckFlagsFromValue(v int32) (*ToolCheckFlags, error) {
	ev := ToolCheckFlags(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ToolCheckFlags: valid values are %v", v, AllowedToolCheckFlagsEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ToolCheckFlags) IsValid() bool {
	for _, existing := range AllowedToolCheckFlagsEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ToolCheckFlags value
func (v ToolCheckFlags) Ptr() *ToolCheckFlags {
	return &v
}

type NullableToolCheckFlags struct {
	value *ToolCheckFlags
	isSet bool
}

func (v NullableToolCheckFlags) Get() *ToolCheckFlags {
	return v.value
}

func (v *NullableToolCheckFlags) Set(val *ToolCheckFlags) {
	v.value = val
	v.isSet = true
}

func (v NullableToolCheckFlags) IsSet() bool {
	return v.isSet
}

func (v *NullableToolCheckFlags) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolCheckFlags(val *ToolCheckFlags) *NullableToolCheckFlags {
	return &NullableToolCheckFlags{value: val, isSet: true}
}

func (v NullableToolCheckFlags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolCheckFlags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

