/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppSummaryViewModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppSummaryViewModel{}

// AppSummaryViewModel Minimal app view model for embedding inside a MAS list entry.
type AppSummaryViewModel struct {
	Id string `json:"id"`
	Type string `json:"type"`
	Name string `json:"name"`
}

type _AppSummaryViewModel AppSummaryViewModel

// NewAppSummaryViewModel instantiates a new AppSummaryViewModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppSummaryViewModel(id string, type_ string, name string) *AppSummaryViewModel {
	this := AppSummaryViewModel{}
	this.Id = id
	this.Type = type_
	this.Name = name
	return &this
}

// NewAppSummaryViewModelWithDefaults instantiates a new AppSummaryViewModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppSummaryViewModelWithDefaults() *AppSummaryViewModel {
	this := AppSummaryViewModel{}
	return &this
}

// GetId returns the Id field value
func (o *AppSummaryViewModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppSummaryViewModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppSummaryViewModel) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *AppSummaryViewModel) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppSummaryViewModel) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppSummaryViewModel) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *AppSummaryViewModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AppSummaryViewModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AppSummaryViewModel) SetName(v string) {
	o.Name = v
}

func (o AppSummaryViewModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppSummaryViewModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *AppSummaryViewModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppSummaryViewModel := _AppSummaryViewModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppSummaryViewModel)

	if err != nil {
		return err
	}

	*o = AppSummaryViewModel(varAppSummaryViewModel)

	return err
}

type NullableAppSummaryViewModel struct {
	value *AppSummaryViewModel
	isSet bool
}

func (v NullableAppSummaryViewModel) Get() *AppSummaryViewModel {
	return v.value
}

func (v *NullableAppSummaryViewModel) Set(val *AppSummaryViewModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAppSummaryViewModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAppSummaryViewModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppSummaryViewModel(val *AppSummaryViewModel) *NullableAppSummaryViewModel {
	return &NullableAppSummaryViewModel{value: val, isSet: true}
}

func (v NullableAppSummaryViewModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppSummaryViewModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


