/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LLMCallStartedRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMCallStartedRequest{}

// LLMCallStartedRequest Request body for recording the start of an LLM call.
type LLMCallStartedRequest struct {
	CallId string `json:"call_id"`
	Prompt string `json:"prompt"`
	Tools NullableString `json:"tools,omitempty"`
}

type _LLMCallStartedRequest LLMCallStartedRequest

// NewLLMCallStartedRequest instantiates a new LLMCallStartedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMCallStartedRequest(callId string, prompt string) *LLMCallStartedRequest {
	this := LLMCallStartedRequest{}
	this.CallId = callId
	this.Prompt = prompt
	return &this
}

// NewLLMCallStartedRequestWithDefaults instantiates a new LLMCallStartedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMCallStartedRequestWithDefaults() *LLMCallStartedRequest {
	this := LLMCallStartedRequest{}
	return &this
}

// GetCallId returns the CallId field value
func (o *LLMCallStartedRequest) GetCallId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CallId
}

// GetCallIdOk returns a tuple with the CallId field value
// and a boolean to check if the value has been set.
func (o *LLMCallStartedRequest) GetCallIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallId, true
}

// SetCallId sets field value
func (o *LLMCallStartedRequest) SetCallId(v string) {
	o.CallId = v
}

// GetPrompt returns the Prompt field value
func (o *LLMCallStartedRequest) GetPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value
// and a boolean to check if the value has been set.
func (o *LLMCallStartedRequest) GetPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prompt, true
}

// SetPrompt sets field value
func (o *LLMCallStartedRequest) SetPrompt(v string) {
	o.Prompt = v
}

// GetTools returns the Tools field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMCallStartedRequest) GetTools() string {
	if o == nil || IsNil(o.Tools.Get()) {
		var ret string
		return ret
	}
	return *o.Tools.Get()
}

// GetToolsOk returns a tuple with the Tools field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMCallStartedRequest) GetToolsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tools.Get(), o.Tools.IsSet()
}

// HasTools returns a boolean if a field has been set.
func (o *LLMCallStartedRequest) HasTools() bool {
	if o != nil && o.Tools.IsSet() {
		return true
	}

	return false
}

// SetTools gets a reference to the given NullableString and assigns it to the Tools field.
func (o *LLMCallStartedRequest) SetTools(v string) {
	o.Tools.Set(&v)
}
// SetToolsNil sets the value for Tools to be an explicit nil
func (o *LLMCallStartedRequest) SetToolsNil() {
	o.Tools.Set(nil)
}

// UnsetTools ensures that no value is present for Tools, not even an explicit nil
func (o *LLMCallStartedRequest) UnsetTools() {
	o.Tools.Unset()
}

func (o LLMCallStartedRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMCallStartedRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["call_id"] = o.CallId
	toSerialize["prompt"] = o.Prompt
	if o.Tools.IsSet() {
		toSerialize["tools"] = o.Tools.Get()
	}
	return toSerialize, nil
}

func (o *LLMCallStartedRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"call_id",
		"prompt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLLMCallStartedRequest := _LLMCallStartedRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLLMCallStartedRequest)

	if err != nil {
		return err
	}

	*o = LLMCallStartedRequest(varLLMCallStartedRequest)

	return err
}

type NullableLLMCallStartedRequest struct {
	value *LLMCallStartedRequest
	isSet bool
}

func (v NullableLLMCallStartedRequest) Get() *LLMCallStartedRequest {
	return v.value
}

func (v *NullableLLMCallStartedRequest) Set(val *LLMCallStartedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMCallStartedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMCallStartedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMCallStartedRequest(val *LLMCallStartedRequest) *NullableLLMCallStartedRequest {
	return &NullableLLMCallStartedRequest{value: val, isSet: true}
}

func (v NullableLLMCallStartedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMCallStartedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


