/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MultiAgentSystemMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultiAgentSystemMetadata{}

// MultiAgentSystemMetadata Metadata for MultiAgentSystem CRD.
type MultiAgentSystemMetadata struct {
	// Resource name
	Name string `json:"name"`
	// Kubernetes namespace
	Namespace string `json:"namespace"`
	Uid NullableString `json:"uid,omitempty"`
	ResourceVersion NullableString `json:"resourceVersion,omitempty"`
	Generation NullableInt32 `json:"generation,omitempty"`
	Labels map[string]interface{} `json:"labels,omitempty"`
	Annotations map[string]interface{} `json:"annotations,omitempty"`
}

type _MultiAgentSystemMetadata MultiAgentSystemMetadata

// NewMultiAgentSystemMetadata instantiates a new MultiAgentSystemMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultiAgentSystemMetadata(name string, namespace string) *MultiAgentSystemMetadata {
	this := MultiAgentSystemMetadata{}
	this.Name = name
	this.Namespace = namespace
	return &this
}

// NewMultiAgentSystemMetadataWithDefaults instantiates a new MultiAgentSystemMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultiAgentSystemMetadataWithDefaults() *MultiAgentSystemMetadata {
	this := MultiAgentSystemMetadata{}
	return &this
}

// GetName returns the Name field value
func (o *MultiAgentSystemMetadata) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MultiAgentSystemMetadata) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MultiAgentSystemMetadata) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value
func (o *MultiAgentSystemMetadata) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *MultiAgentSystemMetadata) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *MultiAgentSystemMetadata) SetNamespace(v string) {
	o.Namespace = v
}

// GetUid returns the Uid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultiAgentSystemMetadata) GetUid() string {
	if o == nil || IsNil(o.Uid.Get()) {
		var ret string
		return ret
	}
	return *o.Uid.Get()
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultiAgentSystemMetadata) GetUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Uid.Get(), o.Uid.IsSet()
}

// HasUid returns a boolean if a field has been set.
func (o *MultiAgentSystemMetadata) HasUid() bool {
	if o != nil && o.Uid.IsSet() {
		return true
	}

	return false
}

// SetUid gets a reference to the given NullableString and assigns it to the Uid field.
func (o *MultiAgentSystemMetadata) SetUid(v string) {
	o.Uid.Set(&v)
}
// SetUidNil sets the value for Uid to be an explicit nil
func (o *MultiAgentSystemMetadata) SetUidNil() {
	o.Uid.Set(nil)
}

// UnsetUid ensures that no value is present for Uid, not even an explicit nil
func (o *MultiAgentSystemMetadata) UnsetUid() {
	o.Uid.Unset()
}

// GetResourceVersion returns the ResourceVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultiAgentSystemMetadata) GetResourceVersion() string {
	if o == nil || IsNil(o.ResourceVersion.Get()) {
		var ret string
		return ret
	}
	return *o.ResourceVersion.Get()
}

// GetResourceVersionOk returns a tuple with the ResourceVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultiAgentSystemMetadata) GetResourceVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceVersion.Get(), o.ResourceVersion.IsSet()
}

// HasResourceVersion returns a boolean if a field has been set.
func (o *MultiAgentSystemMetadata) HasResourceVersion() bool {
	if o != nil && o.ResourceVersion.IsSet() {
		return true
	}

	return false
}

// SetResourceVersion gets a reference to the given NullableString and assigns it to the ResourceVersion field.
func (o *MultiAgentSystemMetadata) SetResourceVersion(v string) {
	o.ResourceVersion.Set(&v)
}
// SetResourceVersionNil sets the value for ResourceVersion to be an explicit nil
func (o *MultiAgentSystemMetadata) SetResourceVersionNil() {
	o.ResourceVersion.Set(nil)
}

// UnsetResourceVersion ensures that no value is present for ResourceVersion, not even an explicit nil
func (o *MultiAgentSystemMetadata) UnsetResourceVersion() {
	o.ResourceVersion.Unset()
}

// GetGeneration returns the Generation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultiAgentSystemMetadata) GetGeneration() int32 {
	if o == nil || IsNil(o.Generation.Get()) {
		var ret int32
		return ret
	}
	return *o.Generation.Get()
}

// GetGenerationOk returns a tuple with the Generation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultiAgentSystemMetadata) GetGenerationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Generation.Get(), o.Generation.IsSet()
}

// HasGeneration returns a boolean if a field has been set.
func (o *MultiAgentSystemMetadata) HasGeneration() bool {
	if o != nil && o.Generation.IsSet() {
		return true
	}

	return false
}

// SetGeneration gets a reference to the given NullableInt32 and assigns it to the Generation field.
func (o *MultiAgentSystemMetadata) SetGeneration(v int32) {
	o.Generation.Set(&v)
}
// SetGenerationNil sets the value for Generation to be an explicit nil
func (o *MultiAgentSystemMetadata) SetGenerationNil() {
	o.Generation.Set(nil)
}

// UnsetGeneration ensures that no value is present for Generation, not even an explicit nil
func (o *MultiAgentSystemMetadata) UnsetGeneration() {
	o.Generation.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultiAgentSystemMetadata) GetLabels() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultiAgentSystemMetadata) GetLabelsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]interface{}{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *MultiAgentSystemMetadata) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]interface{} and assigns it to the Labels field.
func (o *MultiAgentSystemMetadata) SetLabels(v map[string]interface{}) {
	o.Labels = v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultiAgentSystemMetadata) GetAnnotations() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultiAgentSystemMetadata) GetAnnotationsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Annotations) {
		return map[string]interface{}{}, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *MultiAgentSystemMetadata) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]interface{} and assigns it to the Annotations field.
func (o *MultiAgentSystemMetadata) SetAnnotations(v map[string]interface{}) {
	o.Annotations = v
}

func (o MultiAgentSystemMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultiAgentSystemMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["namespace"] = o.Namespace
	if o.Uid.IsSet() {
		toSerialize["uid"] = o.Uid.Get()
	}
	if o.ResourceVersion.IsSet() {
		toSerialize["resourceVersion"] = o.ResourceVersion.Get()
	}
	if o.Generation.IsSet() {
		toSerialize["generation"] = o.Generation.Get()
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Annotations != nil {
		toSerialize["annotations"] = o.Annotations
	}
	return toSerialize, nil
}

func (o *MultiAgentSystemMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"namespace",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMultiAgentSystemMetadata := _MultiAgentSystemMetadata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMultiAgentSystemMetadata)

	if err != nil {
		return err
	}

	*o = MultiAgentSystemMetadata(varMultiAgentSystemMetadata)

	return err
}

type NullableMultiAgentSystemMetadata struct {
	value *MultiAgentSystemMetadata
	isSet bool
}

func (v NullableMultiAgentSystemMetadata) Get() *MultiAgentSystemMetadata {
	return v.value
}

func (v *NullableMultiAgentSystemMetadata) Set(val *MultiAgentSystemMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableMultiAgentSystemMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableMultiAgentSystemMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultiAgentSystemMetadata(val *MultiAgentSystemMetadata) *NullableMultiAgentSystemMetadata {
	return &NullableMultiAgentSystemMetadata{value: val, isSet: true}
}

func (v NullableMultiAgentSystemMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultiAgentSystemMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


