/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppSpec{}

// AppSpec Application specification within a MultiAgentSystem.
type AppSpec struct {
	// Name of the application
	Name string `json:"name"`
	// Type of the application
	Type AppType `json:"type"`
	// Base URL of the application
	BaseUrl string `json:"baseUrl"`
}

type _AppSpec AppSpec

// NewAppSpec instantiates a new AppSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppSpec(name string, type_ AppType, baseUrl string) *AppSpec {
	this := AppSpec{}
	this.Name = name
	this.Type = type_
	this.BaseUrl = baseUrl
	return &this
}

// NewAppSpecWithDefaults instantiates a new AppSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppSpecWithDefaults() *AppSpec {
	this := AppSpec{}
	return &this
}

// GetName returns the Name field value
func (o *AppSpec) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AppSpec) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AppSpec) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *AppSpec) GetType() AppType {
	if o == nil {
		var ret AppType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppSpec) GetTypeOk() (*AppType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppSpec) SetType(v AppType) {
	o.Type = v
}

// GetBaseUrl returns the BaseUrl field value
func (o *AppSpec) GetBaseUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseUrl
}

// GetBaseUrlOk returns a tuple with the BaseUrl field value
// and a boolean to check if the value has been set.
func (o *AppSpec) GetBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseUrl, true
}

// SetBaseUrl sets field value
func (o *AppSpec) SetBaseUrl(v string) {
	o.BaseUrl = v
}

func (o AppSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["baseUrl"] = o.BaseUrl
	return toSerialize, nil
}

func (o *AppSpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
		"baseUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppSpec := _AppSpec{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppSpec)

	if err != nil {
		return err
	}

	*o = AppSpec(varAppSpec)

	return err
}

type NullableAppSpec struct {
	value *AppSpec
	isSet bool
}

func (v NullableAppSpec) Get() *AppSpec {
	return v.value
}

func (v *NullableAppSpec) Set(val *AppSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableAppSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableAppSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppSpec(val *AppSpec) *NullableAppSpec {
	return &NullableAppSpec{value: val, isSet: true}
}

func (v NullableAppSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


