/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CASAPolicySpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CASAPolicySpec{}

// CASAPolicySpec Specification for CASAPolicy CRD.
type CASAPolicySpec struct {
	// Workload this policy applies to
	TargetRef CASAPolicyTargetRef `json:"targetRef"`
	// Protocols allowed for this workload: mcp, a2a, http
	AllowedProtocols []string `json:"allowedProtocols,omitempty"`
	// K8s services this workload may communicate with
	AllowedEndpoints []CASAPolicyAllowedEndpoint `json:"allowedEndpoints,omitempty"`
	// Allowed external LLM endpoint
	LlmEndpoint NullableCASAPolicyLlmEndpoint `json:"llmEndpoint,omitempty"`
}

type _CASAPolicySpec CASAPolicySpec

// NewCASAPolicySpec instantiates a new CASAPolicySpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCASAPolicySpec(targetRef CASAPolicyTargetRef) *CASAPolicySpec {
	this := CASAPolicySpec{}
	this.TargetRef = targetRef
	return &this
}

// NewCASAPolicySpecWithDefaults instantiates a new CASAPolicySpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCASAPolicySpecWithDefaults() *CASAPolicySpec {
	this := CASAPolicySpec{}
	return &this
}

// GetTargetRef returns the TargetRef field value
func (o *CASAPolicySpec) GetTargetRef() CASAPolicyTargetRef {
	if o == nil {
		var ret CASAPolicyTargetRef
		return ret
	}

	return o.TargetRef
}

// GetTargetRefOk returns a tuple with the TargetRef field value
// and a boolean to check if the value has been set.
func (o *CASAPolicySpec) GetTargetRefOk() (*CASAPolicyTargetRef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetRef, true
}

// SetTargetRef sets field value
func (o *CASAPolicySpec) SetTargetRef(v CASAPolicyTargetRef) {
	o.TargetRef = v
}

// GetAllowedProtocols returns the AllowedProtocols field value if set, zero value otherwise.
func (o *CASAPolicySpec) GetAllowedProtocols() []string {
	if o == nil || IsNil(o.AllowedProtocols) {
		var ret []string
		return ret
	}
	return o.AllowedProtocols
}

// GetAllowedProtocolsOk returns a tuple with the AllowedProtocols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CASAPolicySpec) GetAllowedProtocolsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedProtocols) {
		return nil, false
	}
	return o.AllowedProtocols, true
}

// HasAllowedProtocols returns a boolean if a field has been set.
func (o *CASAPolicySpec) HasAllowedProtocols() bool {
	if o != nil && !IsNil(o.AllowedProtocols) {
		return true
	}

	return false
}

// SetAllowedProtocols gets a reference to the given []string and assigns it to the AllowedProtocols field.
func (o *CASAPolicySpec) SetAllowedProtocols(v []string) {
	o.AllowedProtocols = v
}

// GetAllowedEndpoints returns the AllowedEndpoints field value if set, zero value otherwise.
func (o *CASAPolicySpec) GetAllowedEndpoints() []CASAPolicyAllowedEndpoint {
	if o == nil || IsNil(o.AllowedEndpoints) {
		var ret []CASAPolicyAllowedEndpoint
		return ret
	}
	return o.AllowedEndpoints
}

// GetAllowedEndpointsOk returns a tuple with the AllowedEndpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CASAPolicySpec) GetAllowedEndpointsOk() ([]CASAPolicyAllowedEndpoint, bool) {
	if o == nil || IsNil(o.AllowedEndpoints) {
		return nil, false
	}
	return o.AllowedEndpoints, true
}

// HasAllowedEndpoints returns a boolean if a field has been set.
func (o *CASAPolicySpec) HasAllowedEndpoints() bool {
	if o != nil && !IsNil(o.AllowedEndpoints) {
		return true
	}

	return false
}

// SetAllowedEndpoints gets a reference to the given []CASAPolicyAllowedEndpoint and assigns it to the AllowedEndpoints field.
func (o *CASAPolicySpec) SetAllowedEndpoints(v []CASAPolicyAllowedEndpoint) {
	o.AllowedEndpoints = v
}

// GetLlmEndpoint returns the LlmEndpoint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CASAPolicySpec) GetLlmEndpoint() CASAPolicyLlmEndpoint {
	if o == nil || IsNil(o.LlmEndpoint.Get()) {
		var ret CASAPolicyLlmEndpoint
		return ret
	}
	return *o.LlmEndpoint.Get()
}

// GetLlmEndpointOk returns a tuple with the LlmEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CASAPolicySpec) GetLlmEndpointOk() (*CASAPolicyLlmEndpoint, bool) {
	if o == nil {
		return nil, false
	}
	return o.LlmEndpoint.Get(), o.LlmEndpoint.IsSet()
}

// HasLlmEndpoint returns a boolean if a field has been set.
func (o *CASAPolicySpec) HasLlmEndpoint() bool {
	if o != nil && o.LlmEndpoint.IsSet() {
		return true
	}

	return false
}

// SetLlmEndpoint gets a reference to the given NullableCASAPolicyLlmEndpoint and assigns it to the LlmEndpoint field.
func (o *CASAPolicySpec) SetLlmEndpoint(v CASAPolicyLlmEndpoint) {
	o.LlmEndpoint.Set(&v)
}
// SetLlmEndpointNil sets the value for LlmEndpoint to be an explicit nil
func (o *CASAPolicySpec) SetLlmEndpointNil() {
	o.LlmEndpoint.Set(nil)
}

// UnsetLlmEndpoint ensures that no value is present for LlmEndpoint, not even an explicit nil
func (o *CASAPolicySpec) UnsetLlmEndpoint() {
	o.LlmEndpoint.Unset()
}

func (o CASAPolicySpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CASAPolicySpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["targetRef"] = o.TargetRef
	if !IsNil(o.AllowedProtocols) {
		toSerialize["allowedProtocols"] = o.AllowedProtocols
	}
	if !IsNil(o.AllowedEndpoints) {
		toSerialize["allowedEndpoints"] = o.AllowedEndpoints
	}
	if o.LlmEndpoint.IsSet() {
		toSerialize["llmEndpoint"] = o.LlmEndpoint.Get()
	}
	return toSerialize, nil
}

func (o *CASAPolicySpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"targetRef",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCASAPolicySpec := _CASAPolicySpec{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCASAPolicySpec)

	if err != nil {
		return err
	}

	*o = CASAPolicySpec(varCASAPolicySpec)

	return err
}

type NullableCASAPolicySpec struct {
	value *CASAPolicySpec
	isSet bool
}

func (v NullableCASAPolicySpec) Get() *CASAPolicySpec {
	return v.value
}

func (v *NullableCASAPolicySpec) Set(val *CASAPolicySpec) {
	v.value = val
	v.isSet = true
}

func (v NullableCASAPolicySpec) IsSet() bool {
	return v.isSet
}

func (v *NullableCASAPolicySpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCASAPolicySpec(val *CASAPolicySpec) *NullableCASAPolicySpec {
	return &NullableCASAPolicySpec{value: val, isSet: true}
}

func (v NullableCASAPolicySpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCASAPolicySpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


