/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the MultiAgentSystemStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultiAgentSystemStatus{}

// MultiAgentSystemStatus Status of MultiAgentSystem CRD.
type MultiAgentSystemStatus struct {
	// Current phase of the MAS
	Phase *MASPhase `json:"phase,omitempty"`
	// Number of apps successfully registered
	AppsReady *int32 `json:"appsReady,omitempty"`
	LastSyncTime *string `json:"last_sync_time,omitempty"`
	Message NullableString `json:"message,omitempty"`
	Credentials []AppCredentials `json:"credentials,omitempty"`
}

// NewMultiAgentSystemStatus instantiates a new MultiAgentSystemStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultiAgentSystemStatus() *MultiAgentSystemStatus {
	this := MultiAgentSystemStatus{}
	var phase MASPhase = PENDING
	this.Phase = &phase
	var appsReady int32 = 0
	this.AppsReady = &appsReady
	var lastSyncTime string = "2026-04-16T14:06:57.992400Z"
	this.LastSyncTime = &lastSyncTime
	return &this
}

// NewMultiAgentSystemStatusWithDefaults instantiates a new MultiAgentSystemStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultiAgentSystemStatusWithDefaults() *MultiAgentSystemStatus {
	this := MultiAgentSystemStatus{}
	var phase MASPhase = PENDING
	this.Phase = &phase
	var appsReady int32 = 0
	this.AppsReady = &appsReady
	var lastSyncTime string = "2026-04-16T14:06:57.992400Z"
	this.LastSyncTime = &lastSyncTime
	return &this
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *MultiAgentSystemStatus) GetPhase() MASPhase {
	if o == nil || IsNil(o.Phase) {
		var ret MASPhase
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiAgentSystemStatus) GetPhaseOk() (*MASPhase, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *MultiAgentSystemStatus) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given MASPhase and assigns it to the Phase field.
func (o *MultiAgentSystemStatus) SetPhase(v MASPhase) {
	o.Phase = &v
}

// GetAppsReady returns the AppsReady field value if set, zero value otherwise.
func (o *MultiAgentSystemStatus) GetAppsReady() int32 {
	if o == nil || IsNil(o.AppsReady) {
		var ret int32
		return ret
	}
	return *o.AppsReady
}

// GetAppsReadyOk returns a tuple with the AppsReady field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiAgentSystemStatus) GetAppsReadyOk() (*int32, bool) {
	if o == nil || IsNil(o.AppsReady) {
		return nil, false
	}
	return o.AppsReady, true
}

// HasAppsReady returns a boolean if a field has been set.
func (o *MultiAgentSystemStatus) HasAppsReady() bool {
	if o != nil && !IsNil(o.AppsReady) {
		return true
	}

	return false
}

// SetAppsReady gets a reference to the given int32 and assigns it to the AppsReady field.
func (o *MultiAgentSystemStatus) SetAppsReady(v int32) {
	o.AppsReady = &v
}

// GetLastSyncTime returns the LastSyncTime field value if set, zero value otherwise.
func (o *MultiAgentSystemStatus) GetLastSyncTime() string {
	if o == nil || IsNil(o.LastSyncTime) {
		var ret string
		return ret
	}
	return *o.LastSyncTime
}

// GetLastSyncTimeOk returns a tuple with the LastSyncTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiAgentSystemStatus) GetLastSyncTimeOk() (*string, bool) {
	if o == nil || IsNil(o.LastSyncTime) {
		return nil, false
	}
	return o.LastSyncTime, true
}

// HasLastSyncTime returns a boolean if a field has been set.
func (o *MultiAgentSystemStatus) HasLastSyncTime() bool {
	if o != nil && !IsNil(o.LastSyncTime) {
		return true
	}

	return false
}

// SetLastSyncTime gets a reference to the given string and assigns it to the LastSyncTime field.
func (o *MultiAgentSystemStatus) SetLastSyncTime(v string) {
	o.LastSyncTime = &v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultiAgentSystemStatus) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultiAgentSystemStatus) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *MultiAgentSystemStatus) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *MultiAgentSystemStatus) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *MultiAgentSystemStatus) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *MultiAgentSystemStatus) UnsetMessage() {
	o.Message.Unset()
}

// GetCredentials returns the Credentials field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultiAgentSystemStatus) GetCredentials() []AppCredentials {
	if o == nil {
		var ret []AppCredentials
		return ret
	}
	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultiAgentSystemStatus) GetCredentialsOk() ([]AppCredentials, bool) {
	if o == nil || IsNil(o.Credentials) {
		return nil, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *MultiAgentSystemStatus) HasCredentials() bool {
	if o != nil && !IsNil(o.Credentials) {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given []AppCredentials and assigns it to the Credentials field.
func (o *MultiAgentSystemStatus) SetCredentials(v []AppCredentials) {
	o.Credentials = v
}

func (o MultiAgentSystemStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultiAgentSystemStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.AppsReady) {
		toSerialize["appsReady"] = o.AppsReady
	}
	if !IsNil(o.LastSyncTime) {
		toSerialize["last_sync_time"] = o.LastSyncTime
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	if o.Credentials != nil {
		toSerialize["credentials"] = o.Credentials
	}
	return toSerialize, nil
}

type NullableMultiAgentSystemStatus struct {
	value *MultiAgentSystemStatus
	isSet bool
}

func (v NullableMultiAgentSystemStatus) Get() *MultiAgentSystemStatus {
	return v.value
}

func (v *NullableMultiAgentSystemStatus) Set(val *MultiAgentSystemStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableMultiAgentSystemStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableMultiAgentSystemStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultiAgentSystemStatus(val *MultiAgentSystemStatus) *NullableMultiAgentSystemStatus {
	return &NullableMultiAgentSystemStatus{value: val, isSet: true}
}

func (v NullableMultiAgentSystemStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultiAgentSystemStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


