/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MultiAgentSystemAppsBindingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultiAgentSystemAppsBindingRequest{}

// MultiAgentSystemAppsBindingRequest Request model for binding/unbinding a list of apps to a MAS instance.
type MultiAgentSystemAppsBindingRequest struct {
	AppIds []string `json:"app_ids"`
}

type _MultiAgentSystemAppsBindingRequest MultiAgentSystemAppsBindingRequest

// NewMultiAgentSystemAppsBindingRequest instantiates a new MultiAgentSystemAppsBindingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultiAgentSystemAppsBindingRequest(appIds []string) *MultiAgentSystemAppsBindingRequest {
	this := MultiAgentSystemAppsBindingRequest{}
	this.AppIds = appIds
	return &this
}

// NewMultiAgentSystemAppsBindingRequestWithDefaults instantiates a new MultiAgentSystemAppsBindingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultiAgentSystemAppsBindingRequestWithDefaults() *MultiAgentSystemAppsBindingRequest {
	this := MultiAgentSystemAppsBindingRequest{}
	return &this
}

// GetAppIds returns the AppIds field value
func (o *MultiAgentSystemAppsBindingRequest) GetAppIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AppIds
}

// GetAppIdsOk returns a tuple with the AppIds field value
// and a boolean to check if the value has been set.
func (o *MultiAgentSystemAppsBindingRequest) GetAppIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppIds, true
}

// SetAppIds sets field value
func (o *MultiAgentSystemAppsBindingRequest) SetAppIds(v []string) {
	o.AppIds = v
}

func (o MultiAgentSystemAppsBindingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultiAgentSystemAppsBindingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["app_ids"] = o.AppIds
	return toSerialize, nil
}

func (o *MultiAgentSystemAppsBindingRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"app_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMultiAgentSystemAppsBindingRequest := _MultiAgentSystemAppsBindingRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMultiAgentSystemAppsBindingRequest)

	if err != nil {
		return err
	}

	*o = MultiAgentSystemAppsBindingRequest(varMultiAgentSystemAppsBindingRequest)

	return err
}

type NullableMultiAgentSystemAppsBindingRequest struct {
	value *MultiAgentSystemAppsBindingRequest
	isSet bool
}

func (v NullableMultiAgentSystemAppsBindingRequest) Get() *MultiAgentSystemAppsBindingRequest {
	return v.value
}

func (v *NullableMultiAgentSystemAppsBindingRequest) Set(val *MultiAgentSystemAppsBindingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMultiAgentSystemAppsBindingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMultiAgentSystemAppsBindingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultiAgentSystemAppsBindingRequest(val *MultiAgentSystemAppsBindingRequest) *NullableMultiAgentSystemAppsBindingRequest {
	return &NullableMultiAgentSystemAppsBindingRequest{value: val, isSet: true}
}

func (v NullableMultiAgentSystemAppsBindingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultiAgentSystemAppsBindingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


