/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the K8sLlmCallMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &K8sLlmCallMapping{}

// K8sLlmCallMapping struct for K8sLlmCallMapping
type K8sLlmCallMapping struct {
	Id NullableString `json:"id,omitempty"`
	Namespace string `json:"namespace"`
	TraceId string `json:"trace_id"`
	MasId NullableString `json:"mas_id"`
	AppId NullableString `json:"app_id"`
	UserInputId NullableString `json:"user_input_id"`
	CreatedAt *string `json:"created_at,omitempty"`
}

type _K8sLlmCallMapping K8sLlmCallMapping

// NewK8sLlmCallMapping instantiates a new K8sLlmCallMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewK8sLlmCallMapping(namespace string, traceId string, masId NullableString, appId NullableString, userInputId NullableString) *K8sLlmCallMapping {
	this := K8sLlmCallMapping{}
	this.Namespace = namespace
	this.TraceId = traceId
	this.MasId = masId
	this.AppId = appId
	this.UserInputId = userInputId
	var createdAt string = "2026-04-17T16:09:56.424880Z"
	this.CreatedAt = &createdAt
	return &this
}

// NewK8sLlmCallMappingWithDefaults instantiates a new K8sLlmCallMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewK8sLlmCallMappingWithDefaults() *K8sLlmCallMapping {
	this := K8sLlmCallMapping{}
	var createdAt string = "2026-04-17T16:09:56.424880Z"
	this.CreatedAt = &createdAt
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *K8sLlmCallMapping) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *K8sLlmCallMapping) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *K8sLlmCallMapping) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *K8sLlmCallMapping) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *K8sLlmCallMapping) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *K8sLlmCallMapping) UnsetId() {
	o.Id.Unset()
}

// GetNamespace returns the Namespace field value
func (o *K8sLlmCallMapping) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *K8sLlmCallMapping) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *K8sLlmCallMapping) SetNamespace(v string) {
	o.Namespace = v
}

// GetTraceId returns the TraceId field value
func (o *K8sLlmCallMapping) GetTraceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value
// and a boolean to check if the value has been set.
func (o *K8sLlmCallMapping) GetTraceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TraceId, true
}

// SetTraceId sets field value
func (o *K8sLlmCallMapping) SetTraceId(v string) {
	o.TraceId = v
}

// GetMasId returns the MasId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *K8sLlmCallMapping) GetMasId() string {
	if o == nil || o.MasId.Get() == nil {
		var ret string
		return ret
	}

	return *o.MasId.Get()
}

// GetMasIdOk returns a tuple with the MasId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *K8sLlmCallMapping) GetMasIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MasId.Get(), o.MasId.IsSet()
}

// SetMasId sets field value
func (o *K8sLlmCallMapping) SetMasId(v string) {
	o.MasId.Set(&v)
}

// GetAppId returns the AppId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *K8sLlmCallMapping) GetAppId() string {
	if o == nil || o.AppId.Get() == nil {
		var ret string
		return ret
	}

	return *o.AppId.Get()
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *K8sLlmCallMapping) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppId.Get(), o.AppId.IsSet()
}

// SetAppId sets field value
func (o *K8sLlmCallMapping) SetAppId(v string) {
	o.AppId.Set(&v)
}

// GetUserInputId returns the UserInputId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *K8sLlmCallMapping) GetUserInputId() string {
	if o == nil || o.UserInputId.Get() == nil {
		var ret string
		return ret
	}

	return *o.UserInputId.Get()
}

// GetUserInputIdOk returns a tuple with the UserInputId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *K8sLlmCallMapping) GetUserInputIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserInputId.Get(), o.UserInputId.IsSet()
}

// SetUserInputId sets field value
func (o *K8sLlmCallMapping) SetUserInputId(v string) {
	o.UserInputId.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *K8sLlmCallMapping) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *K8sLlmCallMapping) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *K8sLlmCallMapping) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *K8sLlmCallMapping) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o K8sLlmCallMapping) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o K8sLlmCallMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	toSerialize["namespace"] = o.Namespace
	toSerialize["trace_id"] = o.TraceId
	toSerialize["mas_id"] = o.MasId.Get()
	toSerialize["app_id"] = o.AppId.Get()
	toSerialize["user_input_id"] = o.UserInputId.Get()
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

func (o *K8sLlmCallMapping) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"namespace",
		"trace_id",
		"mas_id",
		"app_id",
		"user_input_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varK8sLlmCallMapping := _K8sLlmCallMapping{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varK8sLlmCallMapping)

	if err != nil {
		return err
	}

	*o = K8sLlmCallMapping(varK8sLlmCallMapping)

	return err
}

type NullableK8sLlmCallMapping struct {
	value *K8sLlmCallMapping
	isSet bool
}

func (v NullableK8sLlmCallMapping) Get() *K8sLlmCallMapping {
	return v.value
}

func (v *NullableK8sLlmCallMapping) Set(val *K8sLlmCallMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableK8sLlmCallMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableK8sLlmCallMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableK8sLlmCallMapping(val *K8sLlmCallMapping) *NullableK8sLlmCallMapping {
	return &NullableK8sLlmCallMapping{value: val, isSet: true}
}

func (v NullableK8sLlmCallMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableK8sLlmCallMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


