/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MASListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MASListResponse{}

// MASListResponse Paginated list of Multi-Agent Systems.
type MASListResponse struct {
	Items []MASViewModel `json:"items"`
	Total int32 `json:"total"`
	Page int32 `json:"page"`
	PageSize int32 `json:"page_size"`
}

type _MASListResponse MASListResponse

// NewMASListResponse instantiates a new MASListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMASListResponse(items []MASViewModel, total int32, page int32, pageSize int32) *MASListResponse {
	this := MASListResponse{}
	this.Items = items
	this.Total = total
	this.Page = page
	this.PageSize = pageSize
	return &this
}

// NewMASListResponseWithDefaults instantiates a new MASListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMASListResponseWithDefaults() *MASListResponse {
	this := MASListResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *MASListResponse) GetItems() []MASViewModel {
	if o == nil {
		var ret []MASViewModel
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *MASListResponse) GetItemsOk() ([]MASViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *MASListResponse) SetItems(v []MASViewModel) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *MASListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *MASListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *MASListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetPage returns the Page field value
func (o *MASListResponse) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *MASListResponse) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *MASListResponse) SetPage(v int32) {
	o.Page = v
}

// GetPageSize returns the PageSize field value
func (o *MASListResponse) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *MASListResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *MASListResponse) SetPageSize(v int32) {
	o.PageSize = v
}

func (o MASListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MASListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["total"] = o.Total
	toSerialize["page"] = o.Page
	toSerialize["page_size"] = o.PageSize
	return toSerialize, nil
}

func (o *MASListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"total",
		"page",
		"page_size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMASListResponse := _MASListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMASListResponse)

	if err != nil {
		return err
	}

	*o = MASListResponse(varMASListResponse)

	return err
}

type NullableMASListResponse struct {
	value *MASListResponse
	isSet bool
}

func (v NullableMASListResponse) Get() *MASListResponse {
	return v.value
}

func (v *NullableMASListResponse) Set(val *MASListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMASListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMASListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMASListResponse(val *MASListResponse) *NullableMASListResponse {
	return &NullableMASListResponse{value: val, isSet: true}
}

func (v NullableMASListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMASListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


