/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ScopeCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScopeCreateRequest{}

// ScopeCreateRequest Request model for scope creation.
type ScopeCreateRequest struct {
	Name string `json:"name"`
	MasId string `json:"mas_id"`
}

type _ScopeCreateRequest ScopeCreateRequest

// NewScopeCreateRequest instantiates a new ScopeCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScopeCreateRequest(name string, masId string) *ScopeCreateRequest {
	this := ScopeCreateRequest{}
	this.Name = name
	this.MasId = masId
	return &this
}

// NewScopeCreateRequestWithDefaults instantiates a new ScopeCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScopeCreateRequestWithDefaults() *ScopeCreateRequest {
	this := ScopeCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ScopeCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ScopeCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ScopeCreateRequest) SetName(v string) {
	o.Name = v
}

// GetMasId returns the MasId field value
func (o *ScopeCreateRequest) GetMasId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MasId
}

// GetMasIdOk returns a tuple with the MasId field value
// and a boolean to check if the value has been set.
func (o *ScopeCreateRequest) GetMasIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MasId, true
}

// SetMasId sets field value
func (o *ScopeCreateRequest) SetMasId(v string) {
	o.MasId = v
}

func (o ScopeCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScopeCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["mas_id"] = o.MasId
	return toSerialize, nil
}

func (o *ScopeCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"mas_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScopeCreateRequest := _ScopeCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScopeCreateRequest)

	if err != nil {
		return err
	}

	*o = ScopeCreateRequest(varScopeCreateRequest)

	return err
}

type NullableScopeCreateRequest struct {
	value *ScopeCreateRequest
	isSet bool
}

func (v NullableScopeCreateRequest) Get() *ScopeCreateRequest {
	return v.value
}

func (v *NullableScopeCreateRequest) Set(val *ScopeCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableScopeCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableScopeCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScopeCreateRequest(val *ScopeCreateRequest) *NullableScopeCreateRequest {
	return &NullableScopeCreateRequest{value: val, isSet: true}
}

func (v NullableScopeCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScopeCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


