/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppCredentials{}

// AppCredentials OAuth2 credentials for an application.
type AppCredentials struct {
	// Name of the application
	AppName string `json:"appName"`
	// Application UUID
	AppId string `json:"appId"`
	// OAuth2 client ID
	ClientId string `json:"clientId"`
	// OAuth2 client secret
	ClientSecret string `json:"clientSecret"`
	// Name of the K8s secret to create
	SecretName string `json:"secretName"`
}

type _AppCredentials AppCredentials

// NewAppCredentials instantiates a new AppCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppCredentials(appName string, appId string, clientId string, clientSecret string, secretName string) *AppCredentials {
	this := AppCredentials{}
	this.AppName = appName
	this.AppId = appId
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	this.SecretName = secretName
	return &this
}

// NewAppCredentialsWithDefaults instantiates a new AppCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppCredentialsWithDefaults() *AppCredentials {
	this := AppCredentials{}
	return &this
}

// GetAppName returns the AppName field value
func (o *AppCredentials) GetAppName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppName
}

// GetAppNameOk returns a tuple with the AppName field value
// and a boolean to check if the value has been set.
func (o *AppCredentials) GetAppNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppName, true
}

// SetAppName sets field value
func (o *AppCredentials) SetAppName(v string) {
	o.AppName = v
}

// GetAppId returns the AppId field value
func (o *AppCredentials) GetAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *AppCredentials) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *AppCredentials) SetAppId(v string) {
	o.AppId = v
}

// GetClientId returns the ClientId field value
func (o *AppCredentials) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *AppCredentials) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *AppCredentials) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *AppCredentials) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *AppCredentials) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *AppCredentials) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetSecretName returns the SecretName field value
func (o *AppCredentials) GetSecretName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretName
}

// GetSecretNameOk returns a tuple with the SecretName field value
// and a boolean to check if the value has been set.
func (o *AppCredentials) GetSecretNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretName, true
}

// SetSecretName sets field value
func (o *AppCredentials) SetSecretName(v string) {
	o.SecretName = v
}

func (o AppCredentials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["appName"] = o.AppName
	toSerialize["appId"] = o.AppId
	toSerialize["clientId"] = o.ClientId
	toSerialize["clientSecret"] = o.ClientSecret
	toSerialize["secretName"] = o.SecretName
	return toSerialize, nil
}

func (o *AppCredentials) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"appName",
		"appId",
		"clientId",
		"clientSecret",
		"secretName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppCredentials := _AppCredentials{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppCredentials)

	if err != nil {
		return err
	}

	*o = AppCredentials(varAppCredentials)

	return err
}

type NullableAppCredentials struct {
	value *AppCredentials
	isSet bool
}

func (v NullableAppCredentials) Get() *AppCredentials {
	return v.value
}

func (v *NullableAppCredentials) Set(val *AppCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableAppCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableAppCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppCredentials(val *AppCredentials) *NullableAppCredentials {
	return &NullableAppCredentials{value: val, isSet: true}
}

func (v NullableAppCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


