/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MultiAgentSystemCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultiAgentSystemCreateRequest{}

// MultiAgentSystemCreateRequest Request model for MAS creation.
type MultiAgentSystemCreateRequest struct {
	Name string `json:"name"`
	EnabledToolChecks NullableToolCheckFlags `json:"enabled_tool_checks,omitempty"`
	Namespace NullableString `json:"namespace,omitempty"`
}

type _MultiAgentSystemCreateRequest MultiAgentSystemCreateRequest

// NewMultiAgentSystemCreateRequest instantiates a new MultiAgentSystemCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultiAgentSystemCreateRequest(name string) *MultiAgentSystemCreateRequest {
	this := MultiAgentSystemCreateRequest{}
	this.Name = name
	return &this
}

// NewMultiAgentSystemCreateRequestWithDefaults instantiates a new MultiAgentSystemCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultiAgentSystemCreateRequestWithDefaults() *MultiAgentSystemCreateRequest {
	this := MultiAgentSystemCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *MultiAgentSystemCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MultiAgentSystemCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MultiAgentSystemCreateRequest) SetName(v string) {
	o.Name = v
}

// GetEnabledToolChecks returns the EnabledToolChecks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultiAgentSystemCreateRequest) GetEnabledToolChecks() ToolCheckFlags {
	if o == nil || IsNil(o.EnabledToolChecks.Get()) {
		var ret ToolCheckFlags
		return ret
	}
	return *o.EnabledToolChecks.Get()
}

// GetEnabledToolChecksOk returns a tuple with the EnabledToolChecks field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultiAgentSystemCreateRequest) GetEnabledToolChecksOk() (*ToolCheckFlags, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnabledToolChecks.Get(), o.EnabledToolChecks.IsSet()
}

// HasEnabledToolChecks returns a boolean if a field has been set.
func (o *MultiAgentSystemCreateRequest) HasEnabledToolChecks() bool {
	if o != nil && o.EnabledToolChecks.IsSet() {
		return true
	}

	return false
}

// SetEnabledToolChecks gets a reference to the given NullableToolCheckFlags and assigns it to the EnabledToolChecks field.
func (o *MultiAgentSystemCreateRequest) SetEnabledToolChecks(v ToolCheckFlags) {
	o.EnabledToolChecks.Set(&v)
}
// SetEnabledToolChecksNil sets the value for EnabledToolChecks to be an explicit nil
func (o *MultiAgentSystemCreateRequest) SetEnabledToolChecksNil() {
	o.EnabledToolChecks.Set(nil)
}

// UnsetEnabledToolChecks ensures that no value is present for EnabledToolChecks, not even an explicit nil
func (o *MultiAgentSystemCreateRequest) UnsetEnabledToolChecks() {
	o.EnabledToolChecks.Unset()
}

// GetNamespace returns the Namespace field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultiAgentSystemCreateRequest) GetNamespace() string {
	if o == nil || IsNil(o.Namespace.Get()) {
		var ret string
		return ret
	}
	return *o.Namespace.Get()
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultiAgentSystemCreateRequest) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Namespace.Get(), o.Namespace.IsSet()
}

// HasNamespace returns a boolean if a field has been set.
func (o *MultiAgentSystemCreateRequest) HasNamespace() bool {
	if o != nil && o.Namespace.IsSet() {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given NullableString and assigns it to the Namespace field.
func (o *MultiAgentSystemCreateRequest) SetNamespace(v string) {
	o.Namespace.Set(&v)
}
// SetNamespaceNil sets the value for Namespace to be an explicit nil
func (o *MultiAgentSystemCreateRequest) SetNamespaceNil() {
	o.Namespace.Set(nil)
}

// UnsetNamespace ensures that no value is present for Namespace, not even an explicit nil
func (o *MultiAgentSystemCreateRequest) UnsetNamespace() {
	o.Namespace.Unset()
}

func (o MultiAgentSystemCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultiAgentSystemCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.EnabledToolChecks.IsSet() {
		toSerialize["enabled_tool_checks"] = o.EnabledToolChecks.Get()
	}
	if o.Namespace.IsSet() {
		toSerialize["namespace"] = o.Namespace.Get()
	}
	return toSerialize, nil
}

func (o *MultiAgentSystemCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMultiAgentSystemCreateRequest := _MultiAgentSystemCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMultiAgentSystemCreateRequest)

	if err != nil {
		return err
	}

	*o = MultiAgentSystemCreateRequest(varMultiAgentSystemCreateRequest)

	return err
}

type NullableMultiAgentSystemCreateRequest struct {
	value *MultiAgentSystemCreateRequest
	isSet bool
}

func (v NullableMultiAgentSystemCreateRequest) Get() *MultiAgentSystemCreateRequest {
	return v.value
}

func (v *NullableMultiAgentSystemCreateRequest) Set(val *MultiAgentSystemCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMultiAgentSystemCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMultiAgentSystemCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultiAgentSystemCreateRequest(val *MultiAgentSystemCreateRequest) *NullableMultiAgentSystemCreateRequest {
	return &NullableMultiAgentSystemCreateRequest{value: val, isSet: true}
}

func (v NullableMultiAgentSystemCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultiAgentSystemCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


