/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MASStatusUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MASStatusUpdateRequest{}

// MASStatusUpdateRequest Request model for updating MAS status (used by operator).
type MASStatusUpdateRequest struct {
	Status MultiAgentSystemStatus `json:"status"`
}

type _MASStatusUpdateRequest MASStatusUpdateRequest

// NewMASStatusUpdateRequest instantiates a new MASStatusUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMASStatusUpdateRequest(status MultiAgentSystemStatus) *MASStatusUpdateRequest {
	this := MASStatusUpdateRequest{}
	this.Status = status
	return &this
}

// NewMASStatusUpdateRequestWithDefaults instantiates a new MASStatusUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMASStatusUpdateRequestWithDefaults() *MASStatusUpdateRequest {
	this := MASStatusUpdateRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *MASStatusUpdateRequest) GetStatus() MultiAgentSystemStatus {
	if o == nil {
		var ret MultiAgentSystemStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MASStatusUpdateRequest) GetStatusOk() (*MultiAgentSystemStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MASStatusUpdateRequest) SetStatus(v MultiAgentSystemStatus) {
	o.Status = v
}

func (o MASStatusUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MASStatusUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *MASStatusUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMASStatusUpdateRequest := _MASStatusUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMASStatusUpdateRequest)

	if err != nil {
		return err
	}

	*o = MASStatusUpdateRequest(varMASStatusUpdateRequest)

	return err
}

type NullableMASStatusUpdateRequest struct {
	value *MASStatusUpdateRequest
	isSet bool
}

func (v NullableMASStatusUpdateRequest) Get() *MASStatusUpdateRequest {
	return v.value
}

func (v *NullableMASStatusUpdateRequest) Set(val *MASStatusUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMASStatusUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMASStatusUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMASStatusUpdateRequest(val *MASStatusUpdateRequest) *NullableMASStatusUpdateRequest {
	return &NullableMASStatusUpdateRequest{value: val, isSet: true}
}

func (v NullableMASStatusUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMASStatusUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


