/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// MASPhase Phase of MAS resource lifecycle.
type MASPhase string

// List of MASPhase
const (
	PENDING MASPhase = "Pending"
	ACTIVE MASPhase = "Active"
	FAILED MASPhase = "Failed"
)

// All allowed values of MASPhase enum
var AllowedMASPhaseEnumValues = []MASPhase{
	"Pending",
	"Active",
	"Failed",
}

func (v *MASPhase) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MASPhase(value)
	for _, existing := range AllowedMASPhaseEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MASPhase", value)
}

// NewMASPhaseFromValue returns a pointer to a valid MASPhase
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMASPhaseFromValue(v string) (*MASPhase, error) {
	ev := MASPhase(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MASPhase: valid values are %v", v, AllowedMASPhaseEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MASPhase) IsValid() bool {
	for _, existing := range AllowedMASPhaseEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MASPhase value
func (v MASPhase) Ptr() *MASPhase {
	return &v
}

type NullableMASPhase struct {
	value *MASPhase
	isSet bool
}

func (v NullableMASPhase) Get() *MASPhase {
	return v.value
}

func (v *NullableMASPhase) Set(val *MASPhase) {
	v.value = val
	v.isSet = true
}

func (v NullableMASPhase) IsSet() bool {
	return v.isSet
}

func (v *NullableMASPhase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMASPhase(val *MASPhase) *NullableMASPhase {
	return &NullableMASPhase{value: val, isSet: true}
}

func (v NullableMASPhase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMASPhase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

