/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MASListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MASListResponse{}

// MASListResponse Response model for listing MultiAgentSystems.
type MASListResponse struct {
	ApiVersion *string `json:"apiVersion,omitempty"`
	Kind *string `json:"kind,omitempty"`
	Items []MultiAgentSystemCRD `json:"items"`
}

type _MASListResponse MASListResponse

// NewMASListResponse instantiates a new MASListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMASListResponse(items []MultiAgentSystemCRD) *MASListResponse {
	this := MASListResponse{}
	var apiVersion string = "zta.io/v1alpha1"
	this.ApiVersion = &apiVersion
	var kind string = "MultiAgentSystemList"
	this.Kind = &kind
	this.Items = items
	return &this
}

// NewMASListResponseWithDefaults instantiates a new MASListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMASListResponseWithDefaults() *MASListResponse {
	this := MASListResponse{}
	var apiVersion string = "zta.io/v1alpha1"
	this.ApiVersion = &apiVersion
	var kind string = "MultiAgentSystemList"
	this.Kind = &kind
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *MASListResponse) GetApiVersion() string {
	if o == nil || IsNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MASListResponse) GetApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *MASListResponse) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *MASListResponse) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *MASListResponse) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MASListResponse) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *MASListResponse) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *MASListResponse) SetKind(v string) {
	o.Kind = &v
}

// GetItems returns the Items field value
func (o *MASListResponse) GetItems() []MultiAgentSystemCRD {
	if o == nil {
		var ret []MultiAgentSystemCRD
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *MASListResponse) GetItemsOk() ([]MultiAgentSystemCRD, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *MASListResponse) SetItems(v []MultiAgentSystemCRD) {
	o.Items = v
}

func (o MASListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MASListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiVersion) {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *MASListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMASListResponse := _MASListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMASListResponse)

	if err != nil {
		return err
	}

	*o = MASListResponse(varMASListResponse)

	return err
}

type NullableMASListResponse struct {
	value *MASListResponse
	isSet bool
}

func (v NullableMASListResponse) Get() *MASListResponse {
	return v.value
}

func (v *NullableMASListResponse) Set(val *MASListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMASListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMASListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMASListResponse(val *MASListResponse) *NullableMASListResponse {
	return &NullableMASListResponse{value: val, isSet: true}
}

func (v NullableMASListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMASListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


