/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LLMCallEndedKubernetesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMCallEndedKubernetesRequest{}

// LLMCallEndedKubernetesRequest Request body for recording the end of an LLM call.
type LLMCallEndedKubernetesRequest struct {
	CallId string `json:"call_id"`
	Response string `json:"response"`
}

type _LLMCallEndedKubernetesRequest LLMCallEndedKubernetesRequest

// NewLLMCallEndedKubernetesRequest instantiates a new LLMCallEndedKubernetesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMCallEndedKubernetesRequest(callId string, response string) *LLMCallEndedKubernetesRequest {
	this := LLMCallEndedKubernetesRequest{}
	this.CallId = callId
	this.Response = response
	return &this
}

// NewLLMCallEndedKubernetesRequestWithDefaults instantiates a new LLMCallEndedKubernetesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMCallEndedKubernetesRequestWithDefaults() *LLMCallEndedKubernetesRequest {
	this := LLMCallEndedKubernetesRequest{}
	return &this
}

// GetCallId returns the CallId field value
func (o *LLMCallEndedKubernetesRequest) GetCallId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CallId
}

// GetCallIdOk returns a tuple with the CallId field value
// and a boolean to check if the value has been set.
func (o *LLMCallEndedKubernetesRequest) GetCallIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallId, true
}

// SetCallId sets field value
func (o *LLMCallEndedKubernetesRequest) SetCallId(v string) {
	o.CallId = v
}

// GetResponse returns the Response field value
func (o *LLMCallEndedKubernetesRequest) GetResponse() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Response
}

// GetResponseOk returns a tuple with the Response field value
// and a boolean to check if the value has been set.
func (o *LLMCallEndedKubernetesRequest) GetResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Response, true
}

// SetResponse sets field value
func (o *LLMCallEndedKubernetesRequest) SetResponse(v string) {
	o.Response = v
}

func (o LLMCallEndedKubernetesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMCallEndedKubernetesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["call_id"] = o.CallId
	toSerialize["response"] = o.Response
	return toSerialize, nil
}

func (o *LLMCallEndedKubernetesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"call_id",
		"response",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLLMCallEndedKubernetesRequest := _LLMCallEndedKubernetesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLLMCallEndedKubernetesRequest)

	if err != nil {
		return err
	}

	*o = LLMCallEndedKubernetesRequest(varLLMCallEndedKubernetesRequest)

	return err
}

type NullableLLMCallEndedKubernetesRequest struct {
	value *LLMCallEndedKubernetesRequest
	isSet bool
}

func (v NullableLLMCallEndedKubernetesRequest) Get() *LLMCallEndedKubernetesRequest {
	return v.value
}

func (v *NullableLLMCallEndedKubernetesRequest) Set(val *LLMCallEndedKubernetesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMCallEndedKubernetesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMCallEndedKubernetesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMCallEndedKubernetesRequest(val *LLMCallEndedKubernetesRequest) *NullableLLMCallEndedKubernetesRequest {
	return &NullableLLMCallEndedKubernetesRequest{value: val, isSet: true}
}

func (v NullableLLMCallEndedKubernetesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMCallEndedKubernetesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


