/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MultiAgentSystemUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultiAgentSystemUpdateRequest{}

// MultiAgentSystemUpdateRequest Request model for updating an existing MAS instance.
type MultiAgentSystemUpdateRequest struct {
	Name string `json:"name"`
	EnabledToolChecks NullableToolCheckFlags `json:"enabled_tool_checks,omitempty"`
}

type _MultiAgentSystemUpdateRequest MultiAgentSystemUpdateRequest

// NewMultiAgentSystemUpdateRequest instantiates a new MultiAgentSystemUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultiAgentSystemUpdateRequest(name string) *MultiAgentSystemUpdateRequest {
	this := MultiAgentSystemUpdateRequest{}
	this.Name = name
	return &this
}

// NewMultiAgentSystemUpdateRequestWithDefaults instantiates a new MultiAgentSystemUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultiAgentSystemUpdateRequestWithDefaults() *MultiAgentSystemUpdateRequest {
	this := MultiAgentSystemUpdateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *MultiAgentSystemUpdateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MultiAgentSystemUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MultiAgentSystemUpdateRequest) SetName(v string) {
	o.Name = v
}

// GetEnabledToolChecks returns the EnabledToolChecks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultiAgentSystemUpdateRequest) GetEnabledToolChecks() ToolCheckFlags {
	if o == nil || IsNil(o.EnabledToolChecks.Get()) {
		var ret ToolCheckFlags
		return ret
	}
	return *o.EnabledToolChecks.Get()
}

// GetEnabledToolChecksOk returns a tuple with the EnabledToolChecks field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultiAgentSystemUpdateRequest) GetEnabledToolChecksOk() (*ToolCheckFlags, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnabledToolChecks.Get(), o.EnabledToolChecks.IsSet()
}

// HasEnabledToolChecks returns a boolean if a field has been set.
func (o *MultiAgentSystemUpdateRequest) HasEnabledToolChecks() bool {
	if o != nil && o.EnabledToolChecks.IsSet() {
		return true
	}

	return false
}

// SetEnabledToolChecks gets a reference to the given NullableToolCheckFlags and assigns it to the EnabledToolChecks field.
func (o *MultiAgentSystemUpdateRequest) SetEnabledToolChecks(v ToolCheckFlags) {
	o.EnabledToolChecks.Set(&v)
}
// SetEnabledToolChecksNil sets the value for EnabledToolChecks to be an explicit nil
func (o *MultiAgentSystemUpdateRequest) SetEnabledToolChecksNil() {
	o.EnabledToolChecks.Set(nil)
}

// UnsetEnabledToolChecks ensures that no value is present for EnabledToolChecks, not even an explicit nil
func (o *MultiAgentSystemUpdateRequest) UnsetEnabledToolChecks() {
	o.EnabledToolChecks.Unset()
}

func (o MultiAgentSystemUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultiAgentSystemUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.EnabledToolChecks.IsSet() {
		toSerialize["enabled_tool_checks"] = o.EnabledToolChecks.Get()
	}
	return toSerialize, nil
}

func (o *MultiAgentSystemUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMultiAgentSystemUpdateRequest := _MultiAgentSystemUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMultiAgentSystemUpdateRequest)

	if err != nil {
		return err
	}

	*o = MultiAgentSystemUpdateRequest(varMultiAgentSystemUpdateRequest)

	return err
}

type NullableMultiAgentSystemUpdateRequest struct {
	value *MultiAgentSystemUpdateRequest
	isSet bool
}

func (v NullableMultiAgentSystemUpdateRequest) Get() *MultiAgentSystemUpdateRequest {
	return v.value
}

func (v *NullableMultiAgentSystemUpdateRequest) Set(val *MultiAgentSystemUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMultiAgentSystemUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMultiAgentSystemUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultiAgentSystemUpdateRequest(val *MultiAgentSystemUpdateRequest) *NullableMultiAgentSystemUpdateRequest {
	return &NullableMultiAgentSystemUpdateRequest{value: val, isSet: true}
}

func (v NullableMultiAgentSystemUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultiAgentSystemUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


