/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LLMCallStartedEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMCallStartedEvent{}

// LLMCallStartedEvent Event emitted when an LLM call begins (recorded by the agent).
type LLMCallStartedEvent struct {
	Id *string `json:"id,omitempty"`
	UserInputId string `json:"user_input_id"`
	CreatedAt *string `json:"created_at,omitempty"`
	CallId string `json:"call_id"`
	Token string `json:"token"`
	AppId string `json:"app_id"`
	MasId NullableString `json:"mas_id,omitempty"`
	Prompt string `json:"prompt"`
	Tools NullableString `json:"tools"`
}

type _LLMCallStartedEvent LLMCallStartedEvent

// NewLLMCallStartedEvent instantiates a new LLMCallStartedEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMCallStartedEvent(userInputId string, callId string, token string, appId string, prompt string, tools NullableString) *LLMCallStartedEvent {
	this := LLMCallStartedEvent{}
	this.UserInputId = userInputId
	this.CallId = callId
	this.Token = token
	this.AppId = appId
	this.Prompt = prompt
	this.Tools = tools
	return &this
}

// NewLLMCallStartedEventWithDefaults instantiates a new LLMCallStartedEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMCallStartedEventWithDefaults() *LLMCallStartedEvent {
	this := LLMCallStartedEvent{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LLMCallStartedEvent) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMCallStartedEvent) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LLMCallStartedEvent) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LLMCallStartedEvent) SetId(v string) {
	o.Id = &v
}

// GetUserInputId returns the UserInputId field value
func (o *LLMCallStartedEvent) GetUserInputId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserInputId
}

// GetUserInputIdOk returns a tuple with the UserInputId field value
// and a boolean to check if the value has been set.
func (o *LLMCallStartedEvent) GetUserInputIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserInputId, true
}

// SetUserInputId sets field value
func (o *LLMCallStartedEvent) SetUserInputId(v string) {
	o.UserInputId = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *LLMCallStartedEvent) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMCallStartedEvent) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *LLMCallStartedEvent) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *LLMCallStartedEvent) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCallId returns the CallId field value
func (o *LLMCallStartedEvent) GetCallId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CallId
}

// GetCallIdOk returns a tuple with the CallId field value
// and a boolean to check if the value has been set.
func (o *LLMCallStartedEvent) GetCallIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallId, true
}

// SetCallId sets field value
func (o *LLMCallStartedEvent) SetCallId(v string) {
	o.CallId = v
}

// GetToken returns the Token field value
func (o *LLMCallStartedEvent) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *LLMCallStartedEvent) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *LLMCallStartedEvent) SetToken(v string) {
	o.Token = v
}

// GetAppId returns the AppId field value
func (o *LLMCallStartedEvent) GetAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *LLMCallStartedEvent) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *LLMCallStartedEvent) SetAppId(v string) {
	o.AppId = v
}

// GetMasId returns the MasId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMCallStartedEvent) GetMasId() string {
	if o == nil || IsNil(o.MasId.Get()) {
		var ret string
		return ret
	}
	return *o.MasId.Get()
}

// GetMasIdOk returns a tuple with the MasId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMCallStartedEvent) GetMasIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MasId.Get(), o.MasId.IsSet()
}

// HasMasId returns a boolean if a field has been set.
func (o *LLMCallStartedEvent) HasMasId() bool {
	if o != nil && o.MasId.IsSet() {
		return true
	}

	return false
}

// SetMasId gets a reference to the given NullableString and assigns it to the MasId field.
func (o *LLMCallStartedEvent) SetMasId(v string) {
	o.MasId.Set(&v)
}
// SetMasIdNil sets the value for MasId to be an explicit nil
func (o *LLMCallStartedEvent) SetMasIdNil() {
	o.MasId.Set(nil)
}

// UnsetMasId ensures that no value is present for MasId, not even an explicit nil
func (o *LLMCallStartedEvent) UnsetMasId() {
	o.MasId.Unset()
}

// GetPrompt returns the Prompt field value
func (o *LLMCallStartedEvent) GetPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value
// and a boolean to check if the value has been set.
func (o *LLMCallStartedEvent) GetPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prompt, true
}

// SetPrompt sets field value
func (o *LLMCallStartedEvent) SetPrompt(v string) {
	o.Prompt = v
}

// GetTools returns the Tools field value
// If the value is explicit nil, the zero value for string will be returned
func (o *LLMCallStartedEvent) GetTools() string {
	if o == nil || o.Tools.Get() == nil {
		var ret string
		return ret
	}

	return *o.Tools.Get()
}

// GetToolsOk returns a tuple with the Tools field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMCallStartedEvent) GetToolsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tools.Get(), o.Tools.IsSet()
}

// SetTools sets field value
func (o *LLMCallStartedEvent) SetTools(v string) {
	o.Tools.Set(&v)
}

func (o LLMCallStartedEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMCallStartedEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["user_input_id"] = o.UserInputId
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	toSerialize["call_id"] = o.CallId
	toSerialize["token"] = o.Token
	toSerialize["app_id"] = o.AppId
	if o.MasId.IsSet() {
		toSerialize["mas_id"] = o.MasId.Get()
	}
	toSerialize["prompt"] = o.Prompt
	toSerialize["tools"] = o.Tools.Get()
	return toSerialize, nil
}

func (o *LLMCallStartedEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_input_id",
		"call_id",
		"token",
		"app_id",
		"prompt",
		"tools",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLLMCallStartedEvent := _LLMCallStartedEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLLMCallStartedEvent)

	if err != nil {
		return err
	}

	*o = LLMCallStartedEvent(varLLMCallStartedEvent)

	return err
}

type NullableLLMCallStartedEvent struct {
	value *LLMCallStartedEvent
	isSet bool
}

func (v NullableLLMCallStartedEvent) Get() *LLMCallStartedEvent {
	return v.value
}

func (v *NullableLLMCallStartedEvent) Set(val *LLMCallStartedEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMCallStartedEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMCallStartedEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMCallStartedEvent(val *LLMCallStartedEvent) *NullableLLMCallStartedEvent {
	return &NullableLLMCallStartedEvent{value: val, isSet: true}
}

func (v NullableLLMCallStartedEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMCallStartedEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


