/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the K8sAppSpecViewModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &K8sAppSpecViewModel{}

// K8sAppSpecViewModel View model for application specification data.
type K8sAppSpecViewModel struct {
	Id NullableString `json:"id,omitempty"`
	Name string `json:"name"`
	Type AppType `json:"type"`
	UrlHost string `json:"url_host"`
	UrlScheme string `json:"url_scheme"`
	PromptFieldJsonPath NullableString `json:"prompt_field_json_path,omitempty"`
	KubernetesWorkloadName NullableString `json:"kubernetes_workload_name,omitempty"`
	MasCrdId NullableString `json:"mas_crd_id,omitempty"`
	AppId NullableString `json:"app_id,omitempty"`
}

type _K8sAppSpecViewModel K8sAppSpecViewModel

// NewK8sAppSpecViewModel instantiates a new K8sAppSpecViewModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewK8sAppSpecViewModel(name string, type_ AppType, urlHost string, urlScheme string) *K8sAppSpecViewModel {
	this := K8sAppSpecViewModel{}
	this.Name = name
	this.Type = type_
	this.UrlHost = urlHost
	this.UrlScheme = urlScheme
	return &this
}

// NewK8sAppSpecViewModelWithDefaults instantiates a new K8sAppSpecViewModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewK8sAppSpecViewModelWithDefaults() *K8sAppSpecViewModel {
	this := K8sAppSpecViewModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *K8sAppSpecViewModel) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *K8sAppSpecViewModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *K8sAppSpecViewModel) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *K8sAppSpecViewModel) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *K8sAppSpecViewModel) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *K8sAppSpecViewModel) UnsetId() {
	o.Id.Unset()
}

// GetName returns the Name field value
func (o *K8sAppSpecViewModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *K8sAppSpecViewModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *K8sAppSpecViewModel) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *K8sAppSpecViewModel) GetType() AppType {
	if o == nil {
		var ret AppType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *K8sAppSpecViewModel) GetTypeOk() (*AppType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *K8sAppSpecViewModel) SetType(v AppType) {
	o.Type = v
}

// GetUrlHost returns the UrlHost field value
func (o *K8sAppSpecViewModel) GetUrlHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlHost
}

// GetUrlHostOk returns a tuple with the UrlHost field value
// and a boolean to check if the value has been set.
func (o *K8sAppSpecViewModel) GetUrlHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlHost, true
}

// SetUrlHost sets field value
func (o *K8sAppSpecViewModel) SetUrlHost(v string) {
	o.UrlHost = v
}

// GetUrlScheme returns the UrlScheme field value
func (o *K8sAppSpecViewModel) GetUrlScheme() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlScheme
}

// GetUrlSchemeOk returns a tuple with the UrlScheme field value
// and a boolean to check if the value has been set.
func (o *K8sAppSpecViewModel) GetUrlSchemeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlScheme, true
}

// SetUrlScheme sets field value
func (o *K8sAppSpecViewModel) SetUrlScheme(v string) {
	o.UrlScheme = v
}

// GetPromptFieldJsonPath returns the PromptFieldJsonPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *K8sAppSpecViewModel) GetPromptFieldJsonPath() string {
	if o == nil || IsNil(o.PromptFieldJsonPath.Get()) {
		var ret string
		return ret
	}
	return *o.PromptFieldJsonPath.Get()
}

// GetPromptFieldJsonPathOk returns a tuple with the PromptFieldJsonPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *K8sAppSpecViewModel) GetPromptFieldJsonPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromptFieldJsonPath.Get(), o.PromptFieldJsonPath.IsSet()
}

// HasPromptFieldJsonPath returns a boolean if a field has been set.
func (o *K8sAppSpecViewModel) HasPromptFieldJsonPath() bool {
	if o != nil && o.PromptFieldJsonPath.IsSet() {
		return true
	}

	return false
}

// SetPromptFieldJsonPath gets a reference to the given NullableString and assigns it to the PromptFieldJsonPath field.
func (o *K8sAppSpecViewModel) SetPromptFieldJsonPath(v string) {
	o.PromptFieldJsonPath.Set(&v)
}
// SetPromptFieldJsonPathNil sets the value for PromptFieldJsonPath to be an explicit nil
func (o *K8sAppSpecViewModel) SetPromptFieldJsonPathNil() {
	o.PromptFieldJsonPath.Set(nil)
}

// UnsetPromptFieldJsonPath ensures that no value is present for PromptFieldJsonPath, not even an explicit nil
func (o *K8sAppSpecViewModel) UnsetPromptFieldJsonPath() {
	o.PromptFieldJsonPath.Unset()
}

// GetKubernetesWorkloadName returns the KubernetesWorkloadName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *K8sAppSpecViewModel) GetKubernetesWorkloadName() string {
	if o == nil || IsNil(o.KubernetesWorkloadName.Get()) {
		var ret string
		return ret
	}
	return *o.KubernetesWorkloadName.Get()
}

// GetKubernetesWorkloadNameOk returns a tuple with the KubernetesWorkloadName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *K8sAppSpecViewModel) GetKubernetesWorkloadNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.KubernetesWorkloadName.Get(), o.KubernetesWorkloadName.IsSet()
}

// HasKubernetesWorkloadName returns a boolean if a field has been set.
func (o *K8sAppSpecViewModel) HasKubernetesWorkloadName() bool {
	if o != nil && o.KubernetesWorkloadName.IsSet() {
		return true
	}

	return false
}

// SetKubernetesWorkloadName gets a reference to the given NullableString and assigns it to the KubernetesWorkloadName field.
func (o *K8sAppSpecViewModel) SetKubernetesWorkloadName(v string) {
	o.KubernetesWorkloadName.Set(&v)
}
// SetKubernetesWorkloadNameNil sets the value for KubernetesWorkloadName to be an explicit nil
func (o *K8sAppSpecViewModel) SetKubernetesWorkloadNameNil() {
	o.KubernetesWorkloadName.Set(nil)
}

// UnsetKubernetesWorkloadName ensures that no value is present for KubernetesWorkloadName, not even an explicit nil
func (o *K8sAppSpecViewModel) UnsetKubernetesWorkloadName() {
	o.KubernetesWorkloadName.Unset()
}

// GetMasCrdId returns the MasCrdId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *K8sAppSpecViewModel) GetMasCrdId() string {
	if o == nil || IsNil(o.MasCrdId.Get()) {
		var ret string
		return ret
	}
	return *o.MasCrdId.Get()
}

// GetMasCrdIdOk returns a tuple with the MasCrdId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *K8sAppSpecViewModel) GetMasCrdIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MasCrdId.Get(), o.MasCrdId.IsSet()
}

// HasMasCrdId returns a boolean if a field has been set.
func (o *K8sAppSpecViewModel) HasMasCrdId() bool {
	if o != nil && o.MasCrdId.IsSet() {
		return true
	}

	return false
}

// SetMasCrdId gets a reference to the given NullableString and assigns it to the MasCrdId field.
func (o *K8sAppSpecViewModel) SetMasCrdId(v string) {
	o.MasCrdId.Set(&v)
}
// SetMasCrdIdNil sets the value for MasCrdId to be an explicit nil
func (o *K8sAppSpecViewModel) SetMasCrdIdNil() {
	o.MasCrdId.Set(nil)
}

// UnsetMasCrdId ensures that no value is present for MasCrdId, not even an explicit nil
func (o *K8sAppSpecViewModel) UnsetMasCrdId() {
	o.MasCrdId.Unset()
}

// GetAppId returns the AppId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *K8sAppSpecViewModel) GetAppId() string {
	if o == nil || IsNil(o.AppId.Get()) {
		var ret string
		return ret
	}
	return *o.AppId.Get()
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *K8sAppSpecViewModel) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppId.Get(), o.AppId.IsSet()
}

// HasAppId returns a boolean if a field has been set.
func (o *K8sAppSpecViewModel) HasAppId() bool {
	if o != nil && o.AppId.IsSet() {
		return true
	}

	return false
}

// SetAppId gets a reference to the given NullableString and assigns it to the AppId field.
func (o *K8sAppSpecViewModel) SetAppId(v string) {
	o.AppId.Set(&v)
}
// SetAppIdNil sets the value for AppId to be an explicit nil
func (o *K8sAppSpecViewModel) SetAppIdNil() {
	o.AppId.Set(nil)
}

// UnsetAppId ensures that no value is present for AppId, not even an explicit nil
func (o *K8sAppSpecViewModel) UnsetAppId() {
	o.AppId.Unset()
}

func (o K8sAppSpecViewModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o K8sAppSpecViewModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["url_host"] = o.UrlHost
	toSerialize["url_scheme"] = o.UrlScheme
	if o.PromptFieldJsonPath.IsSet() {
		toSerialize["prompt_field_json_path"] = o.PromptFieldJsonPath.Get()
	}
	if o.KubernetesWorkloadName.IsSet() {
		toSerialize["kubernetes_workload_name"] = o.KubernetesWorkloadName.Get()
	}
	if o.MasCrdId.IsSet() {
		toSerialize["mas_crd_id"] = o.MasCrdId.Get()
	}
	if o.AppId.IsSet() {
		toSerialize["app_id"] = o.AppId.Get()
	}
	return toSerialize, nil
}

func (o *K8sAppSpecViewModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
		"url_host",
		"url_scheme",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varK8sAppSpecViewModel := _K8sAppSpecViewModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varK8sAppSpecViewModel)

	if err != nil {
		return err
	}

	*o = K8sAppSpecViewModel(varK8sAppSpecViewModel)

	return err
}

type NullableK8sAppSpecViewModel struct {
	value *K8sAppSpecViewModel
	isSet bool
}

func (v NullableK8sAppSpecViewModel) Get() *K8sAppSpecViewModel {
	return v.value
}

func (v *NullableK8sAppSpecViewModel) Set(val *K8sAppSpecViewModel) {
	v.value = val
	v.isSet = true
}

func (v NullableK8sAppSpecViewModel) IsSet() bool {
	return v.isSet
}

func (v *NullableK8sAppSpecViewModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableK8sAppSpecViewModel(val *K8sAppSpecViewModel) *NullableK8sAppSpecViewModel {
	return &NullableK8sAppSpecViewModel{value: val, isSet: true}
}

func (v NullableK8sAppSpecViewModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableK8sAppSpecViewModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


