/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MASFlowEdge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MASFlowEdge{}

// MASFlowEdge Observed caller→callee MCP call counts for a MAS.
type MASFlowEdge struct {
	CallerAppId string `json:"caller_app_id"`
	CalleeAppId string `json:"callee_app_id"`
	CallCount int32 `json:"call_count"`
	BlockedCount int32 `json:"blocked_count"`
}

type _MASFlowEdge MASFlowEdge

// NewMASFlowEdge instantiates a new MASFlowEdge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMASFlowEdge(callerAppId string, calleeAppId string, callCount int32, blockedCount int32) *MASFlowEdge {
	this := MASFlowEdge{}
	this.CallerAppId = callerAppId
	this.CalleeAppId = calleeAppId
	this.CallCount = callCount
	this.BlockedCount = blockedCount
	return &this
}

// NewMASFlowEdgeWithDefaults instantiates a new MASFlowEdge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMASFlowEdgeWithDefaults() *MASFlowEdge {
	this := MASFlowEdge{}
	return &this
}

// GetCallerAppId returns the CallerAppId field value
func (o *MASFlowEdge) GetCallerAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CallerAppId
}

// GetCallerAppIdOk returns a tuple with the CallerAppId field value
// and a boolean to check if the value has been set.
func (o *MASFlowEdge) GetCallerAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallerAppId, true
}

// SetCallerAppId sets field value
func (o *MASFlowEdge) SetCallerAppId(v string) {
	o.CallerAppId = v
}

// GetCalleeAppId returns the CalleeAppId field value
func (o *MASFlowEdge) GetCalleeAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CalleeAppId
}

// GetCalleeAppIdOk returns a tuple with the CalleeAppId field value
// and a boolean to check if the value has been set.
func (o *MASFlowEdge) GetCalleeAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CalleeAppId, true
}

// SetCalleeAppId sets field value
func (o *MASFlowEdge) SetCalleeAppId(v string) {
	o.CalleeAppId = v
}

// GetCallCount returns the CallCount field value
func (o *MASFlowEdge) GetCallCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CallCount
}

// GetCallCountOk returns a tuple with the CallCount field value
// and a boolean to check if the value has been set.
func (o *MASFlowEdge) GetCallCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallCount, true
}

// SetCallCount sets field value
func (o *MASFlowEdge) SetCallCount(v int32) {
	o.CallCount = v
}

// GetBlockedCount returns the BlockedCount field value
func (o *MASFlowEdge) GetBlockedCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BlockedCount
}

// GetBlockedCountOk returns a tuple with the BlockedCount field value
// and a boolean to check if the value has been set.
func (o *MASFlowEdge) GetBlockedCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockedCount, true
}

// SetBlockedCount sets field value
func (o *MASFlowEdge) SetBlockedCount(v int32) {
	o.BlockedCount = v
}

func (o MASFlowEdge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MASFlowEdge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["caller_app_id"] = o.CallerAppId
	toSerialize["callee_app_id"] = o.CalleeAppId
	toSerialize["call_count"] = o.CallCount
	toSerialize["blocked_count"] = o.BlockedCount
	return toSerialize, nil
}

func (o *MASFlowEdge) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"caller_app_id",
		"callee_app_id",
		"call_count",
		"blocked_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMASFlowEdge := _MASFlowEdge{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMASFlowEdge)

	if err != nil {
		return err
	}

	*o = MASFlowEdge(varMASFlowEdge)

	return err
}

type NullableMASFlowEdge struct {
	value *MASFlowEdge
	isSet bool
}

func (v NullableMASFlowEdge) Get() *MASFlowEdge {
	return v.value
}

func (v *NullableMASFlowEdge) Set(val *MASFlowEdge) {
	v.value = val
	v.isSet = true
}

func (v NullableMASFlowEdge) IsSet() bool {
	return v.isSet
}

func (v *NullableMASFlowEdge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMASFlowEdge(val *MASFlowEdge) *NullableMASFlowEdge {
	return &NullableMASFlowEdge{value: val, isSet: true}
}

func (v NullableMASFlowEdge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMASFlowEdge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


