/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CacheTokenLoadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheTokenLoadRequest{}

// CacheTokenLoadRequest struct for CacheTokenLoadRequest
type CacheTokenLoadRequest struct {
	TraceId string `json:"trace_id"`
	AppHost string `json:"app_host"`
	AppType AppType `json:"app_type"`
	Tool NullableString `json:"tool,omitempty"`
}

type _CacheTokenLoadRequest CacheTokenLoadRequest

// NewCacheTokenLoadRequest instantiates a new CacheTokenLoadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheTokenLoadRequest(traceId string, appHost string, appType AppType) *CacheTokenLoadRequest {
	this := CacheTokenLoadRequest{}
	this.TraceId = traceId
	this.AppHost = appHost
	this.AppType = appType
	return &this
}

// NewCacheTokenLoadRequestWithDefaults instantiates a new CacheTokenLoadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheTokenLoadRequestWithDefaults() *CacheTokenLoadRequest {
	this := CacheTokenLoadRequest{}
	return &this
}

// GetTraceId returns the TraceId field value
func (o *CacheTokenLoadRequest) GetTraceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value
// and a boolean to check if the value has been set.
func (o *CacheTokenLoadRequest) GetTraceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TraceId, true
}

// SetTraceId sets field value
func (o *CacheTokenLoadRequest) SetTraceId(v string) {
	o.TraceId = v
}

// GetAppHost returns the AppHost field value
func (o *CacheTokenLoadRequest) GetAppHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppHost
}

// GetAppHostOk returns a tuple with the AppHost field value
// and a boolean to check if the value has been set.
func (o *CacheTokenLoadRequest) GetAppHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppHost, true
}

// SetAppHost sets field value
func (o *CacheTokenLoadRequest) SetAppHost(v string) {
	o.AppHost = v
}

// GetAppType returns the AppType field value
func (o *CacheTokenLoadRequest) GetAppType() AppType {
	if o == nil {
		var ret AppType
		return ret
	}

	return o.AppType
}

// GetAppTypeOk returns a tuple with the AppType field value
// and a boolean to check if the value has been set.
func (o *CacheTokenLoadRequest) GetAppTypeOk() (*AppType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppType, true
}

// SetAppType sets field value
func (o *CacheTokenLoadRequest) SetAppType(v AppType) {
	o.AppType = v
}

// GetTool returns the Tool field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CacheTokenLoadRequest) GetTool() string {
	if o == nil || IsNil(o.Tool.Get()) {
		var ret string
		return ret
	}
	return *o.Tool.Get()
}

// GetToolOk returns a tuple with the Tool field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CacheTokenLoadRequest) GetToolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tool.Get(), o.Tool.IsSet()
}

// HasTool returns a boolean if a field has been set.
func (o *CacheTokenLoadRequest) HasTool() bool {
	if o != nil && o.Tool.IsSet() {
		return true
	}

	return false
}

// SetTool gets a reference to the given NullableString and assigns it to the Tool field.
func (o *CacheTokenLoadRequest) SetTool(v string) {
	o.Tool.Set(&v)
}
// SetToolNil sets the value for Tool to be an explicit nil
func (o *CacheTokenLoadRequest) SetToolNil() {
	o.Tool.Set(nil)
}

// UnsetTool ensures that no value is present for Tool, not even an explicit nil
func (o *CacheTokenLoadRequest) UnsetTool() {
	o.Tool.Unset()
}

func (o CacheTokenLoadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheTokenLoadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["trace_id"] = o.TraceId
	toSerialize["app_host"] = o.AppHost
	toSerialize["app_type"] = o.AppType
	if o.Tool.IsSet() {
		toSerialize["tool"] = o.Tool.Get()
	}
	return toSerialize, nil
}

func (o *CacheTokenLoadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"trace_id",
		"app_host",
		"app_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCacheTokenLoadRequest := _CacheTokenLoadRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCacheTokenLoadRequest)

	if err != nil {
		return err
	}

	*o = CacheTokenLoadRequest(varCacheTokenLoadRequest)

	return err
}

type NullableCacheTokenLoadRequest struct {
	value *CacheTokenLoadRequest
	isSet bool
}

func (v NullableCacheTokenLoadRequest) Get() *CacheTokenLoadRequest {
	return v.value
}

func (v *NullableCacheTokenLoadRequest) Set(val *CacheTokenLoadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheTokenLoadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheTokenLoadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheTokenLoadRequest(val *CacheTokenLoadRequest) *NullableCacheTokenLoadRequest {
	return &NullableCacheTokenLoadRequest{value: val, isSet: true}
}

func (v NullableCacheTokenLoadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheTokenLoadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


