/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CASAPolicyLlmEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CASAPolicyLlmEndpoint{}

// CASAPolicyLlmEndpoint External LLM endpoint this workload is allowed to reach.
type CASAPolicyLlmEndpoint struct {
	// FQDN of the allowed external LLM service
	Fqdn string `json:"fqdn"`
	// Port for the LLM service
	Port int32 `json:"port"`
}

type _CASAPolicyLlmEndpoint CASAPolicyLlmEndpoint

// NewCASAPolicyLlmEndpoint instantiates a new CASAPolicyLlmEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCASAPolicyLlmEndpoint(fqdn string, port int32) *CASAPolicyLlmEndpoint {
	this := CASAPolicyLlmEndpoint{}
	this.Fqdn = fqdn
	this.Port = port
	return &this
}

// NewCASAPolicyLlmEndpointWithDefaults instantiates a new CASAPolicyLlmEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCASAPolicyLlmEndpointWithDefaults() *CASAPolicyLlmEndpoint {
	this := CASAPolicyLlmEndpoint{}
	return &this
}

// GetFqdn returns the Fqdn field value
func (o *CASAPolicyLlmEndpoint) GetFqdn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fqdn
}

// GetFqdnOk returns a tuple with the Fqdn field value
// and a boolean to check if the value has been set.
func (o *CASAPolicyLlmEndpoint) GetFqdnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fqdn, true
}

// SetFqdn sets field value
func (o *CASAPolicyLlmEndpoint) SetFqdn(v string) {
	o.Fqdn = v
}

// GetPort returns the Port field value
func (o *CASAPolicyLlmEndpoint) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *CASAPolicyLlmEndpoint) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *CASAPolicyLlmEndpoint) SetPort(v int32) {
	o.Port = v
}

func (o CASAPolicyLlmEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CASAPolicyLlmEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fqdn"] = o.Fqdn
	toSerialize["port"] = o.Port
	return toSerialize, nil
}

func (o *CASAPolicyLlmEndpoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fqdn",
		"port",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCASAPolicyLlmEndpoint := _CASAPolicyLlmEndpoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCASAPolicyLlmEndpoint)

	if err != nil {
		return err
	}

	*o = CASAPolicyLlmEndpoint(varCASAPolicyLlmEndpoint)

	return err
}

type NullableCASAPolicyLlmEndpoint struct {
	value *CASAPolicyLlmEndpoint
	isSet bool
}

func (v NullableCASAPolicyLlmEndpoint) Get() *CASAPolicyLlmEndpoint {
	return v.value
}

func (v *NullableCASAPolicyLlmEndpoint) Set(val *CASAPolicyLlmEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableCASAPolicyLlmEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableCASAPolicyLlmEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCASAPolicyLlmEndpoint(val *CASAPolicyLlmEndpoint) *NullableCASAPolicyLlmEndpoint {
	return &NullableCASAPolicyLlmEndpoint{value: val, isSet: true}
}

func (v NullableCASAPolicyLlmEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCASAPolicyLlmEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


