/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LLMCallEndedEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMCallEndedEvent{}

// LLMCallEndedEvent Event emitted when an LLM call completes (recorded by the agent).
type LLMCallEndedEvent struct {
	Id *string `json:"id,omitempty"`
	UserInputId string `json:"user_input_id"`
	CreatedAt *string `json:"created_at,omitempty"`
	CallId string `json:"call_id"`
	Token string `json:"token"`
	AppId string `json:"app_id"`
	MasId NullableString `json:"mas_id,omitempty"`
	Response string `json:"response"`
	Tools NullableString `json:"tools"`
}

type _LLMCallEndedEvent LLMCallEndedEvent

// NewLLMCallEndedEvent instantiates a new LLMCallEndedEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMCallEndedEvent(userInputId string, callId string, token string, appId string, response string, tools NullableString) *LLMCallEndedEvent {
	this := LLMCallEndedEvent{}
	this.UserInputId = userInputId
	this.CallId = callId
	this.Token = token
	this.AppId = appId
	this.Response = response
	this.Tools = tools
	return &this
}

// NewLLMCallEndedEventWithDefaults instantiates a new LLMCallEndedEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMCallEndedEventWithDefaults() *LLMCallEndedEvent {
	this := LLMCallEndedEvent{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LLMCallEndedEvent) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMCallEndedEvent) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LLMCallEndedEvent) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LLMCallEndedEvent) SetId(v string) {
	o.Id = &v
}

// GetUserInputId returns the UserInputId field value
func (o *LLMCallEndedEvent) GetUserInputId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserInputId
}

// GetUserInputIdOk returns a tuple with the UserInputId field value
// and a boolean to check if the value has been set.
func (o *LLMCallEndedEvent) GetUserInputIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserInputId, true
}

// SetUserInputId sets field value
func (o *LLMCallEndedEvent) SetUserInputId(v string) {
	o.UserInputId = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *LLMCallEndedEvent) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMCallEndedEvent) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *LLMCallEndedEvent) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *LLMCallEndedEvent) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCallId returns the CallId field value
func (o *LLMCallEndedEvent) GetCallId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CallId
}

// GetCallIdOk returns a tuple with the CallId field value
// and a boolean to check if the value has been set.
func (o *LLMCallEndedEvent) GetCallIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallId, true
}

// SetCallId sets field value
func (o *LLMCallEndedEvent) SetCallId(v string) {
	o.CallId = v
}

// GetToken returns the Token field value
func (o *LLMCallEndedEvent) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *LLMCallEndedEvent) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *LLMCallEndedEvent) SetToken(v string) {
	o.Token = v
}

// GetAppId returns the AppId field value
func (o *LLMCallEndedEvent) GetAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *LLMCallEndedEvent) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *LLMCallEndedEvent) SetAppId(v string) {
	o.AppId = v
}

// GetMasId returns the MasId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMCallEndedEvent) GetMasId() string {
	if o == nil || IsNil(o.MasId.Get()) {
		var ret string
		return ret
	}
	return *o.MasId.Get()
}

// GetMasIdOk returns a tuple with the MasId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMCallEndedEvent) GetMasIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MasId.Get(), o.MasId.IsSet()
}

// HasMasId returns a boolean if a field has been set.
func (o *LLMCallEndedEvent) HasMasId() bool {
	if o != nil && o.MasId.IsSet() {
		return true
	}

	return false
}

// SetMasId gets a reference to the given NullableString and assigns it to the MasId field.
func (o *LLMCallEndedEvent) SetMasId(v string) {
	o.MasId.Set(&v)
}
// SetMasIdNil sets the value for MasId to be an explicit nil
func (o *LLMCallEndedEvent) SetMasIdNil() {
	o.MasId.Set(nil)
}

// UnsetMasId ensures that no value is present for MasId, not even an explicit nil
func (o *LLMCallEndedEvent) UnsetMasId() {
	o.MasId.Unset()
}

// GetResponse returns the Response field value
func (o *LLMCallEndedEvent) GetResponse() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Response
}

// GetResponseOk returns a tuple with the Response field value
// and a boolean to check if the value has been set.
func (o *LLMCallEndedEvent) GetResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Response, true
}

// SetResponse sets field value
func (o *LLMCallEndedEvent) SetResponse(v string) {
	o.Response = v
}

// GetTools returns the Tools field value
// If the value is explicit nil, the zero value for string will be returned
func (o *LLMCallEndedEvent) GetTools() string {
	if o == nil || o.Tools.Get() == nil {
		var ret string
		return ret
	}

	return *o.Tools.Get()
}

// GetToolsOk returns a tuple with the Tools field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMCallEndedEvent) GetToolsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tools.Get(), o.Tools.IsSet()
}

// SetTools sets field value
func (o *LLMCallEndedEvent) SetTools(v string) {
	o.Tools.Set(&v)
}

func (o LLMCallEndedEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMCallEndedEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["user_input_id"] = o.UserInputId
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	toSerialize["call_id"] = o.CallId
	toSerialize["token"] = o.Token
	toSerialize["app_id"] = o.AppId
	if o.MasId.IsSet() {
		toSerialize["mas_id"] = o.MasId.Get()
	}
	toSerialize["response"] = o.Response
	toSerialize["tools"] = o.Tools.Get()
	return toSerialize, nil
}

func (o *LLMCallEndedEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_input_id",
		"call_id",
		"token",
		"app_id",
		"response",
		"tools",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLLMCallEndedEvent := _LLMCallEndedEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLLMCallEndedEvent)

	if err != nil {
		return err
	}

	*o = LLMCallEndedEvent(varLLMCallEndedEvent)

	return err
}

type NullableLLMCallEndedEvent struct {
	value *LLMCallEndedEvent
	isSet bool
}

func (v NullableLLMCallEndedEvent) Get() *LLMCallEndedEvent {
	return v.value
}

func (v *NullableLLMCallEndedEvent) Set(val *LLMCallEndedEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMCallEndedEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMCallEndedEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMCallEndedEvent(val *LLMCallEndedEvent) *NullableLLMCallEndedEvent {
	return &NullableLLMCallEndedEvent{value: val, isSet: true}
}

func (v NullableLLMCallEndedEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMCallEndedEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


