/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the CASAPolicyStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CASAPolicyStatus{}

// CASAPolicyStatus Status of CASAPolicy CRD.
type CASAPolicyStatus struct {
	// Current phase of the policy
	Phase *CRDPhase `json:"phase,omitempty"`
	LastSyncTime *time.Time `json:"last_sync_time,omitempty"`
	// Human-readable status message
	Message NullableString `json:"message,omitempty"`
}

// NewCASAPolicyStatus instantiates a new CASAPolicyStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCASAPolicyStatus() *CASAPolicyStatus {
	this := CASAPolicyStatus{}
	var phase CRDPhase = PENDING
	this.Phase = &phase
	return &this
}

// NewCASAPolicyStatusWithDefaults instantiates a new CASAPolicyStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCASAPolicyStatusWithDefaults() *CASAPolicyStatus {
	this := CASAPolicyStatus{}
	var phase CRDPhase = PENDING
	this.Phase = &phase
	return &this
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *CASAPolicyStatus) GetPhase() CRDPhase {
	if o == nil || IsNil(o.Phase) {
		var ret CRDPhase
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CASAPolicyStatus) GetPhaseOk() (*CRDPhase, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *CASAPolicyStatus) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given CRDPhase and assigns it to the Phase field.
func (o *CASAPolicyStatus) SetPhase(v CRDPhase) {
	o.Phase = &v
}

// GetLastSyncTime returns the LastSyncTime field value if set, zero value otherwise.
func (o *CASAPolicyStatus) GetLastSyncTime() time.Time {
	if o == nil || IsNil(o.LastSyncTime) {
		var ret time.Time
		return ret
	}
	return *o.LastSyncTime
}

// GetLastSyncTimeOk returns a tuple with the LastSyncTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CASAPolicyStatus) GetLastSyncTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastSyncTime) {
		return nil, false
	}
	return o.LastSyncTime, true
}

// HasLastSyncTime returns a boolean if a field has been set.
func (o *CASAPolicyStatus) HasLastSyncTime() bool {
	if o != nil && !IsNil(o.LastSyncTime) {
		return true
	}

	return false
}

// SetLastSyncTime gets a reference to the given time.Time and assigns it to the LastSyncTime field.
func (o *CASAPolicyStatus) SetLastSyncTime(v time.Time) {
	o.LastSyncTime = &v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CASAPolicyStatus) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CASAPolicyStatus) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *CASAPolicyStatus) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *CASAPolicyStatus) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *CASAPolicyStatus) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *CASAPolicyStatus) UnsetMessage() {
	o.Message.Unset()
}

func (o CASAPolicyStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CASAPolicyStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.LastSyncTime) {
		toSerialize["last_sync_time"] = o.LastSyncTime
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	return toSerialize, nil
}

type NullableCASAPolicyStatus struct {
	value *CASAPolicyStatus
	isSet bool
}

func (v NullableCASAPolicyStatus) Get() *CASAPolicyStatus {
	return v.value
}

func (v *NullableCASAPolicyStatus) Set(val *CASAPolicyStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableCASAPolicyStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableCASAPolicyStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCASAPolicyStatus(val *CASAPolicyStatus) *NullableCASAPolicyStatus {
	return &NullableCASAPolicyStatus{value: val, isSet: true}
}

func (v NullableCASAPolicyStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCASAPolicyStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


