/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HttpRequestSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HttpRequestSchema{}

// HttpRequestSchema HTTP request schema for extracting the prompt field.
type HttpRequestSchema struct {
	// JSONPath to the prompt field in the HTTP request body
	PromptFieldJsonPath string `json:"promptFieldJsonPath"`
}

type _HttpRequestSchema HttpRequestSchema

// NewHttpRequestSchema instantiates a new HttpRequestSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpRequestSchema(promptFieldJsonPath string) *HttpRequestSchema {
	this := HttpRequestSchema{}
	this.PromptFieldJsonPath = promptFieldJsonPath
	return &this
}

// NewHttpRequestSchemaWithDefaults instantiates a new HttpRequestSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpRequestSchemaWithDefaults() *HttpRequestSchema {
	this := HttpRequestSchema{}
	return &this
}

// GetPromptFieldJsonPath returns the PromptFieldJsonPath field value
func (o *HttpRequestSchema) GetPromptFieldJsonPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PromptFieldJsonPath
}

// GetPromptFieldJsonPathOk returns a tuple with the PromptFieldJsonPath field value
// and a boolean to check if the value has been set.
func (o *HttpRequestSchema) GetPromptFieldJsonPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PromptFieldJsonPath, true
}

// SetPromptFieldJsonPath sets field value
func (o *HttpRequestSchema) SetPromptFieldJsonPath(v string) {
	o.PromptFieldJsonPath = v
}

func (o HttpRequestSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HttpRequestSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["promptFieldJsonPath"] = o.PromptFieldJsonPath
	return toSerialize, nil
}

func (o *HttpRequestSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"promptFieldJsonPath",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHttpRequestSchema := _HttpRequestSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHttpRequestSchema)

	if err != nil {
		return err
	}

	*o = HttpRequestSchema(varHttpRequestSchema)

	return err
}

type NullableHttpRequestSchema struct {
	value *HttpRequestSchema
	isSet bool
}

func (v NullableHttpRequestSchema) Get() *HttpRequestSchema {
	return v.value
}

func (v *NullableHttpRequestSchema) Set(val *HttpRequestSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpRequestSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpRequestSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpRequestSchema(val *HttpRequestSchema) *NullableHttpRequestSchema {
	return &NullableHttpRequestSchema{value: val, isSet: true}
}

func (v NullableHttpRequestSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpRequestSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


