/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MetricsSnapshot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetricsSnapshot{}

// MetricsSnapshot Pre-aggregated metrics snapshot.
type MetricsSnapshot struct {
	TotalMas int32 `json:"total_mas"`
	TokenRequests int32 `json:"token_requests"`
	McpCallsAllowed int32 `json:"mcp_calls_allowed"`
	McpCallsDenied int32 `json:"mcp_calls_denied"`
	TotalMcpCalls int32 `json:"total_mcp_calls"`
	DeterministicBlocks int32 `json:"deterministic_blocks"`
	AiPoweredBlocks int32 `json:"ai_powered_blocks"`
	BlockReasons []BlockReasonStat `json:"block_reasons"`
}

type _MetricsSnapshot MetricsSnapshot

// NewMetricsSnapshot instantiates a new MetricsSnapshot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricsSnapshot(totalMas int32, tokenRequests int32, mcpCallsAllowed int32, mcpCallsDenied int32, totalMcpCalls int32, deterministicBlocks int32, aiPoweredBlocks int32, blockReasons []BlockReasonStat) *MetricsSnapshot {
	this := MetricsSnapshot{}
	this.TotalMas = totalMas
	this.TokenRequests = tokenRequests
	this.McpCallsAllowed = mcpCallsAllowed
	this.McpCallsDenied = mcpCallsDenied
	this.TotalMcpCalls = totalMcpCalls
	this.DeterministicBlocks = deterministicBlocks
	this.AiPoweredBlocks = aiPoweredBlocks
	this.BlockReasons = blockReasons
	return &this
}

// NewMetricsSnapshotWithDefaults instantiates a new MetricsSnapshot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricsSnapshotWithDefaults() *MetricsSnapshot {
	this := MetricsSnapshot{}
	return &this
}

// GetTotalMas returns the TotalMas field value
func (o *MetricsSnapshot) GetTotalMas() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalMas
}

// GetTotalMasOk returns a tuple with the TotalMas field value
// and a boolean to check if the value has been set.
func (o *MetricsSnapshot) GetTotalMasOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalMas, true
}

// SetTotalMas sets field value
func (o *MetricsSnapshot) SetTotalMas(v int32) {
	o.TotalMas = v
}

// GetTokenRequests returns the TokenRequests field value
func (o *MetricsSnapshot) GetTokenRequests() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokenRequests
}

// GetTokenRequestsOk returns a tuple with the TokenRequests field value
// and a boolean to check if the value has been set.
func (o *MetricsSnapshot) GetTokenRequestsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenRequests, true
}

// SetTokenRequests sets field value
func (o *MetricsSnapshot) SetTokenRequests(v int32) {
	o.TokenRequests = v
}

// GetMcpCallsAllowed returns the McpCallsAllowed field value
func (o *MetricsSnapshot) GetMcpCallsAllowed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.McpCallsAllowed
}

// GetMcpCallsAllowedOk returns a tuple with the McpCallsAllowed field value
// and a boolean to check if the value has been set.
func (o *MetricsSnapshot) GetMcpCallsAllowedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.McpCallsAllowed, true
}

// SetMcpCallsAllowed sets field value
func (o *MetricsSnapshot) SetMcpCallsAllowed(v int32) {
	o.McpCallsAllowed = v
}

// GetMcpCallsDenied returns the McpCallsDenied field value
func (o *MetricsSnapshot) GetMcpCallsDenied() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.McpCallsDenied
}

// GetMcpCallsDeniedOk returns a tuple with the McpCallsDenied field value
// and a boolean to check if the value has been set.
func (o *MetricsSnapshot) GetMcpCallsDeniedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.McpCallsDenied, true
}

// SetMcpCallsDenied sets field value
func (o *MetricsSnapshot) SetMcpCallsDenied(v int32) {
	o.McpCallsDenied = v
}

// GetTotalMcpCalls returns the TotalMcpCalls field value
func (o *MetricsSnapshot) GetTotalMcpCalls() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalMcpCalls
}

// GetTotalMcpCallsOk returns a tuple with the TotalMcpCalls field value
// and a boolean to check if the value has been set.
func (o *MetricsSnapshot) GetTotalMcpCallsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalMcpCalls, true
}

// SetTotalMcpCalls sets field value
func (o *MetricsSnapshot) SetTotalMcpCalls(v int32) {
	o.TotalMcpCalls = v
}

// GetDeterministicBlocks returns the DeterministicBlocks field value
func (o *MetricsSnapshot) GetDeterministicBlocks() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DeterministicBlocks
}

// GetDeterministicBlocksOk returns a tuple with the DeterministicBlocks field value
// and a boolean to check if the value has been set.
func (o *MetricsSnapshot) GetDeterministicBlocksOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeterministicBlocks, true
}

// SetDeterministicBlocks sets field value
func (o *MetricsSnapshot) SetDeterministicBlocks(v int32) {
	o.DeterministicBlocks = v
}

// GetAiPoweredBlocks returns the AiPoweredBlocks field value
func (o *MetricsSnapshot) GetAiPoweredBlocks() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AiPoweredBlocks
}

// GetAiPoweredBlocksOk returns a tuple with the AiPoweredBlocks field value
// and a boolean to check if the value has been set.
func (o *MetricsSnapshot) GetAiPoweredBlocksOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AiPoweredBlocks, true
}

// SetAiPoweredBlocks sets field value
func (o *MetricsSnapshot) SetAiPoweredBlocks(v int32) {
	o.AiPoweredBlocks = v
}

// GetBlockReasons returns the BlockReasons field value
func (o *MetricsSnapshot) GetBlockReasons() []BlockReasonStat {
	if o == nil {
		var ret []BlockReasonStat
		return ret
	}

	return o.BlockReasons
}

// GetBlockReasonsOk returns a tuple with the BlockReasons field value
// and a boolean to check if the value has been set.
func (o *MetricsSnapshot) GetBlockReasonsOk() ([]BlockReasonStat, bool) {
	if o == nil {
		return nil, false
	}
	return o.BlockReasons, true
}

// SetBlockReasons sets field value
func (o *MetricsSnapshot) SetBlockReasons(v []BlockReasonStat) {
	o.BlockReasons = v
}

func (o MetricsSnapshot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetricsSnapshot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total_mas"] = o.TotalMas
	toSerialize["token_requests"] = o.TokenRequests
	toSerialize["mcp_calls_allowed"] = o.McpCallsAllowed
	toSerialize["mcp_calls_denied"] = o.McpCallsDenied
	toSerialize["total_mcp_calls"] = o.TotalMcpCalls
	toSerialize["deterministic_blocks"] = o.DeterministicBlocks
	toSerialize["ai_powered_blocks"] = o.AiPoweredBlocks
	toSerialize["block_reasons"] = o.BlockReasons
	return toSerialize, nil
}

func (o *MetricsSnapshot) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total_mas",
		"token_requests",
		"mcp_calls_allowed",
		"mcp_calls_denied",
		"total_mcp_calls",
		"deterministic_blocks",
		"ai_powered_blocks",
		"block_reasons",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMetricsSnapshot := _MetricsSnapshot{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMetricsSnapshot)

	if err != nil {
		return err
	}

	*o = MetricsSnapshot(varMetricsSnapshot)

	return err
}

type NullableMetricsSnapshot struct {
	value *MetricsSnapshot
	isSet bool
}

func (v NullableMetricsSnapshot) Get() *MetricsSnapshot {
	return v.value
}

func (v *NullableMetricsSnapshot) Set(val *MetricsSnapshot) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricsSnapshot) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricsSnapshot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricsSnapshot(val *MetricsSnapshot) *NullableMetricsSnapshot {
	return &NullableMetricsSnapshot{value: val, isSet: true}
}

func (v NullableMetricsSnapshot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricsSnapshot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


