/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// ToolCheckType Tool check types supported in MAS.
type ToolCheckType string

// List of ToolCheckType
const (
	DETERMINISTIC_TOOL_SELECTED ToolCheckType = "DETERMINISTIC_TOOL_SELECTED"
	DETERMINISTIC_LLM_SELECTED_TOOLS ToolCheckType = "DETERMINISTIC_LLM_SELECTED_TOOLS"
	AI_POWERED_TOOL_MATCH ToolCheckType = "AI_POWERED_TOOL_MATCH"
)

// All allowed values of ToolCheckType enum
var AllowedToolCheckTypeEnumValues = []ToolCheckType{
	"DETERMINISTIC_TOOL_SELECTED",
	"DETERMINISTIC_LLM_SELECTED_TOOLS",
	"AI_POWERED_TOOL_MATCH",
}

func (v *ToolCheckType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ToolCheckType(value)
	for _, existing := range AllowedToolCheckTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ToolCheckType", value)
}

// NewToolCheckTypeFromValue returns a pointer to a valid ToolCheckType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewToolCheckTypeFromValue(v string) (*ToolCheckType, error) {
	ev := ToolCheckType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ToolCheckType: valid values are %v", v, AllowedToolCheckTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ToolCheckType) IsValid() bool {
	for _, existing := range AllowedToolCheckTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ToolCheckType value
func (v ToolCheckType) Ptr() *ToolCheckType {
	return &v
}

type NullableToolCheckType struct {
	value *ToolCheckType
	isSet bool
}

func (v NullableToolCheckType) Get() *ToolCheckType {
	return v.value
}

func (v *NullableToolCheckType) Set(val *ToolCheckType) {
	v.value = val
	v.isSet = true
}

func (v NullableToolCheckType) IsSet() bool {
	return v.isSet
}

func (v *NullableToolCheckType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolCheckType(val *ToolCheckType) *NullableToolCheckType {
	return &NullableToolCheckType{value: val, isSet: true}
}

func (v NullableToolCheckType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolCheckType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

