/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LlmCallMappingStoreRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LlmCallMappingStoreRequest{}

// LlmCallMappingStoreRequest struct for LlmCallMappingStoreRequest
type LlmCallMappingStoreRequest struct {
	Id string `json:"id"`
	TraceId string `json:"trace_id"`
	Token string `json:"token"`
	Request NullableString `json:"request,omitempty"`
}

type _LlmCallMappingStoreRequest LlmCallMappingStoreRequest

// NewLlmCallMappingStoreRequest instantiates a new LlmCallMappingStoreRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLlmCallMappingStoreRequest(id string, traceId string, token string) *LlmCallMappingStoreRequest {
	this := LlmCallMappingStoreRequest{}
	this.Id = id
	this.TraceId = traceId
	this.Token = token
	return &this
}

// NewLlmCallMappingStoreRequestWithDefaults instantiates a new LlmCallMappingStoreRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLlmCallMappingStoreRequestWithDefaults() *LlmCallMappingStoreRequest {
	this := LlmCallMappingStoreRequest{}
	return &this
}

// GetId returns the Id field value
func (o *LlmCallMappingStoreRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LlmCallMappingStoreRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LlmCallMappingStoreRequest) SetId(v string) {
	o.Id = v
}

// GetTraceId returns the TraceId field value
func (o *LlmCallMappingStoreRequest) GetTraceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value
// and a boolean to check if the value has been set.
func (o *LlmCallMappingStoreRequest) GetTraceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TraceId, true
}

// SetTraceId sets field value
func (o *LlmCallMappingStoreRequest) SetTraceId(v string) {
	o.TraceId = v
}

// GetToken returns the Token field value
func (o *LlmCallMappingStoreRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *LlmCallMappingStoreRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *LlmCallMappingStoreRequest) SetToken(v string) {
	o.Token = v
}

// GetRequest returns the Request field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LlmCallMappingStoreRequest) GetRequest() string {
	if o == nil || IsNil(o.Request.Get()) {
		var ret string
		return ret
	}
	return *o.Request.Get()
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LlmCallMappingStoreRequest) GetRequestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Request.Get(), o.Request.IsSet()
}

// HasRequest returns a boolean if a field has been set.
func (o *LlmCallMappingStoreRequest) HasRequest() bool {
	if o != nil && o.Request.IsSet() {
		return true
	}

	return false
}

// SetRequest gets a reference to the given NullableString and assigns it to the Request field.
func (o *LlmCallMappingStoreRequest) SetRequest(v string) {
	o.Request.Set(&v)
}
// SetRequestNil sets the value for Request to be an explicit nil
func (o *LlmCallMappingStoreRequest) SetRequestNil() {
	o.Request.Set(nil)
}

// UnsetRequest ensures that no value is present for Request, not even an explicit nil
func (o *LlmCallMappingStoreRequest) UnsetRequest() {
	o.Request.Unset()
}

func (o LlmCallMappingStoreRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LlmCallMappingStoreRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["trace_id"] = o.TraceId
	toSerialize["token"] = o.Token
	if o.Request.IsSet() {
		toSerialize["request"] = o.Request.Get()
	}
	return toSerialize, nil
}

func (o *LlmCallMappingStoreRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"trace_id",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLlmCallMappingStoreRequest := _LlmCallMappingStoreRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLlmCallMappingStoreRequest)

	if err != nil {
		return err
	}

	*o = LlmCallMappingStoreRequest(varLlmCallMappingStoreRequest)

	return err
}

type NullableLlmCallMappingStoreRequest struct {
	value *LlmCallMappingStoreRequest
	isSet bool
}

func (v NullableLlmCallMappingStoreRequest) Get() *LlmCallMappingStoreRequest {
	return v.value
}

func (v *NullableLlmCallMappingStoreRequest) Set(val *LlmCallMappingStoreRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLlmCallMappingStoreRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLlmCallMappingStoreRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLlmCallMappingStoreRequest(val *LlmCallMappingStoreRequest) *NullableLlmCallMappingStoreRequest {
	return &NullableLlmCallMappingStoreRequest{value: val, isSet: true}
}

func (v NullableLlmCallMappingStoreRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLlmCallMappingStoreRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


