FROM golang:1.23-alpine AS builder

# Build the operator
WORKDIR /build
COPY ./operator ./operator
COPY ./sdk/go ./sdk/go
WORKDIR /build/operator
RUN go build -o casa-operator

RUN apk update \
    &&  apk add ca-certificates \
    &&  update-ca-certificates

FROM golang:1.23-alpine

# Create a group and user
RUN addgroup -S web && adduser -u 1999 -S -G web web

# Set workdir
WORKDIR /home/web

COPY --from=builder /build/operator/casa-operator .

# Give permissions
RUN chmod +x casa-operator && \
    chown -R web:web .

USER web

ENTRYPOINT ["./casa-operator"]
