FROM golang:1.25-alpine AS builder

# Build the package
WORKDIR /build
COPY ./ext_authz_middleware .
RUN go build -o ext-authz-middleware

RUN apk update \
    &&  apk add ca-certificates wget \
    &&  update-ca-certificates

FROM golang:1.25-alpine

# Create a group and user
RUN addgroup -S web && adduser -u 1999 -S -G web web

# Set workdir
WORKDIR /home/web

COPY --from=builder /build/ext-authz-middleware .

# Give permissions
RUN chmod +x ext-authz-middleware && \
    chown -R web:web .

USER web

ENTRYPOINT ["./ext-authz-middleware"]
