FROM python:3.12-slim

WORKDIR /app

RUN pip install uv

COPY demo/workshop/requirements.txt ./requirements.txt
RUN uv pip install --system -r requirements.txt

COPY pyproject.toml uv.lock LICENSE README.md ./
COPY src/ ./src/
RUN uv pip install --system .

COPY demo/workshop/source ./source
WORKDIR /app/source

EXPOSE 3999

CMD ["python", "main.py"]
