FROM golang:1.26-alpine AS builder

# Build the package
WORKDIR /build
COPY ./sidecar/ext_auth ./sidecar/ext_auth
COPY ./sdk/go ./sdk/go
WORKDIR /build/sidecar/ext_auth
RUN go build -o ext-auth-service

RUN apk update \
    &&  apk add ca-certificates wget \
    &&  update-ca-certificates

FROM golang:1.26-alpine

# Create a group and user
RUN addgroup -S web && adduser -u 1999 -S -G web web

# Set workdir
WORKDIR /home/web

COPY --from=builder /build/sidecar/ext_auth/ext-auth-service .

# Give permissions
RUN chmod +x ext-auth-service && \
    chown -R web:web .

USER web

ENTRYPOINT ["./ext-auth-service"]
