apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.agent.serviceName }}
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.agent.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.agent.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.agent.serviceName }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: {{ .Values.agent.serviceName }}
        image: {{ .Values.agent.docker.registry }}/{{ .Values.agent.docker.image }}:{{ .Values.agent.tagversion }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          allowPrivilegeEscalation: false
        ports:
        - containerPort: {{ .Values.agent.servicePort }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
        env:
            - name: OPENAI_API_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: OPENAI_API_BASE
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: OPENAI_API_KEY
