apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.agent.serviceName }}
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.agent.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.agent.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.agent.serviceName }}
    spec:
      imagePullSecrets:
        - name: regcred
      shareProcessNamespace: true
      serviceAccount: beyla
      containers:
      - name: {{ .Values.agent.serviceName }}
        image: {{ .Values.agent.docker.registry }}/{{ .Values.agent.docker.image }}:{{ .Values.agent.tagversion }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          allowPrivilegeEscalation: false
        ports:
        - containerPort: {{ .Values.agent.servicePort }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
        env:
            - name: OPENAI_API_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: OPENAI_API_BASE
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: OPENAI_API_KEY
      # Sidecar container with Beyla - the eBPF auto-instrumentation tool
      - name: beyla
        image: grafana/beyla:latest
        securityContext: # Privileges are required to install the eBPF probes
          privileged: true
        env:
          # The internal port of the application container
          - name: BEYLA_OPEN_PORT
            value: "8082"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://otel-collector-opentelemetry-collector:4318"
          - name: BEYLA_BPF_CONTEXT_PROPAGATION
            value: all
            # required if you want kubernetes metadata decoration
          - name: BEYLA_KUBE_METADATA_ENABLE
            value: "true"
