/*
FastAPI

Testing UserInputsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/cisco-eti/identity-auth-server/sdk/go"
)

func Test_api_UserInputsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UserInputsAPIService CreateUserInputUserInputsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.UserInputsAPI.CreateUserInputUserInputsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UserInputsAPIService GetAppUserInputsGetByTagTagGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tag string

		resp, httpRes, err := apiClient.UserInputsAPI.GetAppUserInputsGetByTagTagGet(context.Background(), tag).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
