/*
FastAPI

Testing ScopesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/cisco-eti/identity-auth-server/sdk/go"
)

func Test_api_ScopesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ScopesAPIService CreateScopeScopesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ScopesAPI.CreateScopeScopesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScopesAPIService DeleteScopeScopesScopeIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var scopeId string

		resp, httpRes, err := apiClient.ScopesAPI.DeleteScopeScopesScopeIdDelete(context.Background(), scopeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScopesAPIService GetScopeScopesScopeIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var scopeId string

		resp, httpRes, err := apiClient.ScopesAPI.GetScopeScopesScopeIdGet(context.Background(), scopeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScopesAPIService GetScopesScopesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ScopesAPI.GetScopesScopesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScopesAPIService UpdateScopeScopesScopeIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var scopeId string

		resp, httpRes, err := apiClient.ScopesAPI.UpdateScopeScopesScopeIdPut(context.Background(), scopeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
