/*
FastAPI

Testing KubernetesCRDsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/cisco-eti/identity-auth-server/sdk/go"
)

func Test_api_KubernetesCRDsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test KubernetesCRDsAPIService CreateMasCrdK8sNamespacesNamespaceMasPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespace string

		resp, httpRes, err := apiClient.KubernetesCRDsAPI.CreateMasCrdK8sNamespacesNamespaceMasPost(context.Background(), namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesCRDsAPIService DeleteMasCrdK8sNamespacesNamespaceMasNameDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespace string
		var name string

		httpRes, err := apiClient.KubernetesCRDsAPI.DeleteMasCrdK8sNamespacesNamespaceMasNameDelete(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesCRDsAPIService GetMasCrdK8sNamespacesNamespaceMasMasIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespace string
		var masId string

		resp, httpRes, err := apiClient.KubernetesCRDsAPI.GetMasCrdK8sNamespacesNamespaceMasMasIdGet(context.Background(), namespace, masId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesCRDsAPIService ListAllMasCrdsK8sMasGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KubernetesCRDsAPI.ListAllMasCrdsK8sMasGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesCRDsAPIService ListMasCrdsInNamespaceK8sNamespacesNamespaceMasGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespace string

		resp, httpRes, err := apiClient.KubernetesCRDsAPI.ListMasCrdsInNamespaceK8sNamespacesNamespaceMasGet(context.Background(), namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesCRDsAPIService LivenessProbeK8sHealthzGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KubernetesCRDsAPI.LivenessProbeK8sHealthzGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesCRDsAPIService ReadinessProbeK8sReadyzGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KubernetesCRDsAPI.ReadinessProbeK8sReadyzGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesCRDsAPIService UpdateMasCrdK8sNamespacesNamespaceMasNamePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.KubernetesCRDsAPI.UpdateMasCrdK8sNamespacesNamespaceMasNamePut(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesCRDsAPIService UpdateMasStatusK8sNamespacesNamespaceMasNameStatusPatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.KubernetesCRDsAPI.UpdateMasStatusK8sNamespacesNamespaceMasNameStatusPatch(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesCRDsAPIService WatchAllMasK8sWatchMultiagentsystemsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KubernetesCRDsAPI.WatchAllMasK8sWatchMultiagentsystemsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesCRDsAPIService WatchMasInNamespaceK8sWatchNamespacesNamespaceMultiagentsystemsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespace string

		resp, httpRes, err := apiClient.KubernetesCRDsAPI.WatchMasInNamespaceK8sWatchNamespacesNamespaceMultiagentsystemsGet(context.Background(), namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesCRDsAPIService WatchPoliciesInNamespaceK8sWatchNamespacesNamespaceZtapoliciesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespace string

		resp, httpRes, err := apiClient.KubernetesCRDsAPI.WatchPoliciesInNamespaceK8sWatchNamespacesNamespaceZtapoliciesGet(context.Background(), namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
