{{- if .Values.postgresAuth.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-auth-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "casa-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres-auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresAuth.persistence.size }}
  {{- if .Values.postgresAuth.persistence.storageClass }}
  storageClassName: {{ .Values.postgresAuth.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
