apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zta-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
data:
  admin-password: {{ .Values.keycloak.admin.password | b64enc | quote }}
  db-password: {{ .Values.postgresKeycloak.password | b64enc | quote }}
