# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if not .Values.authService.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-service-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "casa-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
type: Opaque
data:
  db-password: {{ .Values.authService.database.password | default "" | b64enc | quote }}
  idp-admin-password: {{ .Values.authService.idp.adminPassword | default "" | b64enc | quote }}
  openai-api-base-url: {{ .Values.authService.openai.apiBaseUrl | default "" | b64enc | quote }}
  openai-api-jwt-token: {{ .Values.authService.openai.jwtToken | default "" | b64enc | quote }}
  llm-api-base-url: {{ .Values.authService.openai.llmApiBaseUrl | default "" | b64enc | quote }}
  llm-api-key: {{ .Values.authService.openai.llmApiKey | default "" | b64enc | quote }}
{{- end }}
