# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from identity_auth_sdk.models.k8s_app_spec_view_model import K8sAppSpecViewModel
from identity_auth_sdk.models.k8s_multi_agent_system_metadata_view_model import K8sMultiAgentSystemMetadataViewModel
from typing import Optional, Set
from typing_extensions import Self

class K8sMultiAgentSystemCRDViewModel(BaseModel):
    """
    View model for a complete MultiAgentSystem CRD.
    """ # noqa: E501
    id: Optional[UUID] = None
    api_version: StrictStr
    kind: StrictStr
    namespace: StrictStr
    mas_metadata: Optional[K8sMultiAgentSystemMetadataViewModel] = None
    name: StrictStr
    enabled_tool_checks: Optional[List[StrictStr]]
    llm_host: Optional[StrictStr]
    app_specs: Optional[List[K8sAppSpecViewModel]] = None
    mas_id: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["id", "api_version", "kind", "namespace", "mas_metadata", "name", "enabled_tool_checks", "llm_host", "app_specs", "mas_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of K8sMultiAgentSystemCRDViewModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of mas_metadata
        if self.mas_metadata:
            _dict['mas_metadata'] = self.mas_metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in app_specs (list)
        _items = []
        if self.app_specs:
            for _item_app_specs in self.app_specs:
                if _item_app_specs:
                    _items.append(_item_app_specs.to_dict())
            _dict['app_specs'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if mas_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.mas_metadata is None and "mas_metadata" in self.model_fields_set:
            _dict['mas_metadata'] = None

        # set to None if enabled_tool_checks (nullable) is None
        # and model_fields_set contains the field
        if self.enabled_tool_checks is None and "enabled_tool_checks" in self.model_fields_set:
            _dict['enabled_tool_checks'] = None

        # set to None if llm_host (nullable) is None
        # and model_fields_set contains the field
        if self.llm_host is None and "llm_host" in self.model_fields_set:
            _dict['llm_host'] = None

        # set to None if mas_id (nullable) is None
        # and model_fields_set contains the field
        if self.mas_id is None and "mas_id" in self.model_fields_set:
            _dict['mas_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of K8sMultiAgentSystemCRDViewModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "api_version": obj.get("api_version"),
            "kind": obj.get("kind"),
            "namespace": obj.get("namespace"),
            "mas_metadata": K8sMultiAgentSystemMetadataViewModel.from_dict(obj["mas_metadata"]) if obj.get("mas_metadata") is not None else None,
            "name": obj.get("name"),
            "enabled_tool_checks": obj.get("enabled_tool_checks"),
            "llm_host": obj.get("llm_host"),
            "app_specs": [K8sAppSpecViewModel.from_dict(_item) for _item in obj["app_specs"]] if obj.get("app_specs") is not None else None,
            "mas_id": obj.get("mas_id")
        })
        return _obj


