# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from identity_auth_sdk.models.tool_check_flags import ToolCheckFlags
from typing import Optional, Set
from typing_extensions import Self

class MultiAgentSystem(BaseModel):
    """
    An entity describing a multi agent system, which is a set of apps.
    """ # noqa: E501
    id: Optional[UUID] = None
    name: StrictStr
    k8s_name: Optional[StrictStr] = None
    enabled_tool_checks: Optional[ToolCheckFlags] = None
    authorization_server_id: Optional[UUID]
    namespace: Optional[StrictStr]
    created_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "name", "k8s_name", "enabled_tool_checks", "authorization_server_id", "namespace", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MultiAgentSystem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if k8s_name (nullable) is None
        # and model_fields_set contains the field
        if self.k8s_name is None and "k8s_name" in self.model_fields_set:
            _dict['k8s_name'] = None

        # set to None if enabled_tool_checks (nullable) is None
        # and model_fields_set contains the field
        if self.enabled_tool_checks is None and "enabled_tool_checks" in self.model_fields_set:
            _dict['enabled_tool_checks'] = None

        # set to None if authorization_server_id (nullable) is None
        # and model_fields_set contains the field
        if self.authorization_server_id is None and "authorization_server_id" in self.model_fields_set:
            _dict['authorization_server_id'] = None

        # set to None if namespace (nullable) is None
        # and model_fields_set contains the field
        if self.namespace is None and "namespace" in self.model_fields_set:
            _dict['namespace'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MultiAgentSystem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "k8s_name": obj.get("k8s_name"),
            "enabled_tool_checks": obj.get("enabled_tool_checks"),
            "authorization_server_id": obj.get("authorization_server_id"),
            "namespace": obj.get("namespace"),
            "created_at": obj.get("created_at")
        })
        return _obj


