# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ToolCheckType(str, Enum):
    """
    Tool check types supported in MAS.
    """

    """
    allowed enum values
    """
    DETERMINISTIC_TOOL_SELECTED = 'DETERMINISTIC_TOOL_SELECTED'
    DETERMINISTIC_LLM_SELECTED_TOOLS = 'DETERMINISTIC_LLM_SELECTED_TOOLS'
    AI_POWERED_TOOL_MATCH = 'AI_POWERED_TOOL_MATCH'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ToolCheckType from a JSON string"""
        return cls(json.loads(json_str))


