{{- if .Values.chatUi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-chat-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-chat-ui
    component: demo
  {{- if .Values.chatUi.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.chatUi.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.chatUi.ingress.className }}
  tls:
  - hosts:
    - "{{ .Values.chatUi.ingress.domainPrefix }}.{{ .Values.chatUi.ingress.apiDomainName }}"
    secretName: "{{ .Release.Name }}-chat-ui-tls"
  rules:
  - host: "{{ .Values.chatUi.ingress.domainPrefix }}.{{ .Values.chatUi.ingress.apiDomainName }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-chat-ui
            port:
              number: 80
{{- end }}
