namespace: zta-control-plane-dev

agentSafe:
  replicas: 1
  serviceName: demo-agent-safe
  servicePort: 8082
  docker:
    registry: 626007623524.dkr.ecr.us-east-2.amazonaws.com
    image: outshift-zta/demo-agent-safe
    suffix: ''
  tagversion: latest
  mcp_server_url: http://zta-demo-mcp:3000/mcp

agentCompromised:
  replicas: 1
  serviceName: demo-agent-compromised
  servicePort: 8082
  docker:
    registry: 626007623524.dkr.ecr.us-east-2.amazonaws.com
    image: outshift-zta/demo-agent-compromised
    suffix: ''
  tagversion: latest
  mcp_server_url: http://zta-demo-mcp:3000/mcp

mcp:
  replicas: 1
  serviceName: zta-demo-mcp
  servicePort: 3000
  docker:
    registry: 626007623524.dkr.ecr.us-east-2.amazonaws.com
    image: outshift-zta/k8s-demo-mcp
    suffix: ''
  tagversion: 2026-03-16-a0d1194

mas:
  name: "ZTA Demo"
  enabledToolChecks:
    - DETERMINISTIC_TOOL_SELECTED