namespace: zta-control-plane-dev

agentSafe:
  replicas: 3
  serviceName: demo-agent-safe
  servicePort: 8082
  docker:
    registry: 626007623524.dkr.ecr.us-east-2.amazonaws.com
    image: outshift-zta/demo-agent-safe
    suffix: ''
  tagversion: 2026-04-22-d7b6dce
  mcp_server_url: http://zta-demo-mcp:3000/mcp

agentCompromised:
  replicas: 3
  serviceName: demo-agent-compromised
  servicePort: 8082
  docker:
    registry: 626007623524.dkr.ecr.us-east-2.amazonaws.com
    image: outshift-zta/demo-agent-compromised
    suffix: ''
  tagversion: 2026-04-22-d7b6dce
  mcp_server_url: http://zta-demo-mcp:3000/mcp

mcp:
  replicas: 1
  serviceName: zta-demo-mcp
  servicePort: 3000
  docker:
    registry: 626007623524.dkr.ecr.us-east-2.amazonaws.com
    image: outshift-zta/k8s-demo-mcp
    suffix: ''
  tagversion: 2026-04-22-d7b6dce

chatUis:
  - name: safe
    docker:
      registry: 626007623524.dkr.ecr.us-east-2.amazonaws.com
      image: outshift-zta/chat-ui
    tagversion: 2026-04-22-7c71381
    agentUrl: /safe-agent
    ingress:
      enabled: true
      className: "nginx"
      apiDomainName: "dev.outshift.ai"
      domainPrefix: "zta-demo-safe"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
  - name: compromised
    docker:
      registry: 626007623524.dkr.ecr.us-east-2.amazonaws.com
      image: outshift-zta/chat-ui
    tagversion: 2026-04-22-7c71381
    agentUrl: /compromised-agent
    ingress:
      enabled: true
      className: "nginx"
      apiDomainName: "dev.outshift.ai"
      domainPrefix: "zta-demo-compromised"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt

llmCredentials:
  apiBaseUrl: ""
  apiKey: ""

masSafe:
  name: "ZTA Demo Safe"
  enabledToolChecks:
    - DETERMINISTIC_TOOL_SELECTED
    - AI_POWERED_TOOL_MATCH
  llm_host: litellm.prod.outshift.ai

masCompromised:
  name: "ZTA Demo Compromised"
  enabledToolChecks:
    - DETERMINISTIC_TOOL_SELECTED
    - AI_POWERED_TOOL_MATCH
  llm_host: litellm.prod.outshift.ai
