namespace: zta-sidecar

agent:
  replicas: 1
  serviceName: zta-demo-agent
  servicePort: 8082
  docker:
    registry: 626007623524.dkr.ecr.us-east-2.amazonaws.com
    image: outshift-zta/k8s-demo-agent
    suffix: ''
  tagversion: 2026-03-16-a0d1194

  mcp_server_url: http://zta-demo-mcp:3000/mcp

  # We can move them later to an external vault when we needed
  secret:
    openai_api_base: https://litellm.prod.outshift.ai
    openai_api_key: SECRET_HERE

mcp:
  replicas: 1
  serviceName: zta-demo-mcp
  servicePort: 3000
  docker:
    registry: 626007623524.dkr.ecr.us-east-2.amazonaws.com
    image: outshift-zta/k8s-demo-mcp
    suffix: ''
  tagversion: 2026-03-16-a0d1194

mas:
  name: "ZTA Demo"
  authorizationServer: "zta-demo-realm"
  enabledToolChecks:
    - DETERMINISTIC_TOOL_SELECTED