{{- $root := . }}
{{- range .Values.chatUis }}
{{- if .ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $root.Release.Name }}-chat-ui-{{ .name }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    app: {{ $root.Release.Name }}-chat-ui-{{ .name }}
    component: demo
  {{- if .ingress.annotations }}
  annotations:
    {{- range $key, $value := .ingress.annotations }}
    {{ $key }}: {{ tpl $value $root | quote }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .ingress.className }}
  tls:
  - hosts:
    - "{{ .ingress.domainPrefix }}.{{ .ingress.apiDomainName }}"
    secretName: "{{ $root.Release.Name }}-chat-ui-{{ .name }}-tls"
  rules:
  - host: "{{ .ingress.domainPrefix }}.{{ .ingress.apiDomainName }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $root.Release.Name }}-chat-ui-{{ .name }}
            port:
              number: 80
{{- end }}
{{- end }}
