apiVersion: zta.io/v1alpha1
kind: MultiAgentSystem
metadata:
  name: zta-demo
  namespace: zta-control-plane-dev
spec:
  name: ZTA Demo
  enabledToolChecks:
    - DETERMINISTIC_TOOL_SELECTED
  apps:
    - name: zta-demo-agent
      type: agent
      baseUrl:
        host: zta-demo-agent:8082
        scheme: http
      kubernetesWorkloadName: zta-demo-agent
    - name: zta-demo-mcp
      type: mcp_server
      baseUrl:
        host: zta-demo-mcp:3000
        scheme: http
      kubernetesWorkloadName: zta-demo-mcp
