apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mcp.serviceName }}
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.mcp.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mcp.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.mcp.serviceName }}
    spec:
      {{- if .Values.mcp.docker.registry }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
      - name: {{ .Values.mcp.serviceName }}
        image: {{ if .Values.mcp.docker.registry }}{{ .Values.mcp.docker.registry }}/{{ end }}{{ .Values.mcp.docker.image }}:{{ .Values.mcp.tagversion }}
        imagePullPolicy: {{ if .Values.mcp.docker.registry }}Always{{ else }}Never{{ end }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          allowPrivilegeEscalation: false
        ports:
        - containerPort: {{ .Values.mcp.servicePort }}
