apiVersion: v1
kind: ServiceAccount
metadata:
  name: casa
  namespace: casa-ebpf-debug
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: casa
rules:
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "services", "nodes"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: casa
subjects:
  - kind: ServiceAccount
    name: casa
    namespace: casa-ebpf-debug
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: casa
