apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: traceparent-injector
  namespace: zta-sidecar
spec:
  url: oci://626007623524.dkr.ecr.us-east-2.amazonaws.com/outshift-zta/traceparent_injector_plugin:2026-04-08-75ec9fa
  imagePullPolicy: Always
  imagePullSecret: regcred
  phase: AUTHN
  match:
    - mode: SERVER
