apiVersion: v1
kind: ServiceAccount
metadata:
  name: ext-auth-service
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ext-auth-service
  namespace: '{{ .Release.Namespace }}'
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "deployments" ]
    verbs: [ "list", "get", "watch" ]
  - apiGroups: ["zta.io"]
    resources: ["multiagentsystems"]
    verbs: [ "list", "get", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ext-auth-service
  namespace: '{{ .Release.Namespace }}'
subjects:
  - kind: ServiceAccount
    name: ext-auth-service
    namespace: '{{ .Release.Namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ext-auth-service