---
version: '3.8'

name: zta-demo

services:
  ui:
    container_name: identity-ui
    build:
      context: ../../
      dockerfile: deployments/docker/demo/frontend/Dockerfile
    restart: always
    ports:
      - 5600:5600

  litellm:
    container_name: identity-litellm
    build:
      context: ../../
      dockerfile: deployments/docker/demo/litellm/Dockerfile
    restart: always
    ports:
      - 4000:4000
    env_file:
      - ../../.env
    environment:
      - AUTH_SERVER_URL=http://host.docker.internal:8000


  mcp-server:
    build:
      context: ../..
      dockerfile: deployments/docker/demo/Dockerfile.mcp
    container_name: identity-mcp-server
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - AUTH_SERVER_URL=http://host.docker.internal:8000

  agent:
    build:
      context: ../..
      dockerfile: deployments/docker/demo/Dockerfile.agent
    container_name: identity-agent
    ports:
      - "8082:8082"
    env_file:
      - ../../.env
    environment:
      - LITELLM_URL=http://host.docker.internal:4000
      - MCP_SERVER_URL=http://host.docker.internal:3000/mcp
      - MCP_SERVER_URL_FOR_AUTH=http://localhost:3000/mcp # address sent to the auth server so outside docker, will need to reunite this later
      - AUTH_SERVER_URL=http://host.docker.internal:8000
    restart: unless-stopped

  trusted-agent:
    build:
      context: ../..
      dockerfile: deployments/docker/demo/Dockerfile.source
    container_name: identity-trusted-agent
    ports:
      - "3999:3999"
    env_file:
      - ../../.env
    environment:
      - AUTH_SERVER_URL=http://host.docker.internal:8000
      - AGENT_CHAT_URL=http://host.docker.internal:8082/chat
    restart: unless-stopped
