---
name: zta-frontend
services:
  zta-ui:
    container_name: zta-ui
    image: zta-ui
    build:
      context: ../../
      dockerfile: deployments/docker/demo/frontend/Dockerfile
    restart: always
    ports:
      - 5600:5600
