apiVersion: v1
kind: Secret
metadata:
  name: llm-credentials
  namespace: '{{ .Release.Namespace }}'
type: Opaque
stringData:
  api-base-url: {{ .Values.llmCredentials.apiBaseUrl | quote }}
  api-key: {{ .Values.llmCredentials.apiKey | quote }}
