apiVersion: zta.io/v1alpha1
kind: MultiAgentSystem
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.mas.name }}
  authorizationServer: {{ .Values.mas.authorizationServer }}
  enabledToolChecks: {{ toYaml .Values.mas.enabledToolChecks | nindent 4 }}
  apps:
    - name: {{ .Values.agent.serviceName }}
      type: agent
      baseUrl: http://{{ .Values.agent.serviceName }}:{{ .Values.agent.servicePort }}
    - name: {{ .Values.mcp.serviceName }}
      type: mcp_server
      baseUrl: http://{{ .Values.mcp.serviceName }}:{{ .Values.mcp.servicePort }}
