# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: casa-llm-proxy
  namespace: {{ .Release.Namespace }}
spec:
  url: oci://{{ .Values.llm_proxy.image.repository }}:{{ .Values.llm_proxy.image.tag | default .Chart.AppVersion }}
  imagePullPolicy: {{ .Values.llm_proxy.image.pullPolicy | default "Always" }}
  {{- if .Values.llm_proxy.image.pullSecret }}
  imagePullSecret: {{ .Values.llm_proxy.image.pullSecret }}
  {{- end }}
  phase: AUTHN
  match:
    - mode: CLIENT
  vmConfig:
    env:
    - name: AUTH_SERVER_HOST
      value: {{ .Values.authServerHost }}
    - name: AUTH_SERVER_PORT
      value: {{ .Values.authServerPort | default "8000" | quote }}
