apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: casa-traceparent-injector
  namespace: {{ .Release.Namespace }}
spec:
  url: oci://{{ .Values.traceparent_injector.image.repository }}:{{ .Values.traceparent_injector.image.tag | default .Chart.AppVersion }}
  imagePullPolicy: {{ .Values.traceparent_injector.image.pullPolicy | default "Always" }}
  {{- if .Values.traceparent_injector.image.pullSecret }}
  imagePullSecret: {{ .Values.traceparent_injector.image.pullSecret }}
  {{- end }}
  phase: AUTHN
  match:
    - mode: SERVER
