FROM python:3.12-slim

WORKDIR /app

RUN pip install uv

COPY demo/workshop/requirements.txt ./requirements.txt
COPY pyproject.toml uv.lock LICENSE README.md ./
COPY src/ ./src/
COPY ./sdk ./sdk
RUN uv pip install --system .
RUN uv pip install --system -r requirements.txt

COPY demo/workshop/app/v2 ./v2
RUN uv pip install --system ./v2

COPY demo/workshop/app/auth.py ./
COPY demo/workshop/app/main.py ./
COPY demo/workshop/app/middleware.py ./

EXPOSE 8082

CMD ["python", "main.py"]
