{{- if .Values.authService.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-auth-service-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zta-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.authService.externalSecrets.secretStoreName }}
    kind: {{ .Values.authService.externalSecrets.secretStoreKind }}
  target:
    name: {{ .Release.Name }}-auth-service-secret
    creationPolicy: Owner
  data:
    {{- range .Values.authService.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}
{{- end }}
