{{- if not .Values.authService.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-service-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zta-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
type: Opaque
data:
  db-password: {{ .Values.authService.database.password | b64enc | quote }}
  idp-admin-password: {{ .Values.authService.idp.adminPassword | b64enc | quote }}
  openai-api-base-url: {{ .Values.authService.openai.apiBaseUrl | b64enc | quote }}
  openai-api-jwt-token: {{ .Values.authService.openai.jwtToken | b64enc | quote }}
{{- end }}
