apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: zta-llm-proxy
  namespace: {{ .Release.Namespace }}
spec:
  url: oci://{{ .Values.llm_proxy.image.repository }}:{{ .Values.llm_proxy.image.tag | default .Chart.AppVersion }}
  imagePullPolicy: {{ .Values.llm_proxy.image.pullPolicy | default "Always" }}
  imagePullSecret: {{ .Values.llm_proxy.image.pullSecret }}
  phase: AUTHN
  match:
    - mode: CLIENT
  vmConfig:
    env:
    - name: AUTH_SERVER_HOST
      value: "TODO: get it from the _helpers.tpl"
    - name: AUTH_SERVER_PORT
      value: "8000"
