apiVersion: v1
kind: Service
metadata:
  name: {{ include "ext-auth-service.fullname" . }}
  labels:
    {{- include "ext-auth-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 4100
      targetPort: grpc-inbound
      protocol: TCP
      name: grpc-inbound
    - port: 5100
      targetPort: grpc-outbound
      protocol: TCP
      name: grpc-outbound
  selector:
    {{- include "ext-auth-service.selectorLabels" . | nindent 4 }}
