# Copyright 2025 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

---
name: ZTA Control Plane CI/CD
on:
  push:
    branches:
      - "feature/PYRA-629-inject-traceparent"
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  packages: write # needed to push docker image to gar or ecr

jobs:
  ################################## checkout & unit tests ######################
  ###############################################################################
  checkout:
    name: checkout & unit test
    runs-on: ${{ vars.UBUNTU_RUNNER }}
    container:
      image: ${{ vars.DEFAULT_CONTAINER_RUNNER }}
      options: --user root
      credentials:
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # The branch, tag or SHA to checkout, otherwise, uses the default branch.
          ref: ${{ github.ref }}
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: ''
          # Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching
          # Default: true
          clean: true
          token: ${{ secrets.GHCR_TOKEN || github.token }}
          # Whether to download Git-LFS files
          # Default: false
          lfs: ''
          # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
          # recursively checkout submodules.
          # Default: false
          submodules: 'recursive'

  ################################## Docker build & push ##########################
  #################################################################################
  call-docker-build-push-auth-service:
    name: Call Docker Build Auth Service
    needs: [checkout]
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/build-push-docker.yaml@production

    secrets:
      # Only needed if with:ecr-enabled or with:gar-enabled is true below
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      ghcr-org-token: ${{ secrets.GHCR_TOKEN }}

    with:
      runner-group: ${{ vars.DEFAULT_ARC_RUNNERS }}
      ### REQUIRED
      ### Docker image name
      image-name: "identity-auth-server"

      ### path to where docker should copy files into image
      ### defaults to root of repository (.)
      context: .

      ### Dockerfile alternate name. Default is Dockerfile (relative to context path)
      dockerfile: deployments/docker/Dockerfile

      ### REQUIRED
      ### ENABLE ONE OR BOTH REGISTRIES
      ### tell docker where to push.
      ecr-enabled: true
      artifactory-devhub-enabled: false
      ghcr-enabled: true
      ghcr-org-registry: ${{ vars.GHCR_REGISTRY }}
      checkout-submodules: true

  call-docker-build-push-ui-explorer:
    name: Call Docker Build UI Explorer
    needs: [checkout]
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/build-push-docker.yaml@production

    secrets:
      # Only needed if with:ecr-enabled or with:gar-enabled is true below
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      ghcr-org-token: ${{ secrets.GHCR_TOKEN }}

    with:
      runner-group: ${{ vars.DEFAULT_ARC_RUNNERS }}
      ### REQUIRED
      ### Docker image name
      image-name: "identity-auth-server-ui"

      ### path to where docker should copy files into image
      ### defaults to root of repository (.)
      context: .

      npm-github-registry-enabled: true
      ### Dockerfile alternate name. Default is Dockerfile (relative to context path)
      dockerfile: deployments/docker/Dockerfile.ui
      ### REQUIRED
      ### ENABLE ONE OR BOTH REGISTRIES
      ### tell docker where to push.
      ecr-enabled: true
      artifactory-devhub-enabled: false
      ghcr-enabled: true
      ghcr-org-registry: ${{ vars.GHCR_REGISTRY }}
      checkout-submodules: true

  call-docker-build-push-keycloak:
    name: Call Docker Build Keycloak
    needs: [checkout]
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/build-push-docker.yaml@production

    secrets:
      # Only needed if with:ecr-enabled or with:gar-enabled is true below
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      ghcr-org-token: ${{ secrets.GHCR_TOKEN }}

    with:
      runner-group: ${{ vars.DEFAULT_ARC_RUNNERS }}
      ### REQUIRED
      ### Docker image name
      image-name: "identity-auth-server-keycloak"

      ### path to where docker should copy files into image
      ### defaults to root of repository (.)
      context: deployments/docker

      ### Dockerfile alternate name. Default is Dockerfile (relative to context path)
      dockerfile: deployments/docker/Dockerfile.keycloak
      ### REQUIRED
      ### ENABLE ONE OR BOTH REGISTRIES
      ### tell docker where to push.
      ecr-enabled: true
      artifactory-devhub-enabled: false
      ghcr-enabled: true
      ghcr-org-registry: ${{ vars.GHCR_REGISTRY }}
      checkout-submodules: true

  call-docker-build-push-extauthz:
    name: Call Docker Build ext-authz-middleware
    needs: [checkout]
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/build-push-docker.yaml@production
    secrets:
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      ghcr-org-token: ${{ secrets.GHCR_TOKEN }}
    with:
      runner-group: ${{ vars.DEFAULT_ARC_RUNNERS }}
      image-name: "outshift-zta/ext-authz-middleware"
      context: .
      dockerfile: deployments/docker/Dockerfile.extauthz
      ecr-enabled: true
      artifactory-devhub-enabled: false
      ghcr-enabled: false

  call-docker-build-push-wasm:
    name: Call Docker Build traceparent injector WASM plugin
    needs: [checkout]
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/build-push-docker.yaml@production
    secrets:
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      ghcr-org-token: ${{ secrets.GHCR_TOKEN }}
    with:
      runner-group: ${{ vars.DEFAULT_ARC_RUNNERS }}
      image-name: "outshift-zta/traceparent_injector_plugin"
      context: sidecar/traceparent_injector
      dockerfile: sidecar/traceparent_injector/Dockerfile
      ecr-enabled: true
      artifactory-devhub-enabled: false
      ghcr-enabled: false

  # ################################## Helm Publish #################################
  # #################################################################################
  call-helm-publish-zta-control-plane:
    name: Helm publish ZTA Control Plane
    needs: [checkout]
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/helm-publish.yaml@production
    with:
      runner-group: ${{ vars.DEFAULT_ARC_RUNNERS }}
      enable-chartmuseum: true
      enable-private-ecr: false
      enable-public-ecr: false
      checkout-submodules: true
      chart-path: deployments/k8s/helm/zta-control-plane
      # override-chart-version: ${{ needs.calculate-tags.outputs.chart_version }}
      #ecr-public-registry-alias: ${{ vars.ECR_PUBLIC_REGISTRY_ALIAS}}
    secrets:
      # GHCR Login for docker build runner
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}

  call-helm-publish-ext-authz-middleware:
    name: Helm publish ext-authz-middleware
    needs: [checkout]
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/helm-publish.yaml@production
    with:
      runner-group: ${{ vars.DEFAULT_ARC_RUNNERS }}
      enable-chartmuseum: true
      enable-private-ecr: false
      enable-public-ecr: false
      checkout-submodules: false
      chart-path: ext_authz_middleware/helm/ext-authz-middleware
    secrets:
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}

  ################################## Trigger Deployment ###########################
  #################################################################################

  utils:
    name: Utils
    needs: [checkout]
    runs-on: ${{ vars.UBUNTU_RUNNER }}
    container:
      image: ${{ vars.DEFAULT_CONTAINER_RUNNER }}
      options: --user root
      credentials:
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    outputs:
      image-tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Compute tag
        id: tag
        run: |
          git config --global --add safe.directory '*'
          DATE=$(date +'%Y-%m-%d')
          SHA=$(git rev-parse --short HEAD)
          echo "tag=$DATE-$SHA" >> $GITHUB_OUTPUT

  # ZTA Control Plane Deployment
  call-trigger-cd-auth-service:
    name: Trigger CD Auth Service
    needs: [
      call-docker-build-push-auth-service,
      call-docker-build-push-ui-explorer,
      call-docker-build-push-keycloak,
      call-helm-publish-zta-control-plane,
      utils
    ]
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/trigger-deploy.yaml@production
    with:
      deployment-repo: "cisco-eti/identity-auth-server-deployment"
      client-payload: '{"app-repository": "${{ github.repository }}", "values-file-path": "applications/zta-control-plane", "property-path": "authService.image.tag", "deployment-stage": "dev", "default-deployment": true, "value": "${{ needs.utils.outputs.image-tag }}"}'
    secrets:
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      ghcr-org-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-org-token: ${{ secrets.GHCR_TOKEN }}
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}

  call-trigger-cd-ui-explorer:
    name: Trigger CD UI Explorer
    needs: [
      call-docker-build-push-auth-service,
      call-docker-build-push-ui-explorer,
      call-docker-build-push-keycloak,
      call-helm-publish-zta-control-plane,
      utils
    ]
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/trigger-deploy.yaml@production
    with:
      deployment-repo: "cisco-eti/identity-auth-server-deployment"
      client-payload: '{"app-repository": "${{ github.repository }}", "values-file-path": "applications/zta-control-plane", "property-path": "uiExplorer.image.tag", "deployment-stage": "dev", "default-deployment": true, "value": "${{ needs.utils.outputs.image-tag }}"}'
    secrets:
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      ghcr-org-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-org-token: ${{ secrets.GHCR_TOKEN }}
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}

  call-trigger-cd-keycloak:
    name: Trigger CD Keycloak
    needs: [
      call-docker-build-push-auth-service,
      call-docker-build-push-ui-explorer,
      call-docker-build-push-keycloak,
      call-helm-publish-zta-control-plane,
      utils
    ]
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/trigger-deploy.yaml@production
    with:
      deployment-repo: "cisco-eti/identity-auth-server-deployment"
      client-payload: '{"app-repository": "${{ github.repository }}", "values-file-path": "applications/zta-control-plane", "property-path": "keycloak.image.tag", "deployment-stage": "dev", "default-deployment": true, "value": "${{ needs.utils.outputs.image-tag }}"}'
    secrets:
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      ghcr-org-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-org-token: ${{ secrets.GHCR_TOKEN }}
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}

  # ZTA (ext-authz-middleware) Deployment
  call-trigger-cd-extauthz:
    name: Trigger CD ext-authz-middleware
    needs: [
      call-docker-build-push-extauthz,
      call-helm-publish-ext-authz-middleware,
      utils
    ]
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/trigger-deploy.yaml@production
    with:
      deployment-repo: "cisco-eti/identity-auth-server-deployment"
      client-payload: '{"app-repository": "${{ github.repository }}", "values-file-path": "applications/zta-authz-middleware", "property-path": "image.tag", "deployment-stage": "dev", "default-deployment": true, "value": "${{ needs.utils.outputs.image-tag }}"}'
    secrets:
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      ghcr-org-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-org-token: ${{ secrets.GHCR_TOKEN }}
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
