name: Build and push the envoy ext-auth filter to docker registry

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: checkout
    runs-on:
      group: arc-runner-set
    container:
      image: ${{ vars.DEFAULT_CONTAINER_RUNNER }}
      options: --user root
      credentials:
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
        with:
          ref: ${{ github.ref }}
          path: ''
          clean: true

      - name: Import Vault Secrets for Artifactory
        uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
        with:
          url: ${{ vars.KEEPER_URL }}
          method: approle
          roleId: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
          secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
          namespace: ${{ vars.VAULT_NAMESPACE }}
          secrets: |
            ${{ vars.VAULT_SECRET_PATH }} ARTIFACTORY_USER | ARTIFACTORY_USER ;
            ${{ vars.VAULT_SECRET_PATH }} ARTIFACTORY_DEVHUB_DOCKER_TOKEN | ARTIFACTORY_DEVHUB_DOCKER_TOKEN

      - name: Login to Artifactory DevHub
        run: |
          echo "${{ env.ARTIFACTORY_DEVHUB_DOCKER_TOKEN }}" | docker login artifactory.devhub-cloud.cisco.com -u "${{ env.ARTIFACTORY_USER }}" --password-stdin

  prepare-release:
    name: Prepare Release
    needs: [checkout]
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set version
        id: set-version
        run: echo "version=$(echo "$GITHUB_REF" | cut -d / -f 3 | cut -c2-)" >> "$GITHUB_OUTPUT"

  docker-build-push-extauthz:
    name: Build & Push k8s demo agent
    needs: [prepare-release]
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/build-push-docker.yaml@production
    secrets:
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      ghcr-org-token: ${{ secrets.GHCR_TOKEN }}
    with:
      runner-group: arc-runner-set
      image-name: "outshift-zta/ext-authz-middleware"
      image-custom-tag: ${{ needs.prepare-release.outputs.version }}
      context: .
      dockerfile: deployments/docker/Dockerfile.extauthz
      ecr-enabled: true
      artifactory-devhub-enabled: true
      ghcr-enabled: false

  reusable-workflow-ci-status:
    name: Reusable Workflow CI Status
    # This should be an array of ALL active jobs that are used/run
    needs: [
      checkout,
      docker-build-push-extauthz
    ]
    if: always()
    runs-on:
      group: arc-runner-set
    steps:
      - name: report failure
        if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
        run: |
          echo -e "\033[31m*** WORKFLOW FAILED ***\033[0m"
          exit 1
      - name: report success
        run: |
          echo -e "\033[1;36m*** WORKFLOW SUCCEEDED ***\033[0m"
          exit 0