# Copyright 2026 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

---
name: pytest

on:
    pull_request:
    push:
        branches: [main]
    workflow_call:

defaults:
    run:
        shell: bash -l {0}

jobs:
    pytest:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install needed utilities
              run: |
                  python -m pip install --upgrade pip
                  pip install uv

            - name: Create virtual environment
              run: |
                  uv venv

            - name: Install dependencies
              run: |
                  uv sync --extra dev

            - name: Run pytest
              run: |
                  source .venv/bin/activate
                  pytest
